### ISSUE TITLE
Incomplete Tasks

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#100]
The following methods are listed in MAS, but they do not work, are not tested, or are incomplete.  I need to verify them...

- [x] fc.EnableAllRCS() - untested - used to switch on RCS ports that were disabled.
- [x] nav.CrossTrackDistance() and nav.CrossTrackDistanceFromVessel() - untested
- [x] nav.IntersectionOfTwoPathsLatitude() and nav.IntersectionOfTwoPathsLongitude() - untested
- [x] fc.Crew*() with localSeat = false - not implemented
- [x] fc.Seat*() with localSeat = false - also not implemented
- [x] fc.Mass() with wetMass = false - dry mass is not implemented
- [x] fc.PlayAudio() - not implemented
- [x] fc.TargetType() - Target type 5 (asteroid) is not implemented.
- [x] transfer.RelativeEjectionAngle() - not implemented.
- [x] transfer.TimeUntilEjection() - not implemented.
- [x] transfer.TransferEjectionAngle() - not implemented.

**Comment by MOARdV** [comment]
I am considering dropping the Crew and Seat functions with localSeat = false, since it is costly to update for the full ship.  I would have to iterate over all of the parts of the ship, and check each one for crew for every FixedUpdate.  This would make all crew and seat functions local to the current pod only.

**Comment by Alexustas** [comment]
> crew and seat functions local to the current pod only.

I think that is enough

**Comment by MOARdV** [comment]
Actually, it looks like Squad made it easier to access the entire crew roster.  However, I will make separate methods to access that list, since it is only a list of crew, and not seat assignments.

**Comment by Alexustas** [comment]
Just to let you know. 
I'm really looking forward to when you complete [this request](https://github.com/MOARdV/AvionicsSystems/issues/90) and `fc.PlayAudio().` the absence of these features is not allowed to work in the order in which it would be most effective
