### ISSUE TITLE
ApproachSolver does not handle SoI changes well

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#101]
It does not generate results that match stock during basic Kerbin - Mun transfers.

**Comment by MOARdV** [comment]
Fixed on [DropBox](https://www.dropbox.com/s/qbqmz1j33b4mdbv/AvionicsSystems-0.12.0b1.zip?dl=0).

**Comment by Alexustas** [comment]
situation:

  my vessel orbiting Kerbin and
  target vessel orbiting Kerbin and
  I've created maneuver and result of the maneuver is escaping to the Sun orbit.

![screenshot81](https://user-images.githubusercontent.com/6713671/37565267-fdd06270-2ac7-11e8-8b85-44250f631947.png)


Closest Approach solver returns abnormal results 

![screenshot83](https://user-images.githubusercontent.com/6713671/37565268-053191ba-2ac8-11e8-84ee-ccd6207aaabb.png)
![screenshot84](https://user-images.githubusercontent.com/6713671/37565269-06b56714-2ac8-11e8-95da-ac8812a2f0bd.png)


and the MAS displays an error message 

```
[ERR 15:49:55.580] [MASFlightComputer] FixedUpdate exception on variable (fc.SIFormatValue)((fc.ManeuverNodeTargetClosestApproachDistance)(), 8, 0, "'", false, false)

[ERR 15:49:55.581] [MASFlightComputer] MASFlightComputer.FixedUpdate exception: System.NullReferenceException: Object reference not set to an instance of an object
  at AvionicsSystems.MASFlightComputer+Variable.ProcessObject (System.Object value) [0x00000] in <filename unknown>:0 
  at AvionicsSystems.MASFlightComputer+Variable.Evaluate (MoonSharp.Interpreter.Script script) [0x00000] in <filename unknown>:0 
  at AvionicsSystems.MASFlightComputer.FixedUpdate () [0x00000] in <filename unknown>:0 
```

**Comment by MOARdV** [comment]
I think I need to change the solver so that it returns 0 for complex situations.  There is a lot of complexity that my current code can not solve.

**Comment by MOARdV** [comment]
One thing that will change when I fix this bug: if a maneuver node exists, the Target Closest Approach functions will report the same thing as the Maneuver Node Target Closest Approach.  The Maneuver Node versions of this function will be redundant, except that they report 0 if no target exists.  Will we still need Maneuver Node versions of the target closest approach?

**Comment by MOARdV** [comment]
I think Closest Approach is fixed.  Test build is available on [DropBox](https://www.dropbox.com/s/9cc0g2hyage21cg/AvionicsSystems-0.15.0b1.zip?dl=0).
