### ISSUE TITLE
Request. "Stop warp" action

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#103]
Since I'm going to add some automation to the IVA, I critically need the ability to stop the Warp (if it's active)

**Comment by MOARdV** [comment]
Added this in.  I will release a beta with it this weekend.

**Comment by Alexustas** [comment]
by the way. can you somehow help me with calculating the exact time of stopping the warp? I tried to see how this is implemented in KAC mode, but I do not know C # and I did not understand anything in this code

**Comment by MOARdV** [comment]
I can help.

Do you want an "ASET Alarm Clock" that does not need KAC?

What event is it you want to stop warp?  is it for a maneuver, or do you have your own alarm timer?

**Comment by Alexustas** [comment]
I almost finished my own timer.

https://youtu.be/oIXcIJ7T_oQ

I plan to use it as an alarm clock and as a trigger for running some events, such as starting the engine or toggling the specified action groups and for some other automation. 

for the convenience of using this system, I need to be able to stop the Warp if it was started by the user.

in other words, I need to be able to make sure that Warp stops exactly at the specified time. This time is generated by the script. for example, stopping the warp in 20 seconds before the timer "A" reaches zero or "_at Timer "A" T-20_"

**Comment by MOARdV** [comment]
I think I have an answer, but today was busy and I am tired, so the answer may be wrong.

```Lua
-- Set to zero so there are no errors caused by subtracting a 'nil' value
local nextAlarmTime = 0

-- Action when the user starts the timer
function AlarmOn()
   nextAlarmTime = fc.UT() + [user alarm number of seconds]
end

-- Called as a variable, maybe to display "time until alarm"
function CheckAlarm()
  if nextAlarmTime == 0 then
    -- nextAlarmTime is zero.  Alarm not active.
    return 0
  end

  local timeRemaining = nextAlarmTime - fc.UT()
  if timeRemaining < 0 then
    -- Alarm is in the past, do not do anything
    return 0 -- or return timeRemaining, so you can display how long ago the alarm was?
  else
    -- If alarm is less than one second away (timeRemaining < 1), and warp is active, cancel warp.
    if timeRemaining < 1 and fc.WarpRate() > 1 then
      fc.CancelTimeWarp()
    end

    -- Return number of seconds until alarm.
    return timeRemaining
  end
end
```

I think this works, but I have not tested.

**Comment by Alexustas** [comment]
I did not express it accurately enough. The fact is that Warp does not stop instantly. at high Warp  rates can go through a lot of in-game time between the "cancel warp" command and the return in real time.
and I need to be able to calculate the required command time so that the ship returns in real time at the specified time or no later than the specified time

**Comment by MOARdV** [comment]
Oh, okay.  It is possible to tell the warp to stop instantly.  I will add that as a parameter to CancelTimeWarp

**Comment by MOARdV** [comment]
Updated on [DropBox](https://www.dropbox.com/s/qbqmz1j33b4mdbv/AvionicsSystems-0.12.0b1.zip?dl=0).  Also added `fc.ColorTag(r, g, b)` and `fc.ColorTag(r, g, b, a)` ([see](https://github.com/MOARdV/AvionicsSystems/wiki/MASFlightComputerProxy2#fccolortagdouble-red-double-green-double-blue)) to create variable-controlled color tags.

**Comment by Alexustas** [comment]
>  It is possible to tell the warp to stop instantly.

it's so unexpected. 
I've never seen such a thing before in a regular game or in mods (like MJ or KAC)

**Comment by Alexustas** [comment]
I did some tests and that's it. 

https://youtu.be/wlg7imJrPR0

At large Warp rates, we still have an "overshot". I think I need to be able to slow down the Warp in advance to a lower level (eg to x50) first  , and then make a reset at the exact time. So I need something like "fc.setWarp(value,true/false)"

**Comment by MOARdV** [comment]
This overshoot makes sense.  FixedUpdate fires 10x per second.  At warp 1000, each FixedUpdaate = 100 seconds.  I think this is why KAC changes speeds before the alarm time, also.  I will add the SetWarp action.

**Comment by MOARdV** [comment]
I can do better than only SetWarp.  I can add WarpTo.  Stock KSP has this option, so I can add `fc.WarpTo(UT)`, so you tell it what time you want the warp to stop, and KSP can warp to that time.  The only problem is it shows the text on the middle of the screen showing how long remains.

**Comment by Alexustas** [comment]
I need both ))

**Comment by MOARdV** [comment]
Okay, it was easy.  On [DropBox](https://www.dropbox.com/s/qbqmz1j33b4mdbv/AvionicsSystems-0.12.0b1.zip?dl=0).  SetWarp only works for time warp, not physics (atmosphere) warp.

`fc.SetWarp(double warpRate, bool instantChange)`, `fc.WarpTo(double UT)`.

**Comment by Alexustas** [comment]
`fc.SetWarp(double warpRate, bool instantChange)` work fine, Thank you!
`fc.WarpTo(double UT) ` I have not tested yet, because I do not have prop for this
