### ISSUE TITLE
Expose a state machine?

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#112]
I discovered today that KSP has some classes that allow for creating state machines, and it looks like they could be done at run-time (meaning, from a config file).  A state machine would allow for doing something drastically more complex than the [TRIGGER_EVENT](https://github.com/MOARdV/AvionicsSystems/wiki/MASComponent#trigger_event) feature in MASComponent, including all sorts of automation capabilities.

**Comment by theonegalen** [comment]
I just read an article about state machines and I still am not sure how to use one or what I would use it for. I know RPM and MAS have a lot of functions that evaluate what the states of switches, engines, and the craft are. Would this basically allow us to define more complex states ourselves without them having to be coded by you into the interface?

Or, for example, if I wanted to make a cockpit that worked in both SI and Imperial units, could I define those states in the config file so MAS would basically rework the instruments in the cockpit on the fly, using imperial versions of the variables without having to make all new props like I've done on the RPM version of my cockpits?

I am very much not a computer science guy, so I'm kind of struggling with these concepts.

**Comment by MOARdV** [comment]
A state machine is a way to organize possibly complex behaviors that can be described as distinct phases with identifiable transitions.  In KSP, probably the best known state machine behaviors are in MechJeb.  All of the autopilots are state machines - for instance, the ascent autopilot's different phases are each states with rules for which states they will transition to (waiting to launch, vertical ascent, gravity turn, coast to atmosphere, coast to apoapsis, circularization).  KSP itself is a state machine - it starts with the loading screen, transitions to the Main Menu, where you can go to a variety of different scenes (states).

Some other ideas in-game - automated aircraft landing gear.  The state machine would raise gear at a given altitude, lower them at a given altitude, warn you when you're overspeed with gear down.

For a cockpit that works in both SI and Imperial - as long as the physical props don't have to change, you could use a persistent variable (or a few, actually) to convert units:

```
fc.Altitude() * fc.GetPersistentAsNumber("Distance_Scalar")
```
where the persistent "Distance_Scalar" is 1 for metric, and 3.29whatever to convert to feet.  You'd do the same thing with a speed scalar that converts m/s to knots, and one for m/s to ft/s.  You could conceivably have a switch in the cockpit that lets you change it on the fly.

The tricky part is captions on the props - if it's part of a texture, you'd need to use MAS's texture swapping.  If the caption is a label that used JSILabel in RPM, then you can change the displayed text on the prop in-flight by keying off of a variable.

**Comment by theonegalen** [comment]
Ah, I see. So if I wanted to have a cockpit that automatically deployed flaps to different extension depending on speed and altitude, I could do that with a state machine, or something that would trigger auto speed brake, drag chute, and thrust reverser on ground contact? Though it send like I could do both of those things with variables as well.

Would a state machine be useful for something like creating a flight plan for MA SInavigation where you can define a series of waypoints and it will switch to each of them in order as you pass within a few kilometers of each one? Being able to have user-defined flight planning on the fly through an MFD or unity UI element would be amazing.

**Comment by MOARdV** [comment]
> Ah, I see. So if I wanted to have a cockpit that automatically deployed flaps to different extension depending on speed and altitude, I could do that with a state machine.

Yes, that would be another possibility.  I really need to come up with a good example where a state machine's value can be explained.  A good example would become really complex, but the simple examples tend to be cases where it's easy to implement them in a different way.

**Comment by MOARdV** [comment]
So that I don't forget where I found this later ... the state machine is KerbalFSM.  If I figure it out, it'll be useful for the MAS autopilot implementations (maneuver autopilot and launch autopilot).

**Comment by MOARdV** [comment]
I think I'm going to punt on this one.  The state machine is useful in the autopilot that I'm creating, but I think it's going to be way too difficult to use and too marginal to be useful for IVA creators.
