### ISSUE TITLE
KSP 1.4 / Unity  2017.1.3p1 updates

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#117]
ugh...

- [x] Lots of Unity-related updates due to LineRenderer.
- [x] Shaders don't work - don't know if updating Unity is sufficient.

**Comment by theonegalen** [comment]
Thank you.

**Comment by MOARdV** [comment]
LineRenderer changes appear trivial, fortunately.  Updated Unity, and I've been fighting with it to export shaders.  Someday I'll actually document what needs to be done to get them exporting again, instead of me repeatedly having to relearn the process to get everything working after an update.

**Comment by MOARdV** [comment]
This is ready - just waiting on KSP 1.4.1 to drop in case that causes the need to rebuild.  Also going to get some minor features in for v0.13.0
