### ISSUE TITLE
Radio Navigation Markers

### ISSUE THREAD

**Issue by lazar2222** [MOARdV/AvionicsSystems#118]
Maybe you could add runway radio markers since alexustas has them in ASET avionics and you are kind of basing your radio system on his charts.

**Comment by MOARdV** [comment]
I'm not sure which runway radio markers you mean.  All of the radio nav markers from the Kerbin Aerocharts are already included in MAS, including the KSP runway ILS markers.  Are there some other markers that are missing?

**Comment by lazar2222** [comment]
I`m talking about these:
https://i.imgur.com/nt7Vh1n.jpg
Essentially they are radio which only transmit in very limited range above transmitter and when plane passes over them pilot gets audio and visual cue, and they are placed on varying distances from runway threshold aligned with the center-line. more info: https://en.wikipedia.org/wiki/Marker_beacon

**Comment by Alexustas** [comment]
@lazar2222 
This feature is implemented (in the RPM) through the corresponding props and configs and does not require any additional mechanisms in the plugin. In the MAS, all this will be implemented in the same way.

**Comment by lazar2222** [comment]
So it will be based on DME reading and ILS deviation i suppose?

**Comment by Alexustas** [comment]
I plan to implement the work of markers as follows:
first, the navigation radio must receive the ILS signal.
further, if the ground distance from your craft to the beacon becomes less than the specified value, then the script works and you hear the corresponding signal and you see the "O", "M" or "I" warning light. The distance of the signal reception varies depending on the radar altitude of the aircraft

**Comment by lazar2222** [comment]
Great, thanks for explanation.
