### ISSUE TITLE
Crashes?

### ISSUE THREAD

**Issue by DeputyLOL** [MOARdV/AvionicsSystems#12]
I really have no idea if this is MAS that is doing this but I managed to get a fairly consistent method of using KSP. Loading a flight now works. Going from a flight to space centre crashes the game instantly.

And I have to always 'Verify integrity of game cache' through steam before I can play it again. Steam always finds and replaces 1 file that 'failed to validate'

I have tried reinstalling KSP but the same thing started happening. I have no idea what could be causing it, but it seemed to start with MAS being installed.

**Comment by MOARdV** [comment]
It's possible - I'm not sure how I would be crashing KSP.  I'll have another dev build sometime today, I think, so we'll need to try with it.

One thing you can do if you have the disk space is to copy the entire KSP installation to another place on your disk and run it from there (you don't need Steam to launch it).  That way you can remove MAS from the Steam installation, have it verify file integrity, and see if the Steam version works without MAS, and without finding files that need checked.

**Comment by DeputyLOL** [comment]
I found the solution. I got to run KSP 64bit for some reason. 
Sorry about this, my computer always fixes itself when I ask for help and I end up looking like an idiot.

**Comment by MOARdV** [comment]
> I found the solution. I got to run KSP 64bit for some reason. 

32 bit KSP barely has the memory to run un-modded.  Once you start adding mods, it hits its memory limitations very, very quickly.  And if you have high quality mods, or lots of plugins, it crashes yet more quickly.  You're pretty well forced to use the 64-bit version if you want to play modded.

**Comment by DeputyLOL** [comment]
Fair enough.
