### ISSUE TITLE
 Request. Max Temperature

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#120]
Please add these variables:
-  Maximum temperature for Pod (Skin and Internal) and for HeatShield.
-  Optional, Hottest Part current, maximum temperature and name

**Comment by MOARdV** [comment]
> Hottest Part current, maximum temperature and name

I assume this is the part closest to failure (this is how RPM reported hottest part).

**Comment by Alexustas** [comment]
Additional request.

Functions to track whether Pod, Engine and HeatShield is heating or cooling
`1` - heating, `-1` - cooling, `0` - no part

**Comment by Alexustas** [comment]
> Hottest part requires checking every part every FixedUpdate, which I am trying to avoid with MAS.

This is not so important feature (for me), it was just in RPM and so I included it in the request. Performance is much more important

**Comment by MOARdV** [comment]
Renamed `fc.HottestEngineTemperatureMax()` to `fc.HottestEngineMaxTemperature()` to be consistent with the new methods.  All other methods are named as in my previous (edited) comment.  Will update DropBox shortly.

**Comment by MOARdV** [comment]
DropBox is now updated.

**Comment by MOARdV** [comment]
Added:

* `fc.HottestPartTemperature(bool useKelvin)`
* `fc.HottestPartMaxTemperature(bool useKelvin)`
* and `fc.HottestPartSign()`

for v0.21.0
