### ISSUE TITLE
Request. Acceleration

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#121]
MAS Function similar to RPM,s ACCELFORWARD, ACCELRIGHT, ACCELTOP and EFFECTIVEACCEL 
And Vertical Acceleration and Horizontal Acceleration.

**Comment by MOARdV** [comment]
- [ ] fc.AccelForward()
- [ ] fc.AccelRight()
- [ ] fc.AccelTop()
- [ ] fc.Acceleration()
- [ ] fc.AccelUp()
- [ ] fc.AccelHorizontal()

I will rename `fc.Acceleration()` that is in MAS now to `fc.AccelEngines()`, since that is what it measures.  `fc.Acceleration()` will be total acceleration (EFFECTIVEACCEL in RPM).

**Comment by MOARdV** [comment]
Do we need the other accel variables (AccelPrograde, AccelRadial, AccelNormal, AccelSurfacePrograde)?  Or are vessel and surface values enough?

**Comment by Alexustas** [comment]
> AccelPrograde, AccelRadial, AccelNormal, AccelSurfacePrograde

I have not yet figured out how I can use it

**Comment by MOARdV** [comment]
> I have not yet figured out how I can use it

Okay.  I will add later if needed.

**Comment by Alexustas** [comment]
I will use fc.AccelForward(), fc.AccelRight() and fc.AccelTop()  for the dynamic overload display. fc.AccelUp() and fc.AccelHorizontal() for Landing Assistance and for Aircraft PFD

**Comment by MOARdV** [comment]
Acceleration methods now added on [DropBox](https://www.dropbox.com/s/tzctvykru1p6b49/AvionicsSystems-0.14.0b1.zip?dl=0).

**Comment by Alexustas** [comment]
Is there a chance to get the value of horizontal acceleration with a sign. negative if the speed decreases and positive if the speed increases?

**Comment by MOARdV** [comment]
> or maybe some other way to find out in which direction the horizontal velocity changes

Maybe acceleration compared to surface prograde?

**Comment by MOARdV** [comment]
Will it be more helpful to have a acceleration compared to surface prograde, or acceleration compared to surface forward (and surface right)?  We already have `fc.SurfaceForwardSpeed()` and `fc.SurfaceLateralSpeed()`, so I can add acceleration for both of them as well.

**Comment by Alexustas** [comment]
I'm not entirely sure for now, but I think that surface prograde is quite suitable
. 
In Real life, the modern flight control system displays on the PFD what speed, vertical speed and altitude the aircraft will have in 7 seconds (the time in different systems is slightly different). I want to implement something similar.

**Comment by MOARdV** [comment]
Updates now on [DropBox](https://www.dropbox.com/s/tzctvykru1p6b49/AvionicsSystems-0.14.0b1.zip?dl=0)
