### ISSUE TITLE
Request. Atmospheric flight

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#122]
MAS Function similar to RPM,s DRAG (kN), DRAGACCEL in m/s^2, LIFT (kN) and TERMINALVELOCITY

**Comment by theonegalen** [comment]
Seconded!

**Comment by MOARdV** [comment]
- [x] fc.TerminalVelocity()
- [ ] fc.Drag()
- [ ] fc.Lift()
- [ ] fc.DragAccel()

**Comment by MOARdV** [comment]
Implemented and available for beta on [DropBox](https://www.dropbox.com/s/tzctvykru1p6b49/AvionicsSystems-0.14.0b1.zip?dl=0).
