### ISSUE TITLE
VERTICAL_BAR node incorrect texture UV scaling

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#123]
video:
https://youtu.be/6dNE_F7yfno

it seems that the scaling is in the opposite direction. When the scale needs to be increased, it decreases and vice versa

I'm using this texture for Bar node. This texture has exactly the same size as the Bar

![vertbarv1_fill_r10_o30_g100](https://user-images.githubusercontent.com/6713671/37733593-61291d72-2d6a-11e8-980e-45811f6ae848.png)

config
```

// ABLATOR BAR(BAR) =====================================================================================
	
	VERTICAL_BAR
	{
		name = ABLATOR BAR
		position = 769,681
		size = 16,280
		source = fc.ResourcePercent("Ablator")
		sourceRange = 0,1
		sourceColor = 255,255,255,255
		texture = ASET/ASET_Props_MAS/ASET_MAS_MFD/Common_Images/VertBarV1_Fill_R10_O30_G100
		anchor = Bottom
		variable = fc.ResourceExists("Ablator") > 0
	}

```

I believe that it should work like this

![bandicam 2018-03-22 00-52-45-923](https://user-images.githubusercontent.com/6713671/37733923-79cae58a-2d6b-11e8-9968-6e4550923fd0.jpg)

**Comment by MOARdV** [comment]
All of the VERTICAL_BAR modes had errors.

**Comment by Alexustas** [comment]
Additional request. 
Can you make a sourceColor and borderColor as variable? 
for both Vertical and Horizontal Bars

**Comment by Alexustas** [comment]
I have a config:

```
VERTICAL_BAR
	{
		name = THRUST BAR
		position = 320,712 <- upper left corner of bar
		size = 16,280
		source = fc.CurrentThrust(true)
		sourceRange = 0,1
		sourceColor = 204,255,102,255
		anchor = Bottom
		variable = fc.EngineCountTotal() > 0
	}
```

the behavior of the BAR was normal - the larger value, longer BAR. after today's update, the behavior has reversed, larger the value - shorter BAR  

thrust - 0%

![bandicam 2018-03-25 23-30-05-176](https://user-images.githubusercontent.com/6713671/37878575-a609c1e0-3084-11e8-8114-eae27ee816bd.jpg)

thrust - 80%

![bandicam 2018-03-25 23-30-42-273](https://user-images.githubusercontent.com/6713671/37878576-afcd42f6-3084-11e8-860b-31869f68f8f9.jpg)

thrust - 100%

![bandicam 2018-03-25 23-30-17-410](https://user-images.githubusercontent.com/6713671/37878584-bcc1270c-3084-11e8-8adc-a1abb86b0d88.jpg)



is this a correct behavior and I need to fix all configs or is there some kind of error?

**Comment by MOARdV** [comment]
No, that is the opposite of what is supposed to happen.  I will check again.

**Comment by Alexustas** [comment]
Additional request 2.
Can you make a position of Bar variable?
for both Vertical and Horizontal Bars

**Comment by MOARdV** [comment]
- [ ] Variable sourceColor
- [ ] Variable borderColor
- [ ] Variable position (need to verify)

**Comment by MOARdV** [comment]
New update on [DropBox](https://www.dropbox.com/s/tzctvykru1p6b49/AvionicsSystems-0.14.0b1.zip?dl=0) - sourceColor, borderColor, position are variable for both HORIZ. and VERT. bars.
