### ISSUE TITLE
Request. Additional Landing Gear info

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#125]
GearMoving()
GearPosition()
GearCountTotal()

WheelStress()
WheelBroken (all or at least one)

**Comment by MOARdV** [comment]
- [ ] `fc.GearBroken()` - any landing gear broken.
- [ ] `fc.GearStress()` - highest stress on a landing gear that is not broken.
- [ ] `fc.GearMoving()` - any deployable landing gear is moving
- [ ] `fc.GearPosition()` - deployable landing gear retracted / deployed / moving
- [ ] `fc.GearCountTotal()` -- ??

Landing legs use the same module as wheels, so WheelStress and WheelBroken will be GearStress and GearBroken - choosing only wheels will be much more complex.

For Gear count total - is this deployable landing gear, or does it include fixed landing gear (such as airplane fixed landing gear)?

**Comment by Alexustas** [comment]
> choosing only wheels will be much more complex.

ok

>  is this deployable landing gear, or does it include fixed landing gear

All. 
But this makes sense, if only you can make a function "fc.GearBrokenCount()", which returns the number of broken gears. if not, then you can ignore this part of my request

**Comment by MOARdV** [comment]
> But this makes sense, if only you can make a function "fc.GearBrokenCount()", which returns the number of broken gears. if not, then you can ignore this part of my request

It is easy to count all broken gear.

**Comment by MOARdV** [comment]
Update on [DropBox](https://www.dropbox.com/s/tzctvykru1p6b49/AvionicsSystems-0.14.0b1.zip?dl=0) with functions listed above.
