### ISSUE TITLE
Request. Propellants 

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#127]
I suggest a some supplement to fc.Propillant functions:

- **fc.PropellantStageCount()** - Returns the total number of resources used as fuel for engines.
 _Eg If vessel has liquid fuel engine and solid busters, ` fc.PropellantStageCount()` returns 3._

_The list of propellants in this case will be: 
0 - LiquidFuel; 
1 - Oxidizer; 
2 - SolidFuel_

- **fc.PropellantStageName( id of propellant from propellants list)**  - Retrurns name of propellant resource form resources list. 
_Eg fc.PropellantStageName(1) returns `"Oxidizer`".  If such a propellant with a given Id is not found, then the function returns `empty string`_

- **fc.PropellantStageResourceId( id of propellant from propellants list )** - Returns resource Id from Stage Resources List.
 _Eg  fc.PropellantStageResourceId(1) returns `3`, since Oxidizer (propellant Id=1) has number `3` in the list of Vessel resources. if such a propellant with a given Id is not found, then the function returns `-1`_

- **fc.ResourceIsPropellant()** - return `1` if resource is used as propellant for current active engine, otherwise `0`

**Comment by MOARdV** [comment]
- [ ] `fc.PropellantStageCount()`
- [ ] `fc.PropellantStageName(index)`
- [ ] `fc.PropellantStageResourceId(index)`
- [ ] `fc.ResourceIsPropellant(resourceId)`

Where `index` is a number between 0 and `fc.PropellantStageCount()` - 1, and `resourceId` is the resourceId (number between 0 and `fc.ResourceCount()` - 1.

**Comment by MOARdV** [comment]
Implemented on [DropBox](https://www.dropbox.com/s/tzctvykru1p6b49/AvionicsSystems-0.14.0b1.zip?dl=0).
