### ISSUE TITLE
Request. Extra RCS control

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#128]
I am very interested in ability to switch the mode of operation of the RCS: 
**Full** (Rotation and Translation) and **Translation Only**. 

Is  that possible?

**Comment by MOARdV** [comment]
> Is that possible?

I can change all of these options, I believe:
![rcsopts](https://user-images.githubusercontent.com/6089493/37867154-4669a822-2f62-11e8-8997-e7286bc00967.png)

I can simplify and have `RcsTranslateEnable(bool)` and `RcsRotateEnable(bool)` to set all three axis at the same time.  The only problem is if the player disables some RCS ports in the VAB using those toggles, MAS will override the player.  Maybe that is okay?

**Comment by Alexustas** [comment]
> Maybe that is okay?

I believe so. it's ok
Let player himself decide what to use ))

**Comment by MOARdV** [comment]
- [x] fc.GetRCSRotate()
- [x] fc.GetRCSTranslate()
- [ ] fc.ToggleRCSRotate()
- [ ] fc.ToggleRCSTranslate()
- [ ] fc.SetRCSRotate(bool)
- [ ] fc.SetRCSTranslate(bool)

**Comment by MOARdV** [comment]
Done and on DropBox, same link as other recent updates.
