### ISSUE TITLE
Mapped Variables

### ISSUE THREAD

**Issue by DeputyLOL** [MOARdV/AvionicsSystems#13]
On the RPM issue you said that I could use this as a remap variable:

function Remap(value, bound1, bound2, map1, map2)
  value = math.max(bound1, math.min(bound2, value))
  local iLerp = (value - bound1) / (bound2-bound1)
  return map1 + iLerp * (map2 - map1)
end

I suspect that I don't know what I'm doing and I'm not using it right. My script is like this:

function Remap(value, bound1, bound2, map1, map2)
  value = math.max(bound1, math.min(bound2, value))
  local iLerp = (value - bound1) / (bound2-bound1)
  return map1 + iLerp * (map2 - map1)
end

function ACSkyPointerDisplace()
	if 65 < ACRollAngle() < 90 then
		-- Are we subjected to high gravity?  We might have some flicker
		-- Original design used RANDOM between 0.2 and 0.4, but since RANDOM is
		-- a uniform distribution, RANDOM > 0.8 has the same effect.
			return Remap(ACRollAngle(),65,90,0,1)
	if 90 < ACRollAngle() < 115 then
			return Remap(ACRollAngle(),90,65,1,0)
	else
			return 0
	end
end

What am I doing wrong?

**Comment by MOARdV** [comment]
> What am I doing wrong?

I suspect that Lua doesn't like 

`if 90 < ACRollAngle() < 115 then`

You most likely need to write that as

`if ACRollAngle() > 90 and ACRollAngle() < 115 then`

Otherwise, Lua will read that as 'is ACRollAngle() > 90', which is a boolean value, and then says 'is this boolean < 115'. which Lua won't accept, since the boolean is not a numeric and Lua doesn't implicitly convert booleans to numbers.

Or, you can write `if mas.Between(ACRollAngle(), 65, 90) > 0 then`

(`mas` is an undocumented library of methods I've been adding to do some common tests like that in Lua.  It returns 0 or 1 currently, although that may change to a simple boolean after I make some changes in MAS)

**Comment by DeputyLOL** [comment]
Have I used the 'Remap' function correctly?

**Comment by MOARdV** [comment]
`Remap(ACRollAngle(),65,90,0,1)` says "Take ACRollAngle, limit it to the range 65 to 90, and then convert that range from 0 to 1"  So, for angles <= 65, you'll get 0.  For angles >=90, you'll get 1.  Everything else will be linearly interpolated between those value.

If you're only interested in getting values between 0 and 1, you can simplify the function to something like 

```
function InverseLerp(value, bound1, bound2)
 value = math.max(bound1, math.min(bound2, value))
 return (value - bound1) / (bound2-bound1)
end
```

**Comment by DeputyLOL** [comment]
Nice. Sorry to be a nuisance but why is this wrong. 

function ACK320PFDGroundIndicator()
	local ACK320PFDGroundIndicatorRadarAltitude() = Remap(ACAltitudeTerrainFeet(),0,120,0,22)
	local ACK320PFDGroundIndicatorPitch() = Remap(fc.Pitch(),0,22,0,22)	
	return math.max(ACK320PFDGroundIndicatorPitch(),ACK320PFDGroundIndicatorRadarAltitude())
end

[ERR 18:14:55.500] [MASFlightComputer] MoonSharp.Interpreter.SyntaxErrorException: unexpected symbol near ')'

Also I've noticed that if there is an issue with one of the scripts. None of them will load and the rest of the variables will be unknown. Is this normal?

**Comment by MOARdV** [comment]
> Also I've noticed that if there is an issue with one of the scripts. None of them will load and the rest of the variables will be unknown. Is this normal?

Yes.  For now.  More robust error handling (and hopefully extracting more helpful messages from the MoonSharp Lua interpreter) are a future feature. :)

**Comment by DeputyLOL** [comment]
ahhh ok thank you

**Comment by MOARdV** [comment]
`fc.Remap()` is available now, so the slow Lua method doesn't need to be used.

**Comment by DeputyLOL** [comment]
Thank you
