### ISSUE TITLE
Request. Text node position

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#130]
Can you make a position of Text node variable?

**Comment by MOARdV** [comment]
I will check.  It may be difficult because the text drawing system is much more complicated.  That is why there are x and y nudges.

**Comment by MOARdV** [comment]
Answer is, yes, it is easy to make `position` variable.

**Comment by Alexustas** [comment]
> Answer is, yes

This is just great news!

**Comment by MOARdV** [comment]
And updated on [DropBox](https://www.dropbox.com/s/tzctvykru1p6b49/AvionicsSystems-0.14.0b1.zip?dl=0).
