### ISSUE TITLE
Solar Panel output data jerks

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#131]
video: https://youtu.be/fzh2dKCa2uQ

I see something like a short-term decline in the performance of solar panels. Is there any way to smooth out these jerks?

**Comment by MOARdV** [comment]
I will find out.  It may be a problem with the way KSP computes power production.

**Comment by Alexustas** [comment]
This is not a very big deal, in fact. This is more a matter of aesthetics. So, if it's hard to fix, then do not spend a lot of time on it

**Comment by MOARdV** [comment]
I did not see this happen with a non-tracking solar panel, but when I used two tracking solar panels, I see the power output change for one update at random times.  There does not appear to be a pattern to the behavior.  I believe this is a stock bug.  Any smoothing I apply will still show changes, or else it will cause a large delay before changes are visible in the variable, so I think it is better not to try to fix it.

**Comment by Alexustas** [comment]
Ок!
