### ISSUE TITLE
MASCamera additional fixes / improvements

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#133]
Copied from feedback in Issue #71 

> I have a very strange glitch with sky rendering
>
> video: https://youtu.be/Atetl3ZxIAc
>
> no mods, only MM, MAS and RPM
> Tell me what other information you need from me, I will provide everything you need
>
> FoV marker
>
> video: https://youtu.be/uO9Mxo9E9CM
>
> the marker is updated only when the part is placed
>
> Access to camera limits
>
> I could not find the function to get the data about the active camera limits

- [x] FoV marker in editor (I forgot to finish this)
- [x] Current camera limits (I forgot to finish this, also)
- [x] Multiple cameras in one part - only 1st camera modes work.
- [x] Add MASCameraMount, move model rotation to that code.
- [x] Add `fc.ActiveDockingPortCamera()` function to detect a camera on a reference docking port reference.
- [x] Add names to unnamed cameras (either "Dock #" or "Camera #")
- [x] Detect duplicate names and append numbers to them.

**Comment by MOARdV** [comment]
Okay, the sky glitch is very, very strange...  I hope I can find out what is happening.

**Comment by MOARdV** [comment]
I think I did not plan on one part with multiple cameras.  That is probably a bug.

**Comment by Alexustas** [comment]
ALCOR have five onboard cameras and I would like to make them different ))

**Comment by Alexustas** [comment]
and just thinking, again ))

 I started creating a set of new external cameras specifically for MAS and it so happened that the first thing I wanted to make was a camera in the MSL "Curiosity" style . But that's what I got. In fact, this is not one camera, but an assembly of several cameras in a single casing mounted on a motorized head. Each camera has its own properties: the "main" camera is a high quality color imager with powerful variable optics, the rest are "engineering" cameras for navigation and situation awareness with wide-angle fixed optics and black and white images.
But as I found out, this configuration does not work. The first problem is that I wrote above about camera modes on one part. the second is the inability to share the values of Pan and Tilt between the two cameras. When I select the first camera and pan and then switch to another camera, while I'm not doing the panning, everything is OK, but as soon as I do, the camera jumps to its own orientation and then pan.

**Comment by MOARdV** [comment]
I think I can make mechanical pan/tilt work with multiple cameras on the same part.

**Comment by Alexustas** [comment]
as I imagine the structure of the MASCamera module:

```
	MODULE
	{
		name = MASCamera

		CAMERA
		{
		cameraTransformName = HD_COLOR_Cam_Loc

		refreshRate = 1
		translation = 0, 0, 0
		rotation = 0, 0, 0

		cameraName = Hires Color

		fovRange = 8, 80
		fovRate = 20
		
		    MODE
		    {
		    name = Normal

		    cameraResolution = 1024
		    // shader = ""
		    // properties = ""
		    // texture = ""
		    }
		
		    MODE
		    {
		    name = High Gain

		    cameraResolution = 512
		    shader = MOARdV/Monochrome
		    property = _Gain:1.8  // ;_ChannelR:0.5
		    // texture = ""
		    }
                }

                CAMERA
                {
                cameraTransformName = Nav_Cam_Loc

                refreshRate = 2
		translation = 0, 0, 0
		rotation = 0, 0, 0

		cameraName = NavCam

		fovRange = 100,100
		fovRate = 0
				
		    MODE
		    {
		    name = High Gain

		    cameraResolution = 512
		    shader = MOARdV/Monochrome
		    property = _Gain:1.8 
		    // texture = ""
		    }
                }

		MOUNT (?)
		{

		panRange = -180, 180
		panRate = 10

		tiltRange = -90, 90
		tiltRate = 10
		
		panTransformName = PanAssembly_Loc
		tiltTransformName = TiltAssembly_Loc
		}
	}
```

**Comment by Alexustas** [comment]
and there is another important issue - the docking camera. I like the way it was implemented in the RPM, where the RPM itself adds the camera to the docking port and activates it when the dockport is selected as the reference part. Perhaps in the MAS you can add a tag, something like 
`camera = %ACTIVEDOCKPORTCAM%`
But the question remains who and how will assign the properties of this camera?

**Comment by Alexustas** [comment]
`Reference Transform is Pod, but there is a Docking Port with MASCamera: Select this camera?`

In my opinion, it's better to be a "missing camera", because this gives an additional memo to the player that he needs to assign a dockport

**Comment by MOARdV** [comment]
> and it would still be very convenient if the MAS will add a number to the end of the name of the cameras, which have the same names. since many players still can forget to give each camera an unique name

I agree

**Comment by MOARdV** [comment]
All new features and fixed on [DropBox](https://www.dropbox.com/s/lgffr6rtdf0cc6b/AvionicsSystems-0.14.0b2.zip?dl=0) - new link.  I still need to fix the camera sky glitch.

[MASCameraMount](https://github.com/MOARdV/AvionicsSystems/wiki/MASCamera#mascameramount) and [fc.ActiveDockingPortCamera()](https://github.com/MOARdV/AvionicsSystems/wiki/MASFlightComputerProxy#fcactivedockingportcamera)

**Comment by MOARdV** [comment]
The sky rendering glitch is strange.  If I launch a craft, the sky is black.  If I return to the space center and then go back to the craft, the sky draws correctly.

**Comment by MOARdV** [comment]
I have moved the atmosphere rendering bug to Issue #139.

**Comment by Alexustas** [comment]
If I use the camera mount, then I can not get the values of current Pan and Tilt. The MAS returns 0.

**Comment by MOARdV** [comment]
oops - I forgot to update those.  Fix on [DropBox](https://www.dropbox.com/s/lgffr6rtdf0cc6b/AvionicsSystems-0.14.0b2.zip?dl=0)

**Comment by Alexustas** [comment]
something very strange happens when I switch camera modes
I find it difficult to explain this in English, it's best to see this video
https://youtu.be/bR-qLaJhjjs


cam config

```
	// MAS Camera config =============================================================
	
	MODULE
	{
		name = MASCamera

		fovRange = 8, 80
		fovRate = 20
		
		panRange = 0, 0
		panRate = 10

		tiltRange = 0, 0
		tiltRate = 10

		cameraTransformName = HD_COLOR_Cam_Loc

		refreshRate = 1

		translation = 0, 0, 0
		rotation = 0, 0, 0

		cameraName = Hires Color
		
		// Normal mode (Hires Color)

		MODE
		{
		  name = Normal
		  cameraResolution = 1024
		  // shader = ""
		  // properties = ""
		  // texture = ""
		}
		
		MODE
		{
		  name = High Gain
		  cameraResolution = 512
		  shader = MOARdV/ColorNoise
		  properties = _Gain:1.5;_NoiseOffset:fc.RandomNormal(0, 0.135);_Blend:0.95 - fc.Random() * 0.10
		  texture = ASET/ASET_Props/MFDs/ScreenPlates/noise
		}
	}

	// Camera "Wide Angle Nav Cam"
	
	MODULE
	{
		name = MASCamera

		fovRange = 110, 110
		fovRate = 30

		panRange = 0, 0
		panRate = 10

		tiltRange = 0, 0
		tiltRate = 10

		cameraTransformName = NAV_Cam_Loc

		refreshRate = 2

		translation = 0, 0, 0
		rotation = 0, 0, 0

		cameraName = NavCam
			
		MODE
		{
		  name = HighGain
		  cameraResolution = 512
		  shader = MOARdV/Monochrome
		  properties = _Gain:1.6//;_ChannelR:0.5
		  // texture = ""
		}
	}
	
	MODULE
	{
		name = MASCameraMount

		panRange = -160, 160
		panRate = 20

		tiltRange = -90, 90
		tiltRate = 20

		panTransformName = PanAssembly_Loc
		tiltTransformName = TiltAssembly_Loc
	}
	
	// Animation  
	
	MODULE
	{
		name = MASDeployableCamera

		animationName = RetractCamAnim
		pivotName = RetractAssembly_Loc
		raycastTransformName = PanAssembly_Loc

		isBreakable = true
		//isTracking = false

		showStatus = true
		retractable = true

			// kPa * sin(AoA)
		windResistance = 2.5

		extendActionName = Deploy Camera
		retractActionName = Retract Camera
		extendpanelsActionName = Toggle Camera
	}
```

**Comment by MOARdV** [comment]
Easy bug to fix when I searched for it.  Fixed on [DropBox](https://www.dropbox.com/s/lgffr6rtdf0cc6b/AvionicsSystems-0.14.0b2.zip?dl=0).

**Comment by Alexustas** [comment]
I've never tested a camera in the night and that's what I saw.
it looks like skybox is very, very tiny, literally a few meters in size.

video
https://youtu.be/edL2dLdWvYk

**Comment by MOARdV** [comment]
Oh.  That looks like the skybox camera should not move.

**Comment by MOARdV** [comment]
Re-closing this - I mentioned the skybox bug in #139
