### ISSUE TITLE
MASCamera atmosphere / skybox bugs

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#139]
I'm moving this from Issue #133, since I believe this may be an issue with stock.  The atmosphere does not render correctly under some circumstances:

* Entering IVA the first time after launching a craft (although going to the Space Center and returning to Flight usually fixes it).
* When aiming a camera up (either tilting a horizontal camera to a high angle, or using a camera pointing up).

This issue was introduced in 1.4.x, but I don't know for sure if it was 1.4.0 or one of the updates (my dev environment is now 1.4.2, but I tested it in 1.4.1 as well before updating).  The same configuration worked in 1.3.1, so it appears to be a side-effect of the Unity update, or an internal KSP change.

I've posted a question on the [KSP Forum](https://forum.kerbalspaceprogram.com/index.php?/topic/173808-skybox-buggy-in-iva-cameras-ksp-14x-why/) about this issue.  Hopefully, someone will have a suggestion.

- [ ] Missing atmosphere on IVA after launch.
- [ ] Vessel can maneuver out of the skybox - skybox camera needs to be fixed?

**Comment by MOARdV** [comment]
Second issue reported by alexustas: skybox seems to fixed-position, and it disappears when the vessel moves.

**Comment by MOARdV** [comment]
It looks like sirkut reported the missing atmosphere problem on the forum back in February, so it's not just MAS that sees it.

**Comment by MOARdV** [comment]
sirkut on the KSP forum appears to have found the issue - MAS moves all of the cameras so that they stay attached to the vessel.  However, in DennyTX's DockingCam mod, the GalaxyCamera and Camera ScaledSpace do not move - they only rotate.  I tried that change locally, and it seems to fix both of the problems here.

alexustas - when you have time, can you verify the update on [DropBox](https://www.dropbox.com/s/lgffr6rtdf0cc6b/AvionicsSystems-0.14.0b2.zip?dl=0) fixes the bug?

**Comment by Alexustas** [comment]
>  fixes the bug?

YES! Now the day and night sky are rendered correctly!
THANK YOU!

I apologize for my silence recently, I changed my job. so I have a lot of caring besides ksp

**Comment by MOARdV** [comment]
That is okay.  Real Life is busy sometimes for me, as well.  Good luck with the new job.

Closing this bug as fixed (at last).
