### ISSUE TITLE
Ship Control through script.

### ISSUE THREAD

**Issue by DeputyLOL** [MOARdV/AvionicsSystems#14]
I remember you mentioning something about an autoland system that could be done in MAS.
Would it be possible to control pitch, roll and yaw through a script?

Would it also be possible to 'limit' player input though a script.

I'm working on an airbus and I'd like to have a crack at the control laws.
It limits bank angle to 67_, pitch to 15_ down and 30\* up and will try and prevent a stall by increasing engine power when speed is low.

**Comment by MOARdV** [comment]
I can probably relay control inputs (yaw / pitch / roll).  Limiting player input is something I am not keen on doing, since if there's a bug (either in MAS, or in the script that's controlling the craft), it may be unrecoverable without quitting the game.

**Comment by DeputyLOL** [comment]
There would be an off button...

**Comment by Alexustas** [comment]
I think in the case of the KSP, not very good to restrict control of the vessel. it may be better to warn of potential hazards and provide some instructions? Kind of "Pull AP!" "Accelerate!" ...
or "IT'S TOO LATE! JUMP OVERBOARD!"

**Comment by DeputyLOL** [comment]
> "IT'S TOO LATE! JUMP OVERBOARD!"
I'd love to hear that!

I guess your right. I was thinking of have the player 'control' the computer and the computer 'control' the ship but if its too risky then don't worry about it. 

Also quick question.
	TEXT
	{
		name = PFD overlay text
		textfile = AdvancedCockpit/K320/AC_K320_PFD_TEXT.txt
		font = JSI_baseFont
	}
This doesn't work, no text appears on screen. Any ideas?

**Comment by MOARdV** [comment]
> This doesn't work, no text appears on screen. Any ideas?

Off hand, no.  What's in AC_K320_PFD_TEXT.txt ?  What about the MASMonitor config?

**Comment by DeputyLOL** [comment]
PROP
{
	name = AC_K320_PFD_CAP

	MODEL
	{
		model = AdvancedCockpit/Shared/Displays/DisplayUnit/DisplayUnit
	}
	
	MODULE
	{
		name = MASMonitor
		
		screenTransform = ScreenObj // Transform for the monitor
		layer = _Emissive               // What layer to draw on
		screenSize = 640, 640           // Pixel dimensions (w, h)
		fontSize = 16, 32               // Fixed font dimensions
		font = InconsolataGo-Bold       // Default font
		textColor = 255, 255, 255, 255  // Default color of text
		backgroundColor = 0, 0, 16, 255 // Background color
		monitorID = Monitor%PROPID%     // What is the name of this prop's page variable?
		
		// Not implemented yet:
		//variable = fc.GetPowered()
		//range = 0.5, 1.1
		//disabledColor = 0,0,0,0

		page = AC_K320_PFD_CAP
	}
}

MAS_PAGE
{
	name = AC_K320_PFD_CAP
	HORIZON
	{
		name = Horizon
		texture = AdvancedCockpit/K320/Displays/Textures/PFD/PFD_ladder_basic
		position = -42,13
		size = 295,341
		pitch = fc.Pitch()
		pitchRange = -90, 90
		displayPitchRange = 2062,0
		roll = fc.Roll()
		rollRange = -180,180
		displayRollRange = -180,180
		variable = fc.GetBrakes() // For illustration purposes: HUD ladder works if brakes are off :-)
		range = -0.5, 0.5
	}
	HORIZON
	{
		name = HorizonSkyBorder
		texture = AdvancedCockpit/K320/Displays/Textures/PFD/PFD_HorizonSkyBorder
		position = -42,13
		size = 295,345
		pitch = ACSkyPointerDisplace()
		pitchRange = 0,0
		displayPitchRange = 172,172
		roll = fc.Roll()
		rollRange = -180,180
		displayRollRange = -180,180
		variable = fc.GetBrakes() // For illustration purposes: HUD ladder works if brakes are off :-)
		range = -0.5, 0.5
	}
	HORIZON
	{
		name = HorizonSkyPointer
		texture = AdvancedCockpit/K320/Displays/Textures/PFD/PFD_HorizonSkyPointer
		position = -42,13
		size = 345,345
		pitch = ACSkyPointerDisplace()
		pitchRange = 0,1
		displayPitchRange = 172,150
		roll = fc.Roll()
		rollRange = -180,180
		displayRollRange = -180,180
		variable = fc.GetBrakes() // For illustration purposes: HUD ladder works if brakes are off :-)
		range = -0.5, 0.5
	}
	HORIZON
	{
		name = HorizonGroundBorder
		texture = AdvancedCockpit/K320/Displays/Textures/PFD/PFD_HorizonGroundBorder
		position = -42,13
		size = 295,345
		pitch = ACK320PFDGroundIndicator() 
		pitchRange = 22,0
		displayPitchRange = 172,300
		roll = fc.Roll()
		rollRange = -180,180
		displayRollRange = -180,180
		variable = fc.GetBrakes() // For illustration purposes: HUD ladder works if brakes are off :-)
		range = -0.5, 0.5
	}
	HORIZONTAL_STRIP
	{
		name = Heading
		texture = AdvancedCockpit/K320/Displays/Textures/PFD_HEADING
		position = 125,556
		size = 304,40
		input = fc.Heading()
		inputRange = 0, 360
		displayWidth = 320
		displayRange = 0,2048
		wrap = true
	}
	TEXT
	{
		name = PFD overlay text
		textfile = AdvancedCockpit/K320/AC_K320_PFD_TEXT.txt
		font = JSI_baseFont
	}
	IMAGE
	{
		name = PFD overlay
		texture = AdvancedCockpit/K320/Displays/Textures/PFD/PFD_OVERLAY
		size = 640, 640
	}
	VERTICAL_STRIP
	{
		name = AirSpeedBar
		texture = AdvancedCockpit/K320/Displays/Textures/PFD/Airspeed/PFD_AIRSPEED
		position = 10,62
		size = 64,364
		input = ACAirspeedKnots()
		inputRange = 0, 500
		displayHeight = 930
		displayRange = 4002,151
		variable = fc.GetRCS() // For illustration purposes
		range = -0.5, 0.5
		wrap = false
	}
	VERTICAL_STRIP
	{
		name = StallBar
		texture = AdvancedCockpit/K320/Displays/Textures/PFD/Airspeed/PFD_STALLBAR
		position = 74,62
		size = 12,364
		input = 0 // StallSpeed()
		inputRange = -60, 60
		displayHeight = 455
		displayRange = 682,227
		variable = ACRollAngle() // For illustration purposes
		range = 60, 120
		wrap = false
	}
}

**Comment by DeputyLOL** [comment]
This is the page:
{0,1:0} $&$ fc.Roll()
{0,1:0} $&$ ACRollAngle()
{0,1:0} $&$ ACSkyPointerDisplace()

**Comment by MOARdV** [comment]
Try moving it to the bottom of the list - the objects are rendered such that the first item listed is the "bottom", and anything higher will block those results (in other words, the PFD overlay may be hiding the text).

**Comment by DeputyLOL** [comment]
Didn't work...

**Comment by DeputyLOL** [comment]
Is there anything wrong with this:

function ACK320PFDCheckAtt()
	if fc.pitch() > 85 and fc.Period(1) == 1 then 
		return 1
	else
		return 0
	end
end

**Comment by MOARdV** [comment]
> if fc.**P**itch() > 85 and fc.Period(1) == 1 then 

(All built-in functions use CamelCase, so the first character should be capitalized)

**Comment by DeputyLOL** [comment]
ahh ok. I ask this because there were no errors in the log but none of the variables worked.
Thank you.
What about the text page, I moved it to the bottom and it didn't work.

**Comment by DeputyLOL** [comment]
Changing it to Pitch also didn't work.

**Comment by MOARdV** [comment]
> Changing it to Pitch also didn't work.

Weird.  Another thing you could do is simplify it to

```
if fc.Pitch() > 85 then
  return fc.Period(1)
else
  return 0
end
```
Since fc.Period returns either 0 or 1 already.  As for the page - I'd have to get the files and try it locally.  Or can you put the log somewhere?  Maybe there's a clue that I need to make jump out more.

**Comment by DeputyLOL** [comment]
Thank you. It works now

**Comment by MOARdV** [comment]
Hmm.  I wonder if Period isn't in the dev build you have...  I need to get you and update.

**Comment by DeputyLOL** [comment]
A little but probably impossible idea. Could we get variable text that can be moved like a 'horizon'?

**Comment by DeputyLOL** [comment]
Had to fix the dev build you gave me but now Period works. Thank you.
