### ISSUE TITLE
Question: Action Group strings

### ISSUE THREAD

**Issue by theonegalen** [MOARdV/AvionicsSystems#147]
Does MAS have support for the action group label strings like RPM did?

AG1 = FLAPS, etc in the KSP .craft file?

How about the storedStrings from the RasterPropMonitorComputer? I didn't see anything like that in MASFlightComputer.

**Comment by MOARdV** [comment]
I have not incorporated the action group label strings yet.  I didn't like how they had to be implemented for RPM - essentially, RPM would repeatedly check the contents of the vessel description while in the editor, and whenever the text changed, RPM would copy the description (so, potentially every time you add or remove even a single letter in the description, RPM would copy it).

I was hoping I could find a way to fetch the vessel description without a hack like that, but I haven't found one yet, so I may end up doing it that way after all.

**Comment by MOARdV** [comment]
Oh - with respect to storedStrings, MAS generalizes that to some extent with [PERSISTENT_VARIABLES](https://github.com/MOARdV/AvionicsSystems/wiki/MASFlightComputer#persistent_variables) in the MASFlightComputer configuration.  The example on that page is a number, but there's nothing preventing you from doing
```
PERSISTENT_VARIABLES
{
  StoredString0 = My Stored String
}
```

and then accessing it with `fc.GetPersistent("StoredString0")`.

**Comment by MOARdV** [comment]
...and done.  ([see](https://github.com/MOARdV/AvionicsSystems/wiki/MASFlightComputerProxy#fcactiongroupactivememodouble-groupid)).  The 0.15.0 beta will be updated in a little while, once I get one other minor thing added.
