### ISSUE TITLE
add 'startupScript' to MASComponent

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#148]
MASMonitor has it.  It makes sense to add it to MASComponent as well.

**Comment by MOARdV** [comment]
Done, and supported by Prop Config

**Comment by theonegalen** [comment]
Documentation is a little unclear on this. The start up script happens on vessel load? ("While MAS configures the prop")

Is there something I can do to simulate the CRT starting up when first turned on; a big flash then the image fading in slowly?
