### ISSUE TITLE
MAS Alarm Clock?

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#150]
This is just an idea right now.  Since I am already thinking of making a simple MechJeb autopilot, and I already have written a simple MechJeb Maneuver Planner ... should I write a simple Kerbal Alarm Clock?

It would not be as complete and fancy as KAC.  Instead of alarms for all vessels, and multiple alarms per vessel, only worry about the next Sphere of Influence change, next Maneuver Node, and next user-defined alarm.

I would have to think about how it would interact with Kerbal Alarm Clock (does MAC create KAC alarms?  If KAC is installed, does it inspect the KAC alarm list?  Or does it ignore KAC?).

**Comment by theonegalen** [comment]
It seems to me that it would probably be annoying to have alarms from both MAC and KAC when approaching a flight event. I feel that optional integration with KAC (setting and reading alarms) would be best from a user standpoint, but I understand that probably adds a lot of complexity on the coding side.

**Comment by MOARdV** [comment]
I would want to keep KAC awareness.  There's already a limited KAC interface in MAS, so coordinating with KAC when it's present should not be an issue.

**Comment by MOARdV** [comment]
Upon further review, I think I'll punt on this one.  I have plenty of other things to work through for MAS, and there are ways to write an alarm clock system using scripting if it's really a feature that's needed.
