### ISSUE TITLE
MAS Props not animating while in CameraView (Not KerbalView)

### ISSUE THREAD

**Issue by gthaatar** [MOARdV/AvionicsSystems#152]
I'm running into an issue where I've switched from a Kerbal seat's camera to a separate camera (utilizing the internal camera switch module), and the MAS props in my view will not animate.  My clicks will register, and the functions of the props work as intended, but I'm not getting any of the animations. 

I can verify this by switching in and out of the view (and the props update), and by comparing them to the RPM props I also have present, which work normally.

I swear I've seen this issue before somewhere, or even had it myself and figured out how to fix it, however I can't remember and I can't find anywhere that triggers a solution for me. # #

**Comment by gthaatar** [comment]
I can provide my own IVA. Currently uses a mix of RPM and MAS Props, but it should work fine for testing purposes. Give me a bit and I'll upload a release that has the updated transforms and what not.

**Comment by gthaatar** [comment]
https://github.com/gthaatar/UltimateShuttleIVA-FullRetro

v0.03.

**Comment by MOARdV** [comment]
Okay.  I've fixed the problem.  There will be an official MAS release soon with the fix.
