### ISSUE TITLE
kOS support?

### ISSUE THREAD

**Issue by mathuin** [MOARdV/AvionicsSystems#153]
I noticed in a closed issue that the maintainer doesn't use kOS so isn't interested in supporting it at the moment.  When I play KSP I'm a heavy kOS user, and would switch to MAS immediately if I could use kOS from IVA.

I will hopefully have some time this summer for KSP again, and would be interested in working on a kOS interface for MAS, if it had a chance of getting committed to the master branch.

**Comment by mathuin** [comment]
My initial vision is similar to kOS Prop Monitor, but simpler.  I would keep the terminal window, keyboard activity indicator, and processor number and add the processor tag if set.  No need for labeled buttons or anything like that.

I can't say more without actually using your mod, which I will do as soon as I can. :-)

**Comment by MOARdV** [comment]
The IVA included in MAS (for the MRK-DM from Commonwealth Rocketry) is a introduction to what the mod can do.  If you look at what alexustas does on [YouTube](https://www.youtube.com/channel/UC58DKB3YguDiVcUh4bmef5w), you can see some of the capabilities of the mod.

**Comment by MOARdV** [comment]
I'm going to close this issue, since I suspect the kOS bridge is best implemented as a DLL that hard-links to both kOS and MAS, and that is outside the scope of what I'm going to do.  I'm willing to provide some suggestions on how to set up the bridge when you're ready to look into it.
