### ISSUE TITLE
MechJeb - Roll Controls

### ISSUE THREAD

**Issue by gthaatar** [MOARdV/AvionicsSystems#154]
Somethign rather important I think is missing from the MechJeb functionality (or at least appears to be missing, I couldn't find any documentation on it) is the ability to control the "Force Roll" functions of the various modules. On/off, force roll #, etc. This is especially important for the the launch autopilot, as setting a specific roll angle is good to combine with inclined launches.

**Comment by MOARdV** [comment]
I will need to look into the roll control.  It's been a while, but I think Mech Jeb separates roll control during launch from roll control during other phases (such as when using SASS), so I may have to add a Launch Roll Control and an in-flight Roll Control.

**Comment by MOARdV** [comment]
Available on the [DropBox](https://www.dropbox.com/s/9cc0g2hyage21cg/AvionicsSystems-0.15.0b1.zip?dl=0) beta.
