### ISSUE TITLE
fc.HottestEngineTemperature - Broken function or broken install?

### ISSUE THREAD

**Issue by gthaatar** [MOARdV/AvionicsSystems#156]
[ERR 23:53:28.949] [MASFlightComputer] MASFlightComputer.FixedUpdate exception: System.ArgumentException: Unexpected variable type Unknown for variable (fc.Remap)((fc.HottestEngineTemperature)(false), 0, (fc.HottestEngineTemperatureMax)(false), (-1), 252) in mutableVariablesList
  at AvionicsSystems.MASFlightComputer.FixedUpdate () [0x00000] in <filename unknown>:0 

This could very well be my install being borked somewhere, but I'm getting this flag with the MFD's since the new update.

**Comment by MOARdV** [comment]
Most likely a side-effect of the changes I made yesterday.  I'll look into it this morning and see if I can get a fix out.

**Comment by MOARdV** [comment]
Actually, the problem is fc.HottestEngineTemperatureMax(false) - that should be fc.HottestEngine**Max**Temperature(false).  I'll see if I can make those messages a little more prominent in the log so they're easier to find.
