### ISSUE TITLE
Reference implementation required

### ISSUE THREAD

**Issue by mathuin** [MOARdV/AvionicsSystems#165]
I completely understand the arguments set forth in the wiki for not providing IVAs for MAS.

That being said, there is an absolute need for a reference implementation, something which MAS can be tested against, something which MAS users and developers and mod folks can use to demonstrate functionality.  

I recommend the Mk1 Command Pod as the target for the reference implementation.  One instance of each kind of terminal is enough.  The idea being that mod folks can *depend* on that implementation being 100% functional for testing while potential users can quickly find out what all the fuss is about.

Yes, maintaining it will be a drag.  But it will also allow for some quick validation by sandbox players to determine that changes to the mod have not broken the reference implementation, which will allow others to trust the mod going forward.

Just my opinion, but a strong one.  :smile:

**Comment by MOARdV** [comment]
For all intents and purposes, the MRK DM is the reference implementation.  I don't use the Mk1 Command Pod (or any other stock pods), so I don't have much interest in sinking time into developing it into a MAS IVA.

The MFD terminals are insufficient to test MAS - there's far more to the mod than the glass cockpit features.  One could develop an MFD configuration that could be extensively test MAS, but that also entails a lot of time that I don't have.
