### ISSUE TITLE
Add SUB_PAGE node to MASMonitor

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#180]
One issue with complex MFD design is that there are times where the same components are used on multiple pages, which means editing each page if something in one of those components changes.

Maybe I should add an 'include = ' statement in the page config (similar to 'softkey ='), and add a MAS_SUBPAGE node that can be used to contain multiple nodes ('TEXT', etc).  At load time, the nodes in the sub pages listed in the  'include =' are appended to the page's existing nodes (or should they be prepended? or should both be allowed using 'includebefore' and 'includeafter'?).

**Comment by Alexustas** [comment]
Oh! you literally read my thoughts! I have long been thinking about such a request.
I thought about what it should be another node that is inserted in the order of its appearance in the config page, like all other nodes

```
MAS_PAGE
{
	name = some really complicated page

node#1
node#2
node#3
  >> SUB_PAGE node#1
node#4
node#5
  >> SUB_PAGE node#2
node#6
node#7
node#8

}
```

**Comment by MOARdV** [comment]
I think
```
MAS_PAGE
{

  node#1
  SUB_PAGE
  {
     name = my sub page //MAS_SUBPAGE name
  }
}
```
and
```
MAS_SUBPAGE
{
  name = my sub page
  nodes
}
```

will be easier than what I was thinking, actually.  You can control exact placement of the nodes that way.

**Comment by Alexustas** [comment]
and one more addition. can you add a "position" field for the sub_page. that we had the ability to adjust the position of the entire sub-page on the page?

**Comment by Alexustas** [comment]
and a variable to control the visibility of sub-page, as for all other nodes

**Comment by MOARdV** [comment]
> and one more addition. can you add a "position" field for the sub_page. that we had the ability to adjust the position of the entire sub-page on the page?

I was afraid you would ask this. :)  It may be very difficult, because text position is not the same as other positions.  I will try to make it work.

> and a variable to control the visibility of sub-page, as for all other nodes

This variable would have to replace the visibility variable for all nodes of the sub page.  It will not be possible for nodes in a sub page to have different visibility than other nodes in the same sub page.

**Comment by Alexustas** [comment]
> I was afraid you would ask this. :) It may be very difficult, 

this is strictly optional, if it is difficult, you can completely ignore these additions.

even the basic implementation of the feature is already **very** useful. I can not wait when I can use the features of sub_pages, it will make my life much, much easier

**Comment by MOARdV** [comment]
Actually, it was not as difficult as I thought.  I had time during lunch to write it.  Both 'position' and 'variable' are options for sub_page, and the nodes in the sub_page can also have 'position' and 'variable':
```
MAS_SUB_PAGE
{
  name = flashing text
  TEXT
  {
    name = some name
    text = FLASH
    variable = fc.PeriodStep(2)
    position = 1, 1
  }
}
MAS_PAGE
{
  ...
  SUB_PAGE
  {
    name = flashing text
    variable = fc.GetGear()
    position = 16, 32
  }
}
```
will combine to create
```
TEXT
{
    name = some name
    text = FLASH
    variable = (fc.GetGear() and (fc.PeriodStep(2))
    position = 0.0625 * (16) + (1), 0.03125 * (32) + (1) // same as 2, 2
}
```

**Comment by MOARdV** [comment]
On [DropBox](https://www.dropbox.com/s/brsybmunm9hay12/AvionicsSystems-0.20.0b1.zip?dl=0).
