### ISSUE TITLE
Remove 'range' from prop configs

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#181]
'range' is mostly a left-over from RasterPropMonitor, when there was no way to express valid ranges of values.  However, with MAS, I think it is not needed any longer:

* For "boolean" mode, there is already `fc.Between(value, range1, range2)` that accomplishes the same task.
* For "blend" mode, I will need to add `fc.InverseLerp(value, range1, range2)` that will blend from 0 to 1 (we could also use `fc.Remap(value, range1, range2, 0, 1)`, but it makes sense to have InverseLerp).  This mode will still use the `blend = true` config option.

This will be a huge nuisance to update the prop configs. But it is better to do before too many other people create MAS props.  Hopefully, the PropConfig tool will help update configs.

But it simplifies a small part of the code - right now, every single prop node in both MASComponent and MASMonitor pages has to keep two variable references in case range mode is selected, and MAS has to take a couple of extra steps processing the value.  Removing these extra variable references also will make Issue #179 more useful, since there isn't a way to subscribe or unsubscribe from Variables used for `range`.

**Comment by MOARdV** [comment]
Easy to remove for MASPage nodes (for me, at least) since I wasn't using it.

**Comment by Alexustas** [comment]
> But it is better to do before too many other people create MAS props.

I still have not done a single prop, not counting one MFD and FMS, so I do not see any difficulties for me ))

on the other hand, I very much welcome any changes that can improve performance

**Comment by MOARdV** [comment]
If you have some time, I worked on a PFD that can be reconfigured - take a look at the "FLIGHT" page on MAS_ALCOR_MFD2 prop (left-right arrows and up-down arrows to change configuration).  I also made the kOS Terminal work, but I need to update GitHub with the new version.
