### ISSUE TITLE
Request: function reporting on pressing keys related to throttle control

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#188]
I create a new throttle control lever using the new "drag" feature and I need to track when the user changes the throttle without clicking on the lever, but with the keyboard (pressing `Full Throttle`, `Throttle Cut-Off`, `Throttle Up` and `Throttle Down`)

**Comment by Alexustas** [comment]
I do not think I need to know the exact button.
In this particular case, I need to know that the user has changed the throttle value using the key, not prop. So I can synchronize the position of the lever with the current gas value, only when it is needed and do not create an extra load on the performance

**Comment by MOARdV** [comment]
`fc.GetThrottleKeyPressed()` on [DropBox](https://www.dropbox.com/s/sapygr4c1a4j8f7/AvionicsSystems-0.21.1b1.zip?dl=0).  Returns 1 if any throttle key is pressed on the keyboard, 0 if no key is pressed.
