### ISSUE TITLE
Import JSISetInternalCameraFOV?

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#189]
Used to control the FoV of the IVA camera, with pan and pitch limits, and the ability to hide parts of the Kerbal mesh.

**Comment by MOARdV** [comment]
I think I will simplify this for now - instead of modifying the INTERNAL config with a per-Kerbal set of overrides, I'll have a single setting in MASFlightComputer to control max pan, and min/max pitch.

The show/hide mesh component can get buggy if there are multiple MAS IVAs installed (I'm somewhat surprised it didn't cause problems in RPM).

**Comment by theonegalen** [comment]
So how does this work? The wiki says this is possible in MASFlightComputer, but there are no instructions on how to set the pitch and pan.
