### ISSUE TITLE
Part Groups and Variables

### ISSUE THREAD

**Issue by DeputyLOL** [MOARdV/AvionicsSystems#19]
I asked about this in RPM but it was too difficult to do.
A feature that I would REALLY love to see in MAS is the ability to get readings from individual engines, fuel tanks, landing gear, etc...

The original idea was to set each prop with an ID like the cameras.
Problem is that what if two crafts with props that are the same ID dock together?

Instead of setting each prop its individual ID, assign them to a group that can contain multiple parts.
The variables of the groups should be averages of all the parts in the group. (eg. engine thrust, gear position, fuel...)
When 2 ships that have part groups dock, the parts from both ships go into the same group.

**Comment by MOARdV** [comment]
One way to deal with the dock issue would be to decree that a command pod can only interact with parts that came from the same vessel at launch time - I actually do that with the docking ports.  It could be a problem for someone assembling a big ship in orbit by docking components, but I don't know how many people would want to fly mostly IVA if they're doing something like that.

It's still a topic I need to think through, so it'll need to wait until I've got some time to really work it out.

**Comment by MOARdV** [comment]
I don't think I'm going to do part groups - that adds too much complication.  However, I think I've finally come up with a mechanism that will work satisfactorily.

**Comment by theonegalen** [comment]
Oh heck, that's exciting.

**Comment by MOARdV** [comment]
Basic infrastructure is in place.  Specific features will be separate issues (such as Issue #56 ).
