### ISSUE TITLE
Assorted requests / issues

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#198]
From Dragon01 correspondence at the forum, plus other feedback:

- [x] fc.RadarActive() doesn't seem to actually return 0 if the radars are turned off. 
- [x] Functions from the "body" category don't actually seem to work. For example, fc.BodyRotationPeriod(fc.BodyTargetIndex()) returns zero no matter which body is actually selected.
- [x] Would that be possible to add a function to target the next docking port on the ship?﻿ RPM had a menu for that, but MAS is lacking in terms of targeting individual ports (there's radar, but it's rather troublesome to use when you've got a MIR-style node).
- [x] MAS could use a function which returns 1 when docking ports are aligned in roll and 0 otherwise. Stock docking port module supports specifying multiple orientations at which the ports will lock together. Both orientations and limits can vary between port types, making it impossible to account for in MFD config. If MAS could access those values (when they're present), it would make a great docking aid.
- [x] Add 'Set' functions to the existing 'Toggle' functions - to allow separate buttons to control functionality (eg, `SetRadiators(true)` or `SetRadiators(false)`).
- [x] Additional functionality for the engine group features (thrust, thrust limit, fuel use).
- [x] Vertical G's.
- [x] Heading rate smoothing.
- [x] Set / Get Trim
- [x] Open / Close intakes (set / toggle automatic mode?)
- [x] Individual gimbal axis control.
- [x] Check Toggle return values (should always return 1 on success).
- [x] Brake force adjustment.
- [x] Check Thrust when engines are cut - doesn't go to zero?
- [x] Toggle Engines that aren't on the current stage for grouped engines.
- [x] Report Gimbal Deflection in a given direction.
- [x] Animation position for landing gear, payload bay (if accessible).
- [x] Navball reference frame (isn't that done already?)
- [x] EVA button
- [x] Globus lat/lon gauge speed
- [x] Master Caution / Master Alarm: a voting system using TRIGGER_EVENT to vote for alarm / caution?  The caution / alarm lamp triggers when the relevant persistent > 0?
- [x] Tri-state fc.Select (-/0/+)
- [x] [LF / O / Monoprop](https://forum.kerbalspaceprogram.com/index.php?/topic/160856-wip-16x-moardvs-avionics-systems-mas-interactive-iva-v0921-5-january-2019/&page=11&tab=comments#comment-3518049) digital readouts.
- [x] Per Resource locking / unlocking.
- [x] Way to request more / less power consumption from the flight computer (emulate activating / deactivating a subsystem).

**Comment by theonegalen** [comment]
Aw yeah!
