### ISSUE TITLE
MASPageLineRenderer Unity update

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#2]
The Unity LineRenderer class online advertises a SetPositions(Vector3[]) method, but KSP's current flavor of Unity doesn't include that method, so I've got a loop over the variables instead.  When KSP 1.2 comes out, see if the updated Unity edition takes care of that problem.

**Comment by Alexustas** [comment]
I was going to create a request about adding the possibility of drawing lines on the MFD screen . This issue somehow related to my request?

**Comment by MOARdV** [comment]
This is a different issue, but I can add a line drawing capability, too.  Do you want lines that can move, or fixed lines?
