### ISSUE TITLE
More robust failure for proxy objects

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#203]
The FAR 1.4.5 unofficial release is causing failures in proxy configuration.  Can I do something to make the failure less drastic than this:

```
[ERR 19:48:33.444] [MASFlightComputer] Proxy object configuration failed:

[ERR 19:48:33.444] [MASFlightComputer] System.TypeInitializationException: An exception was thrown by the type initializer for AvionicsSystems.MASIFAR ---> System.ArgumentException: method return type is incompatible
  at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, Boolean throwOnBindFailure) [0x00000] in <filename unknown>:0 
  at System.Delegate.CreateDelegate (System.Type type, System.Reflection.MethodInfo method, Boolean throwOnBindFailure) [0x00000] in <filename unknown>:0 
  at System.Delegate.CreateDelegate (System.Type type, System.Reflection.MethodInfo method) [0x00000] in <filename unknown>:0 
  at AvionicsSystems.MASIFAR..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at AvionicsSystems.MASFlightComputer.Start () [0x00000] in <filename unknown>:0 

[ERR 19:48:33.444] [AvionicsSystems] INITIALIZATION ERROR: Initialization Failed.  Please check KSP.log

[EXC 19:48:33.532] NullReferenceException: Object reference not set to an instance of an object
	AvionicsSystems.MASFlightComputer.Start ()```

**Comment by theonegalen** [comment]
Is it still safe for the career save I just started to leave it installed? I haven't experienced any crashes, but there's been a few weird behaviors. Not sure they are related though.

**Comment by MOARdV** [comment]
So far, all I've heard about is a problem with the unofficial FAR 1.4.5.  If you've got that version of FAR installed, MAS is going to be flaky - I'd have to go dig through the code to remind myself what other components of MAS are going to be affected by that exception firing.

**Comment by MOARdV** [comment]
Update - instead of doing something more robust, I'm going to shut off FAR support until an official release comes out.  I don't want to have to chase down unofficial edits to the mod that may behave differently than other unofficial edits, or are incompatible with the official release.

**Comment by theonegalen** [comment]
It looks like ferram4 may have left KSP altogether. Unofficial releases may be all we have now.

**Comment by MOARdV** [comment]
> It looks like ferram4 may have left KSP altogether. Unofficial releases may be all we have now.

That's a possibility.  Last time I checked, he was still visiting the forum, just not posting.  However, until or unless someone steps up to take official ownership of the DLL, I don't want to spend time chasing potential inconsistencies in different unofficial DLLs.  My free time has become too limited as it is, and I'd like to spend more of it playing KSP than modding it (which I haven't managed to do since KSP 1.4.0 released, alas).

**Comment by theonegalen** [comment]
I understand that, believe me.
