### ISSUE TITLE
Stage propellant is rendered zero

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#208]
The propellant gauge stays at zero IF the engine is activated through the action group (by clicking at the toggle) and not through staging.

**Comment by MOARdV** [comment]
This is a problem with the way staged engines and active engines are reported.  It is possible to activate an engine before it is activated by staging, and MAS doesn't recognize those engines.

**Comment by JonnyOThan** [comment]
Even in cases when I don’t use action groups, sometimes even the stock game’s stage resources window shows zero after a scene switch.  KOS reports the same values.  So I don’t think this is necessarily an issue with MAS, if it’s just fetching the same values that stock is.

**Comment by snakeru** [comment]
@MOARdV do you think it is feasible to detect if
* the engine(s) that is/are being activated is/are not staged
AND
* the next stage contains only this engine(s) and nothing else
... and if so - trigger the stage instead?

**Comment by MOARdV** [comment]
There could be side-effects from staging, and I'd prefer not having MAS do something other than what was specifically requested in a case like this.

KSP staging is somewhat messed up in general - if you dock two vessels, when you undock them, the active stage is often set to one higher than the stage that was previously active (for instance, if your vessel is on stage 2 when you dock, KSP sets it to stage 3 after undocking).
