### ISSUE TITLE
fc.TerrainAltitudeVerticalSpeed ?

### ISSUE THREAD

**Issue by DeputyLOL** [MOARdV/AvionicsSystems#21]
Dunno if it would be that but please can we have the RADARALTVERTSPEED from RPM in MAS?
I want to start working on a GPWS system and this variable is very important.

**Comment by MOARdV** [comment]
I haven't gotten to it yet. :)

**Comment by MOARdV** [comment]
It'll be `fc.AltitudeTerrainRate()` in the next update.

**Comment by DeputyLOL** [comment]
Thank you

**Comment by MOARdV** [comment]
... And, it's available now, along with the rest of the FAR variables from RPM (except Lift Force and Drag Force).

**Comment by DeputyLOL** [comment]
Thank you again.
I still dont seem to have any text on my monitors? Have you got any ideas why?

**Comment by MOARdV** [comment]
> I still dont seem to have any text on my monitors? Have you got any ideas why?

No idea.  Do you still have the Yarbrough IVA that I included in the original dev build?  It has some LED-style numeric displays that use text,  Can you see those?

**Comment by DeputyLOL** [comment]
I think i found the problem.
The text appears behind the overlay regardless of where it is positioned in the page config.
CONFIG:
	IMAGE
	{
		name = PFD overlay
		texture = AdvancedCockpit/K320/Displays/Textures/PFD/PFD_OVERLAY
		size = 640, 640
	}
	TEXT
	{
		name = PFD text
		textfile = AdvancedCockpit/K320/Displays/AC_K320_PFD_TEXT.txt
		font = JSI_baseFont
	}
RESULT:
![screenshot7](https://cloud.githubusercontent.com/assets/12616126/18224266/9c0f5178-71c7-11e6-9639-8f9e5738d79b.png)

**Comment by MOARdV** [comment]
Okay, that is really strange.  I will have to find out what's going on - I'm about ready to start looking at monitors again, so that should be addressed "soon"
