### ISSUE TITLE
MoonSharp isn't in the git repo anywhere

### ISSUE THREAD

**Issue by JonnyOThan** [MOARdV/AvionicsSystems#211]
Minor thing, but if I clone or fork this repro I have to figure out where MoonSharp comes from.  It seems to be masked out in your .gitignore file?  Do you normally build MoonSharp from source?

**Comment by JonnyOThan** [comment]
Along the same lines, I don't get any of the labels on the props in my locally-built MAS, because the assetbundles are excluded from the GameData folder and it can't load the fonts.  Copying the files from the release build seems to work.

**Comment by MOARdV** [comment]
I think I've got the repo reorganized for building asset bundles, and the documentation in BuildingMAS.md should be sufficient for someone else to build MAS.
