### ISSUE TITLE
Using the Recovery prop can soft lock the game

### ISSUE THREAD

**Issue by JonnyOThan** [MOARdV/AvionicsSystems#214]
Sometimes when using the recovery prop, the game will start behaving strangely.  For example, the "leave" button in the R&D building will stop working, which essentially softlocks the game.  This doesn't happen on simple missions, but it happens fairly often after I've returned from a complicated mission.  I took a quicksave just before recovering, and this repros 100% of the time when using the recover prop, and 0% of the time when using the normal recover button in the UI.

Using the click event of the UI button seems to fix this issue.  I'll have a pull request shortly.

**Comment by JonnyOThan** [comment]
I’ve been doing some more digging on this and I’m pretty sure that it’s due to some weird interactions with other mods - specifically ProbeControlRoom.  I’ve locally modified PCR to enable it to work even when the vessel has crew.  If I have ever activated PCR before clicking the recovery prop, the bug occurs. If I haven’t, it doesn’t.  The recovery prop is just strange because it’s the only way you can recover your ship while in IVA.

**Comment by JonnyOThan** [comment]
Yep, that’s understandable.  I think making small accommodations for interplay between mods is worthwhile, because when all this stuff works together it’s pretty incredible.  But you shouldn’t have to bend over backwards for it, and the right solution might be for some other mod to change their code.

I made a couple hasty assumptions on these issues, and I apologize for that.  I think in my initial testing I was hitting the C button before the stock IVA was available, which triggered PCR, then when I did manage to get into IVA and hit the recovery prop the bug occurred.

The recovery prop really is kind of a unique thing because the game (and it seems some mods) don’t expect that the vessel can be recovered during IVA.  It may still be that the recovery prop needs to do something special to make it work better, but at this point my hunch is that this is some issue with PCR.  I will continue digging.

**Comment by MOARdV** [comment]
Barring further information regarding alternatives to the current implementation, closing.

**Comment by JonnyOThan** [comment]
Hey, I managed to fix this in RPM.  KRPC had the same bug too.  It boils down to OnVesselRecoveryRequested needs to be called from LateUpdate, not OnUpdate.  I think a coroutine is probably a better way to do it, but I was a unity n00b when I wrote this.  https://github.com/JonnyOThan/RasterPropMonitor/commit/daabffa54b56a9ab26192ca1144fd9efce2baded

**Comment by MOARdV** [comment]
Thanks for the pointer on how to fix it.  Believe me, I'm not a Unity guy. And I'm definitely not a C# guy - I've written C++ for a couple of decades, so I can pretend like I know C#.
