### ISSUE TITLE
Support stock "target launch site" feature

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#217]
It's a feature that MAS needs to support.

**Comment by theonegalen** [comment]
Oh yeah.

**Comment by MOARdV** [comment]
It's not yet clear where the launch sites are stored, and I haven't actually played with the feature in KSP yet to see how it behaves, so this probably isn't getting done this weekend.

**Comment by MOARdV** [comment]
This seems to be a little less difficult than I expected.  AFAICT, KSP adds the launch sites to the waypoint manager, so I think the base feature is already there.  All I added was a new function that will target the vessel's launch site (whereever it was when it spawned).
