### ISSUE TITLE
Mod incompatibility: KCT

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#221]
Kerbal Construction Time intercepts the launch hook. When user clicks on a green VAB button "launch rocket" then the rocket is just added to the construction queue.
Once the rocket is built and rolled out to the pad the click on the pad produces another KCT menu that allows to assign the crew and launch.

**The problem: with KCT installed clicking on any props inside IVA has no effect except sound.**

I do not know if that's something that MAS can fix or something that KCT should be fixing.

**Comment by MOARdV** [comment]
Can you attach the KSP.log file from a session that demonstrates this problem, or upload it somewhere?  It might give me an idea whether it's something I can address.

**Comment by snakeru** [comment]
GameData contents:
000_ClickThroughBlocker
001_ToolbarControl
ASET
KerbalConstructionTime
MOARdV
MagiCore
ModuleManager.3.1.2.dll
Squad
SquadExpansion



MagiCore is a dependency of KCT.
Log file: [KSP.log](https://github.com/MOARdV/AvionicsSystems/files/2729896/KSP.log)

**Comment by MOARdV** [comment]
I don't see anything obvious in the flight scene.  There is an unhandled exception in KCT in the editor, but I don't know if that has any effect on flight.  MAS thinks initialization was successful.

It may be worth asking the KCT owner if he/she has an idea.

**Comment by snakeru** [comment]
Filed a KCT issue: https://github.com/magico13/KCT/issues/184

**Comment by MOARdV** [comment]
I don't see any indication that KCT development is active at the moment, so I am going to close this bug, since there doesn't appear to be any action I can take with it.
