### ISSUE TITLE
fc.GetLaunchClampCount() seems to always return 0

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#223]
This might not be a bug but just my failure. I have tried creating a flag indicator with the following variable:
			variable = fc.Conditioned(fc.GetLaunchClampCount() > 0)

It seems however to always be "off".
I suspect that the reason is the missing line at MASVesselComputerModules.cs at around line 1410.

**Comment by MOARdV** [comment]
Yes, that was the problem.  Adding a new module to MAS is primarily copy/paste/edit in a few places, and I missed the important one of those places.

**Comment by MOARdV** [comment]
And thank you for the fix.
