### ISSUE TITLE
PROPs are still functional if all kerbals are unconscious.

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#225]
My only kerbal went unconscious during a rather hard reentry. However he was still able to arm the parachute.

I think all props should turn off as if electricity went out. Or even better - even the props that don't normally go off should go off so that as little as possible information is communicated.

This could probably be bound to the same signal that makes the kerbal image to be replaced with white noise.

**Comment by MOARdV** [comment]
Disabling controls may be tricky, although I think I have that code isolated enough to make it work.

Treating blackout as another condition in the "is powered" functionality should be easy, but I don't really have a way to affect instruments that are not subscribed to that feature without introducing a lot of overhead.

What would be ideal would be to black out the entire screen if the current kerbal is suffering GLOC, although I don't know if that should be part of MAS - maybe it can be an optional component?  I'll have to investigate how much effort that would require.

**Comment by theonegalen** [comment]
There used to be a mod called G-Effects that did that, but I had trouble with it.

**Comment by MOARdV** [comment]
> There used to be a mod called G-Effects that did that, but I had trouble with it.

I thought such a thing existed.  Maybe I should track it down and see what it did, and if it could be done in MAS (without causing trouble).

**Comment by theonegalen** [comment]
If you stick a Mainsail under a pod and turn on infinite fuel, that sounds like sustained G's to me.

**Comment by MOARdV** [comment]
> If you stick a Mainsail under a pod and turn on infinite fuel, that sounds like sustained G's to me.

Well, yeah, if I use cheats, it's possible. :)  Maybe I should do that to make sure. :)

**Comment by MOARdV** [comment]
Verified with @theonegalen Mainsail Express, and verified the controls work again after the pilot regains consciousness.  I'm going to defer the screen blackout portion for now.
