### ISSUE TITLE
Control Point switching

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#226]
KSP 1.6.0 added it to ModuleCommand, so it would be nice to figure out how to make use of it.  The one issue I see is handling legacy (mod) pods.  The control point feature adds

```
defaultControlPointDisplayName = #autoLOC_6011003 //#autoLOC_6011003 = Default
CONTROLPOINT
{
	name = reverse
	displayName = #autoLOC_6011004 //#autoLOC_6011004 = Reversed
	orientation = 0,0,180
}
```

(this from the Mk1-3, as an example).  I'll have to see what happens when defaultControlPointDisplayName is missing.

**Comment by MOARdV** [comment]
Looks like it default-configures a single control point, so there doesn't need to be special handling.

**Comment by MOARdV** [comment]
Super easy.

**Comment by theonegalen** [comment]
Nice!
