### ISSUE TITLE
0.92.0 and later break on ASET Mk1 Lander Can

### ISSUE THREAD

**Issue by it0uchpods** [MOARdV/AvionicsSystems#228]
MAS 0.92.0 and 0.92.1 break on the ASET MK1 Lander. 0.91 works fine. I get the [AvionicsSystems]: INITIALIZATION ERROR , CHECK MESSAGE LOG

Here are the logs:
0.92: https://1drv.ms/u/s!Arz15lQFgei8gUHBwTySW9b4qfOz
0.91: https://1drv.ms/u/s!Arz15lQFgei8gUBVSM1RMmDT5fUy

Mod: https://forum.kerbalspaceprogram.com/index.php?/topic/156131-mk1-lander-can-iva-replacement-by-aset11/

Would be nice if this incompatibility could be fixed, I had to downgrade to 0.91 now to fly my crafts.

Thanks!
Josh

**Comment by MOARdV** [comment]
I will have it fixed for the v0.93.0 release later today.

**Comment by MOARdV** [comment]
The Mk1 lander can you linked to is a RasterPropMonitor version of the lander can.  MAS has its own version.  Do you have the ASET lander can IVA installed as well?  If so, I suspect that's the problem - the MM patches are overwriting each other, and leaving things in a bad state when you load the part.

I checked the lander can in a MAS-only installation, and it's working fine.  I will see if I can come up with changes to the MM patch to make sure the RPM patches are not present as well.

**Comment by MOARdV** [comment]
Okay.  Fixed - if the ASET RPM can is installed, the MAS can will not partially override it.

**Comment by it0uchpods** [comment]
Thanks!
Yes, I use the ASET IVA, as it provides a classic IVA Apollo Era, which I love.

It is fixed as of 0.93.0!

Josh
