### ISSUE TITLE
Request: RCS control

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#23]
- Ability to enable all previously disabled RCS Ports
- Ability to set thrust limit for all RCS ports, like a "Thrust limit" for engines

**Comment by MOARdV** [comment]
Do you want to query current thrust limit for all ports?  I can provide simple average or thrust-weighted average.

**Comment by Alexustas** [comment]
> or thrust-weighted average.

I think this option is quite suitable

**Comment by MOARdV** [comment]
Okay.  In the next update (later today, my time zone):

`fc.AnyRCSDisabled()`: return 1 if any RCS thruster is disabled.

`fc.EnableAllRCS()`: Enables any RCS thruster that was disabled.

`fc.GetRCSThrustLimit()`: return 0 to 1 for the weighted thrust limit (enabled RCS only).

`fc.SetRCSThrustLimit(limit)`: Set the thrust limit (number from 0 to 1) for all RCS (enabled and disabled),

**Comment by MOARdV** [comment]
Update posted
