### ISSUE TITLE
MAS Attitude Autopilot overshooting and oscillation

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#234]
Hi,
I had a couple of more or less free days and I immediately returned to the moding (for the first time since last May)

The Attitude Autopilot is a **VERY** useful feature, but the steering algorithm that it uses is extremely inefficient. I recorded a demonstration video about it: https://youtu.be/UqA8bmzcs3Y

Can you improve the performance of the PID controller or do something else to make the control more efficient?

**Comment by MOARdV** [comment]
Welcome back!

Yes, MAS Attitude Autopilot needs more work.  I am going to work on it soon, I think.

**Comment by MOARdV** [comment]
Also, I had a request for an updated ASET prop if you have more free time. :)

**Comment by Alexustas** [comment]
> I had a request for an updated ASET prop

Of course, only you better hurry with this, I do not know how long I will have the opportunity to do something for ksp ((

**Comment by MOARdV** [comment]
> Of course, only you better hurry with this

Prop IndicatorADV - almost perfect for MAS, except for IndicatorNamePlate.  Is it possible to make IndicatorNamePlate blank with optional color, like Modular Push Button Cap?  And add a transform in the middle of the plate for text?  This change allows IndicatorADV to be used for anything with only config file changes.

If it is very easy to change, maybe also IndicatorADV_2Scales, same change?

One last request: is it okay for me to include the ModularPushButton and ModularToggleSwitch PDF files on this Github site?

**Comment by Alexustas** [comment]
> PDF files on this Github site?

yes, no problem

> Is it possible to make IndicatorNamePlate blank with optional color, like Modular Push Button Cap?

Sure thing! What color modes do you need?

**Comment by MOARdV** [comment]
> yes, no problem

Thank you.

> Sure thing! What color modes do you need?

I would be very happy with the same color modes as modular push button  But even a simple color mode such as black, yellow, red, green, white is enough for most situations.

**Comment by Alexustas** [comment]
Here are various options for combining background and text.
![bandicam 2019-01-25 01-16-45-988](https://user-images.githubusercontent.com/6713671/51706115-4db13b80-203f-11e9-9ea9-d62ec76f8abf.jpg)

**Comment by MOARdV** [comment]
> Here are various options for combining background and text.

I think this looks very good.

**Comment by theonegalen** [comment]
Nice! Very glad to see you active again, at least for a bit!

**Comment by MOARdV** [comment]
I have made good progress today on the overshoot and oscillation problem.  If everything continues as I hope, I will have a fix (and improvement) by Saturday.

**Comment by MOARdV** [comment]
Ready for release
