### ISSUE TITLE
Dockport Selection Menu problem

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#235]
on the basis of your configs, I made the following menu for selecting the dockport:

```
// MENU =========================================================================================================
	
	MENU
	{
		name = Dockport Select menu
		position = 2, 4
		maxLines = 14
		
		upSoftkey = 1017
		downSoftkey = 10120
		enterSoftkey = 1023
		homeSoftkey = 1018
		endSoftkey = 1016

		cursorPersistentName = %AUTOID%-DockMenuCursor
		cursor = ►
		cursorColor = 0,255,255,255
		
		itemPositionShift = 2
		itemCount = fc.TargetDockCount()

		ITEM
		{
			name = Dock item
			
			passiveColor = 255,255,255,255
			
			activeText = <=0=>$&$ fc.TargetDockName(%ITEMID%)
			activeColor = 0,255,0,255
			activeVariable = fc.GetPersistentAsNumber("%AUTOID%-DockMenuCursor") == %ITEMID%

			selectEvent = fc.SetTargetDock(%ITEMID%)
		}
	}
```
But for some reason the first item is not displayed in the menu list.
video: https://youtu.be/_TNzVWdGYt4

This problem exists only with the menu of the dockport, all other menus work fine

**Comment by MOARdV** [comment]
Do you have the mode Docking Port Alignment Indicator (DPAI) installed?  If yes, can you see what name the target docking ports have?

**Comment by Alexustas** [comment]
I installed DPAI and in the process of testing I accidentally discovered a very strange thing.
When I first opened the list of available dockports, as before, the first item was missing.
Then I switched to the target vessel to rename the dockport using DPAI. But when I switched back to my vessel, the list was already corrected and the first item was displayed.
in order to double-check what i saw i did a revert. And I repeated it all over again. The first item in the dockport menu was missing, I switched to the target vessel and immediately switched back. All dockports appeared in the list. 
After that, I turned on the time-warp to read the full name of the target because it was very long and suddenly found that the list of the dockport was now completely empty. It is more correct to say - only the labels in the menu disappeared, the dockports themselves did not disappear anywhere and were available for selection. After that, I switched to the target vessel and immediately switched back. All dockports appeared in the list. 
I repeated this sequence twice to make sure that this is not a random glitch.

video: https://youtu.be/whGEs2cFjQ0

**Comment by MOARdV** [comment]
Okay.  There must be something strange with DPAI, and I must check the name it tells me.

**Comment by MOARdV** [comment]
Okay.  I will have to add some testing code and understand what MAS thinks it is doing.

**Comment by MOARdV** [comment]
I found the problem.  There was a bug when a dynamic menu starts at size 0, and then becomes larger.
