### ISSUE TITLE
Text transform/rotation

### ISSUE THREAD

**Issue by DeputyLOL** [MOARdV/AvionicsSystems#24]
I know that this is a shot in the dark and very unlikely to be possible at this stage but.....
Would it be possible to have variable text on a monitor that can be moved and ROTATED by other variables?

**Comment by MOARdV** [comment]
It is possible.  It'll be a bit more work, but I'll see what I can do.

**Comment by DeputyLOL** [comment]
Thanks. The main use for it will be the radio altimeter sticking to the bottom of the Attitude indicator on the PFD. 
It will follow the bottom of the ADI as the aircraft rolls.

**Comment by MOARdV** [comment]
Reviewing the code, text translation is already implemented using the nudges [@x#] and [@y#].  I'll look at adding a rotation nudge to complete this task.

**Comment by DeputyLOL** [comment]
thank you

**Comment by MOARdV** [comment]
Rotation is going to be wonky, unless I add a *lot* of code to my text renderer.  The best way to manage it would be to do a naive rotation from the upper left corner of the text, which means that if you want the text to be centered on the rotation, you'll have to use the X and Y nudges, as well.  As long as the text is fixed text (constant length, not something that can change), that won't be too bad.  But it'll still require a bit of effort to dial it in.

**Comment by DeputyLOL** [comment]
If its too much then don't sweat it. 
I hit kind of a set back with my KSP modding when i accidentally deleted all of it. Had to revert to a slightly old backup. I think my priority is to finish my original 737 cockpit using RPM then see if I can transfer it over to MAS.

All i really need from RPM is a way to move and rotate images on monitors.

**Comment by theonegalen** [comment]
Oh man, that sucks @DeputyLOL - did you redownload your old Advanced Cockpit? If it was anything like my Warbird Cockpits mod, though, there was probably a bunch of WIP stuff that wasn't included with the download.

I gotta figure out a way to back all this up.

**Comment by MOARdV** [comment]
> I gotta figure out a way to back all this up.

GitHub is good for prop configs and other things like that.  You could possibly back up the Unity project, but that will burn a bit of bandwidth.  Backup to another directory, or periodically zip it and put it in an archival directory.  Neither of which I do.  Hmm.

**Comment by DeputyLOL** [comment]
It was sort of unsalvageable.
Windows 10 suddenly decided that I wasn't who I said I was and denied me access to all my game folders. I tried to reinstall steam but it wouldn't even let it do that. Had to use safe mode to get my permissions back but by then all the game folders were empty.

I had a backup from when i first got the new laptop. It wasn't too old thankfully.

**Comment by MOARdV** [comment]
The text rotation still looks to be a mess, since the only reliable way to implement it is to pivot around the upper-left corner of the text.  Anything that requires centering or offsets adds additional complexity that will impact non-rotating text, so I am going to skip over that aspect of this feature request.
