### ISSUE TITLE
Reference Part

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#241]
1. `fc.ReferenceTransformType()` **always** returns "0" while `fc.GetPodIsReference()` returns "1"
2. `fc.SetDockToReference()` has no effect at all

**Comment by MOARdV** [comment]
Hmm.  There is a new stock bug that causes the reference part to reset when changing seats in IVA.  If I am in one seat, set reference dock, and then change seats, KSP reset to the command pod as reference part.

**Comment by MOARdV** [comment]
Both issues in the original bug report have been fixed.  **However**, KSP now resets the reference part to the current command pod any time the player changes IVA seats, even if the player does not exit IVA mode.  This is a new bug in KSP 1.6.0.  In KSP 1.5.1 and earlier versions, changing IVA seats *did not* reset the reference part.

Issue filed at the KSP bug tracker: https://bugs.kerbalspaceprogram.com/issues/21063

**Comment by Alexustas** [comment]
for clarity. The bugs I described in the first post were seen with one crew member. one kerbal in the pilot's seat and two empty seats

**Comment by MOARdV** [comment]
> for clarity. The bugs I described in the first post were seen with one crew member. one kerbal in the pilot's seat and two empty seats

Yes, those bugs are fixed for release tomorrow.  The problem I found is with multiple Kerbal IVA, after those bugs are fixed.  If you change reference part, and then switch to a different Kerbal, the reference part is reset.

**Comment by MOARdV** [comment]
Moved the KSP stock bug description to #243.
