### ISSUE TITLE
Perhaps some of the dock port axes are somehow inverted

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#244]
Here is a screenshot with **zero** alignment of the dock ports in relative angles

![screenshot93](https://user-images.githubusercontent.com/6713671/51861550-5d41c480-235e-11e9-8ce9-5e58991b2e1d.png)

and it looks like the dock port on the screen is upside down. I'm pretty sure that the hatch handle should be at the bottom, and the small window at the top.

Maybe [this information](https://krpc.github.io/krpc/cpp/api/space-center/parts.html#docking-port) will somehow help in the investigation, but most likely you have already seen it.

**Comment by Alexustas** [comment]
additional video
https://youtu.be/Z5QpaLKLJWQ

**Comment by MOARdV** [comment]
The computation was 180 degrees incorrect.
