### ISSUE TITLE
Feature request: visual contact

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#245]
Not sure if this belongs to MAS or should be a separate mod that augments it.
The idea is that the rocket launch can be observed from outside until a certain distance or a certain angle above horizon is reached.

The idea is that once the visual contact is lost the game automatically switches to the IVA mode.
That is just a single switch - if user chooses to press "c" -then  that's his choice and we should not interfere. 

The distance at which the switch should happen should be configurable and depend on the level of the one of the buildings (MissionControl comes to mind). Should probably be equivalent to say, observing the vehicle with a regular binoculars, specialized equipment or having a dedicated observation station. Say 5, 50 and 500 km - actual calculations could be done to figure out what 10x magnification gives us in terms of observing a 20-30 meters object (could actually even depend on the rocket size).

The angle would depend much less from that and probably could be something like 5, 4 and 3 degrees over the horizon.

This FR is inspired by the BARIS mod where you'd probably like to observe your failures from outside, if at all possible.

**Comment by MOARdV** [comment]
I think that's outside the scope of MAS.  It would be better implemented as a stand-alone mod.

**Comment by theonegalen** [comment]
Alternatively, it might be good to code a bridge between MAS and BARIS that allows for some kind of a master alarm / warning light system that will alert of engine and other problems.

**Comment by snakeru** [comment]
Yet another option would be to implement the ICanBreak and allow different instruments to stop functioning mid-flight.

**Comment by MOARdV** [comment]
Implementing ICanBreak requires a hard dependency on another mod (it's not part of stock KSP), which isn't a viable option - one of the design features of MAS is it does not require other mods for basic functionality.
