### ISSUE TITLE
Misc minor functions

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#251]
A few odds-and-ends I thought up.

- [x] `fc.ColorComponent(string colorName, double channel)` - decompose a named color (eg `COLOR_MOARdV_ActiveBacklightText`) into its R, G, B, or A component (depending on `channel` - 0, 1, 2, or 3).  This would allow manipulating named colors (blending, dimming, etc) without having to resort to manually copying the value.
- [x] `fc.ColorTag(string colorName)` - return the RGBA color tag for the specified color name.  I don't know how many times I've copy/pasted the same RGB hex tag to display a named color, and if that color is overridden or edited, all of those copy/pastes won't be updated.

**Comment by Alexustas** [comment]
As for me, this is one of the most **MAJOR** features. 🥇

**Comment by MOARdV** [comment]
> As for me, this is one of the most **MAJOR** features.

I call it "minor" feature because it was easy to write (10 minutes total). :)

And it is now available on GitHub with v0.95.1
