### ISSUE TITLE
build-in landing prediction

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#255]
Now the functions `fc.LandingAltitude()`, `fc.LandingLatitude()`, `fc.LandingLongitude() `and `fc.LandingTime()` automatically selects the data source depending on the installed mods (MF or KE) or use MAS predictor if no mods installed. 
Can you add a boolean argument for all these functions? so that it is possible to prohibit the use of external data from mods, even if they are installed, and only use the built-in MAS predictor

**Comment by MOARdV** [comment]
I think it is easier for me to add new functions `MASLandingAltitude()`, and similar.  These will only use MAS computation, and nothing else.

**Comment by Alexustas** [comment]
ok. you know better ))
