### ISSUE TITLE
parachute.DeploymentSafe()

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#259]
Now we have a mismatch of deplyment safety status. when the `parachute.DeploymentSafe()` returns -1, the stock parachute module reports "risky" and its icon is colored orange, and when the `parachute.DeploymentSafe()` returns 0, the stock module of the parachute reports "unsafe" and its icon is colored red

**Comment by MOARdV** [comment]
I had the definition of UNSAFE and RISKY backwards for stock parachutes.
