### ISSUE TITLE
Request: The ability to use Transforms list in the "COLOR_SHIFT" component

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#26]
it only needs for convenience, so you can ignore and close this request.

Is it possible to add the ability to specify a comma separated list of objects in the "COLOR_SHIFT" module ?

for example
	

```
COLOR_SHIFT
        {
            name = Tumbler Mark
            transform = TumblerMarkObj, CircleMarkObj1, CircleMarkObj2, PointerObj, OuterScaleObj, InnerScaleObj
            passiveColor = 0,0,0,255
            activeColor = 145,145,145,255
            variable = fc.Conditioned(fc.GetPersistentAsNumber("Backlight"))
        }
```

**Comment by MOARdV** [comment]
That is a good idea, and I think it will be easy.  I'll add it to my "to do" list.

**Comment by MOARdV** [comment]
Okay, this is now available in today's updated dev build.
