### ISSUE TITLE
DSKY doesn't work in my IVA...

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#262]
## SOLVED

Hi @MOARdV.

Could you please have a look? For some reason a lot of props work in my work-in-progress IVA, but DSKY doesn't. I have made a test craft that consists of 2 pods (Mk1 Lander Can and Mk2) and 1 DSKYs works but the other doesn't.

What could be wrong?

If you'll be launching this, you'll need the "Making History" expansion for the Mk2 pod.

[a.zip](https://github.com/MOARdV/AvionicsSystems/files/2974867/a.zip)

![image](https://user-images.githubusercontent.com/72657/54486510-93dd8b00-4889-11e9-91f0-e60b5159b2c7.png)

**Comment by snakeru** [comment]
Ahh... Forget this. I'll leave this here so you can refer people to this. 
The problem was only my stupidity. I had to use the MAS_ASET_DSKY prop, but I used the ASET_DSKY.

Obviously that couldn't have worked.

Thank you!

**Comment by MOARdV** [comment]
That's happened to me before, as well.  There is a disadvantage to having many, many props with similar names from two different IVA mods.

**Comment by theonegalen** [comment]
That pot is looking great!

**Comment by snakeru** [comment]
@theonegalen That pod looks very definitely senond-hand. Though I keep slowly improving it. The main thing for me was to identify what prop is there.

I think it's the Squad's textures - they left dark spots under each prop, probably for artistic purposes.
But now as I remove, say, a circular knob and replace it with a rectangular, then ... it gets this "recovered from Jebediah Kerman's scrapyard" look :)

**Comment by MOARdV** [comment]
@snakeru - take a look at the ASET props Primitive_BOX_(color) and Primitive_TRIANGLE_(color).  alexustas used those to cover the IVA surfaces of the old Mk1-2 3-crew command pod, and I've used them as well to cover panels.  Use asymmetric scales, and you can cover the ugly control panel texture with uniform, flat surfaces (the old IVAs also have a problem where their surfaces are not flat).

And you can select multiple props and move them all at once, so it's possible to move your existing instruments a little bit to fit the primitives over the panels.

**Comment by snakeru** [comment]
> And you can select multiple props and move them all at once, so it's possible to move your existing instruments a little bit to fit the primitives over the panels.

LOL. You seem to assume that I have something with which I "select" props. I don't. I really only have a text editor, that's all. Here is a screenshot of my working environment (featuring a part of the python script I use to generate the internal.cfg:
![image](https://user-images.githubusercontent.com/72657/54607118-dd76d300-4a4d-11e9-8520-316828a1d764.png)

**Comment by MOARdV** [comment]
Ah.  That certainly makes things drastically more challenging.

I would strongly recommend installing Unity and the KSP Part Tools DLL, assuming you have the disk space for Unity.  It's drastically easier than text editing, and you don't have to manipulate quaternions by hand. Although, since that's a python script, you should be able to write a Euler angles -> quaternion conversion - it requires some sine and cosine operations, and some multiplication.  That would at least allow you to use easier to read angles.

**Comment by Alexustas** [comment]
@snakeru are you not using Unity Editor at all ??

**Comment by snakeru** [comment]
@Alexustas yes.
I can't install it, for certain, non-technical reasons.
