### ISSUE TITLE
Feature request: cleaned ship description.

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#266]
Sorry if I overlooked it and the feature already exists.
I tried to display the ship description, but this attempt failed:
`text = <=0=>$&$ EditorLogic.fetch.shipDescriptionField.text`

It would be nice to have access to the ship description (ideally - cleaned up from the action groups stuff) - with heavy rockets it is often essential to have some notes on ascent sequence that is needed to get safely into orbit and the ship description is the only place these could be kept in.

**Comment by MOARdV** [comment]
No, that doesn't currently exist.  The code required to implement it is about 80% done, so it wouldn't be too tough to add it.

**Comment by snakeru** [comment]
Another use for it would be the same ascent autopilot - if implemented in lua.

**Comment by MOARdV** [comment]
Okay, it'll be in the next update.
