### ISSUE TITLE
Bug: toggle switch modular cover is not reliable

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#267]
I have a modular switch of the following configuration: MAS_tggl_asMode_T1_G1_C1_S.cfg

The switch is located rather low so I am able to see it from above. Apparently the cover does not cover the whole underlying switch collider and there is a small piece of it exposed (matches the grey band on the screenshot).

So I am able to switch the switch without opening the cover.
![image](https://user-images.githubusercontent.com/72657/55669730-2666be00-587b-11e9-8662-7679ca550238.png)

[asMode.zip](https://github.com/MOARdV/AvionicsSystems/files/3050463/asMode.zip)

**Comment by MOARdV** [comment]
The colliders are part of the model, unfortunately.  That's not something I can fix in MAS.
