### ISSUE TITLE
IVA crash when controlled from other part

### ISSUE THREAD

**Issue by snakeru** [MOARdV/AvionicsSystems#269]
I have managed to lock myself out of IVA. I strongly suspect this happened because the ship was controller from the about-to-be-detached stage.

Simplified scheme: pod-decoupler-tank-SE-decoupler-tank-**controlprobe**-ME

Due to the ship being very heavy and extra long I have inserted a control probe at the bottom end to get more stable steering. Therefore the control was happening, effectively, from the bottom stage and once it has burned out the staging event forced me out of IVA.

However, this caused the following effects as well:
1) Once I switched ships there was no way for me to switch back into the IVA
2) Attempts to switch to IVA rendered almost everything unresponsive - I was not able to control the ship or even the camera.

Cycling to map mode and back was fixing the issue (2) but not (1).
[KSP.log.zip](https://github.com/MOARdV/AvionicsSystems/files/3105592/KSP.log.zip)

**Comment by MOARdV** [comment]
There are a lot of exceptions and errors in that log - I suspect part of the issue is there are mods that are out of date or have bugs.  I see a few MAS exceptions as well, so I'll see if I can make sense of them, although it'll be a challenge if I can't reproduce it.

**Comment by MOARdV** [comment]
The most common MAS-related exception is happening in the onCameraChange callback.  The only way that'd be likely is if InternalCamera.Instance is null - there really aren't other values being dereferenced that could be null at that stage.

**Comment by snakeru** [comment]
Ahh... My naive belief that there is no more than one issue in the log. Sorry, I was dumb. I also did not thought of trying to reproduce this on a less modded install.

Here is a redo in my "development" copy with much less mods (some might still be obsolete though):
1) I had a small craft, consisting of: Mk2 Pod, decoupler and Mk1LanderCan on top of it.
2) The AG1 was configured to "control from Mk1LanderCan" and AG2 to "decouple".
3) The pilot was sitting in the Mk2
4) At 17:12:40 I have clicked the AG1 (with the mouse) - worked as intended
5) At 17:12:50 I have clicked the AG2 - I was thrown out of IVA and observed "something" from some peculiar angle - only the sky and a couple of polygons were visible.
6) At 17:14:01 I tried rotating the camera with arrow keys - it didn't work
7) At 17:14:40 I entered the map with hotkey "M" - it worked, arrow keys worked there as well.
8) At 17:15:25 I exited the map with the same hotkey - it exited, though I observed now a black sky with stars, no blue sky or poligons were visible (at least I didn't notice).
9) At 17:16:10 I tried using arrow keys without any success - unmoving starry sky.
10) At 17:17 I zipped the log without exiting the ksp.

[17-17.zip](https://github.com/MOARdV/AvionicsSystems/files/3108252/17-17.zip)

**Comment by snakeru** [comment]
For the record, the installed mods are: base, MH, ASET props, ASET avionics, AutoLoadGame, MEM (MAS-config for MEM), MAS, my MAS-config for Mk2, module-manager.

**Comment by MOARdV** [comment]
The log + your detailed time line help **a lot**.  I think what's happening with the MAS exception is that the empty lander can is the active vessel - it's a MAS-enabled part, but there's no crew, so there's no internal camera available, and MAS is doing Bad Things because of an invalid assumption.

As for the odd camera views when you got kicked out of IVA - KSP has a bad habit of setting the camera up like it's in extreme closeup mode (the camera is inside the part's mesh).  If that happens, zooming out should help you get your bearings.  I will can reproduce the failure here (it shouldn't be too hard), and confirm that I can eliminate that exception.
