### ISSUE TITLE
COLLIDER_ADVANCED

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#271]
I need to think of a better name than COLLIDER_ADVANCED.  Or not.

It is possible to determine *where* in a collider the mouse click happened.  I can then convert the hit location to a normalized value in the volume (0, 0, 0) - (1, 1, 1).

Which means, with a little bit more effort, I can convert that hit location into a 2D value, which means it's possible to create touch-screen MFDs.

Topics that need nailed down or implemented:
- [x] Configuring the collider.  I don't have any control over how a given collider is oriented, so I need to provide a way for the config to select which two of the 3 axes are valid (as an example, the buttons on the ASET HUD use X and Z - the front face is Y).  It also needs to allow for negation and scaling of the value.
- [x] Passing that info to MAS_PAGE.  There needs to be a way to attach the collider to the MASMonitor (logically in the config file).  Maybe a function similar to `fc.SendSoftkey()`, like `fc.SendTap("%AUTOID%", x, y)`?
- [x] Processing that info in the MAS_PAGE.  There needs to be a way to define "hit box" bounds that are active, each of which has its own click handler.
- [x] Click event.
- [x] Tap-and-release event (tap location did not move, like a quick click/release).
- [x] Tap-and-drag event (hit location changes between the click and release), needed for the tap-and-drag controls).
- [x] Tap-and-release out of bounds - someone pressed a button, then moved off the button to release it.
- [x] Expose coordinates of the tap / release events.  I managed this for the basic collider, so I should be able to do it here, too.
- [x] Config options in the COLLIDER_ADVANCED to use with conventional props, not just the MFD.
- [x] `variable` field to allow a hitbox to be disabled / conditionally enabled.

**Comment by theonegalen** [comment]
Whaaaf

**Comment by MOARdV** [comment]
> Whaaat

Touch screen MFDs. :)

If I get the basic functionality figured out, I might be able to expand that to other applications, but that's way down the road.

**Comment by MOARdV** [comment]
Mostly works ... except that the hit location and the bounds are in world-space coordinates, which means if the collider is rotated at all, the hit coordinates I currently generate will be wrong.  I need to transform the hit location into the collider's space.

**Comment by MOARdV** [comment]
Fixed the bugs, got touch controls working for non-monitors, and added a throttle slider control using the IndicatorADV prop.

I really need to add a general-purpose monitor to MAS to demonstrate touch controls, since it's a more complex topic.

**Comment by theonegalen** [comment]
Amazing
