### ISSUE TITLE
[AvionicsSystems] INITIALIZATION ERROR, CHECK MESSAGE LOG.

### ISSUE THREAD

**Issue by Sam-Neale** [MOARdV/AvionicsSystems#280]
Hello, I am trying the MOARdvPlus on a FASA Apollo Command Module, and the In-Vehicle-View is frozen with no response from any buttons, or displays, I can not find the "MESSAGE LOG" also.
What do I do?

**Comment by Sam-Neale** [comment]
Oh yea, I am playing with RO/RSS on kip 1.6.1

**Comment by MOARdV** [comment]
The message log is KSP.log.  On Windows, KSP.log is written in the same folder that contains KSP_x64.exe.

Which version of MAS are you using?  KSP 1.6.1 is an older KSP version, and new versions of MAS are not compatible with it (my notes says MAS 0.98.0 was the last MAS version that was expected to work with KSP 1.6.1)

**Comment by Sam-Neale** [comment]
Ok I am reallllly stupid, I never installed MAS, smh

**Comment by Sam-Neale** [comment]
I did install the new version however I installed the 1.6.1 compatible version. and it still didnt work, 
[KSP copy.log](https://github.com/MOARdV/AvionicsSystems/files/3719898/KSP.copy.log)

**Comment by Sam-Neale** [comment]
Is there a dependancy I am missing?

**Comment by MOARdV** [comment]
It doesn't looks like you're using the MAS Apollo CM.  It looks like something was done to add the MAS IVA to the FASA Apollo CM.

In the Command Pods list in the editor, there should be a MAS FASA RA-01 CM.  That's the 1960's style Apollo CM, and it should work out of the box.  Be aware that it the config was adjusted to work with Bluedog Design Bureau Apollo parts in a stock-scaled installation.

If you want to use the MAS IVA with the FASA Apollo CM, you'll need to add a MM patch to install the MASFlightComputer module to the command pod - that's what all of the errors are about.  Just copy the entire MASFlightComputer module out of MOARdVPlus/MAS_FASA_Apollo/Parts/FASA_Apollo_CM.cfg and put that in a MM patch that adds it to the FASA CM.
