### ISSUE TITLE
Moardv/Flightsystems/Squad.cfg removes dockingports in KSP 1.8.0

### ISSUE THREAD

**Issue by JonathanC8** [MOARdV/AvionicsSystems#281]
I removed the squad.cfg file from avionics system and it seems to fix the problem. Other than that Moardv and MoardvPlus are compatible with ksp 1.8.0

**Comment by MOARdV** [comment]
Unfortunately, if the CFG file is causing parts to disappear, then MAS is very definitely not compatible.  All that patch does is add a radar and camera to the docking port, so there's something seriously wrong with one of those modules.

But thank you for checking the rest of the functionality - at least that tells me it's not going to be too horrible to fix. :)

**Comment by panarchist** [comment]
Confirming behavior in Windows version w no other mods.

**Comment by MOARdV** [comment]
> Confirming behavior in Windows version w no other mods.

Fortunately, it looks like a fairly straight-forward fix.  I want to spot check with a glass cockpit before I make a release, but that should happen this weekend.

**Comment by MOARdV** [comment]
Fixed for the v1.1.0 / KSP 1.8.x version
