### ISSUE TITLE
Modded Launch Sites cause MAS to fail to configure

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#293]
A trapped NRE in MASINavigation when launching from a modded launch site causes MASFlightComputer.Start() to fail to complete.  From the call stack, it looks like a problem selecting the launch site's name in the MASINavigation constructor.

Since the NRE causes MAS to skip configuring the rest of the proxy objects, but doesn't prevent the balance of Start() from executing, I end up leaving a bunch of null values floating around.

I need to install the relevant mod and see if I can identify a way to include the site's name even if localization isn't configured.

Callstack:
```
[ERR 12:59:55.460] [MASFlightComputer] System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
  at KSP.Localization.Localizer.GetStringByTag (System.String tag) [0x00005] in <394a98b9c7624adc895c04290da62640>:0 
  at AvionicsSystems.MASINavigation..ctor (Vessel vessel, AvionicsSystems.MASFlightComputer fc) [0x00103] in <40ea1bba0cb943a78937ff6bf85192ca>:0 
  at AvionicsSystems.MASFlightComputer.Start () [0x0053a] in <40ea1bba0cb943a78937ff6bf85192ca>:0 
```

**Comment by MOARdV** [comment]
The issue is that I'm calling GetStringByTag, which throws an exception.  If I use TryGetStringByTag, I can take corrective measures without the exception throwing up.

**Comment by theonegalen** [comment]
By "modded launch sites" were you referring to Kerbal Konstructs sites or KSCswitcher sites, or both?

**Comment by MOARdV** [comment]
> By "modded launch sites" were you referring to Kerbal Konstructs sites or KSCswitcher sites, or both?

KK sites.  Some of the site names aren't localized, and KSP's localization tool throws exceptions if it is given a string that's not localized.  I did not try KSCswitcher (I've never used it), but if it adds new launch sites, this fix will help it as well.

**Comment by theonegalen** [comment]
Thanks!
