### ISSUE TITLE
Rolling Digits

### ISSUE THREAD

**Issue by DeputyLOL** [MOARdV/AvionicsSystems#3]
That...
![rolling digit](https://cloud.githubusercontent.com/assets/12616126/17140921/3167727c-5342-11e6-8530-2c5066457a98.jpg)

Some way to get this without the need for lots of configs. 
Can we also get the ability to change its 'roll rate', meaning that the 'one' unit will move continuously and the 'tens' will only move when the tens change.

**Comment by MOARdV** [comment]
Yes, that "should" be easy to do.  (famous last words)

**Comment by MOARdV** [comment]
To clarify this:

> Can we also get the ability to change its 'roll rate', meaning that the 'one' unit will move continuously and the 'tens' will only move when the tens change.

The "easy" thing for me to do is to make the ones unit continuously scrolling like a mechanical odometer does, but the other digits snap (so, when it goes 249-250, the 9 will scroll to 0, but the '24' will instantly become '25').  Do you think that will work okay, at least to start?

**Comment by DeputyLOL** [comment]
Yeah, Its a good start. As for other vertical/Horizontal bars and other on screen magic, can we have a 'change rate'. Kind of like RPMs max rate change for props.

I might have remember seeing that the vertical/horizontal bars now have a 'loop' setting.

**Comment by MOARdV** [comment]
Yeah, the vertical / horizontal bars have a loop - so you can use them like the heading strip (wraps around), or like a VSI/altimeter/speed gauge.

A change rate would complicate things - what's the use case for it on a digital display (what is it needed for)?

**Comment by DeputyLOL** [comment]
If you have a warning flag that appear when a certain variables changes from 0 to 1

**Comment by DeputyLOL** [comment]
I'm using quite a few vertical bars for things other than flight conditions.
I use the vertical bars for the speed limits that change with flap and gear position. When you change flap setting the new speed limits changing immediately, it would be better if the speed limit bars quickly change.

**Comment by MOARdV** [comment]
Okay.  I will see what I can manage,

**Comment by theonegalen** [comment]
I assume from the open issue that this is not implemented as yet?

**Comment by MOARdV** [comment]
> I assume from the open issue that this is not implemented as yet?

Correct.  I have not come up with a way to implement this that isn't excessively convoluted.  There's a simple answer somewhere, but it hasn't revealed itself.

**Comment by theonegalen** [comment]
I'm working on starting to code for KSP but I'm teaching myself and it is slow going.

Maybe I can be helpful eventually.

**Comment by MOARdV** [comment]
The very, very old ROLLING_DIGIT request is finally implemented.  I need to fine-tune the rolling digits a little more, and consider whether the rolling digits (as opposed to the static digits) should be allowed to have a separately-defined color

**Comment by theonegalen** [comment]
Thank you!
