### ISSUE TITLE
MENU MASMonitor type

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#30]
This will be a major undertaking.  Time to start making notes.  The goal is user-configured menus.  How I get there is the trick...

First ideas: 
- Something similar to the way MASMonitor pages are done - that is, each menu is named.
- Each `MAS_MENU` contains one or more things describing what's in the menu, and what it does, such as `MENU_ITEM` for a single entry.
- Each `MENU_ITEM` contains text, an optional "right hand side text" (like the range indicators for vessels in RPM), a variable to disable the entry, and an action.  There should possibly also be a variable to enable the action, separate from the disable variable - I'm thinking of the case in the vessel targeting menu to select a docking port on a tracked vessel.
- A `MULTI_ITEM` menu - this entry will be used for lists, and it will require an iterator limit variable and variables to control what's displayed.  Some ideas would be `fc.NumVesselsInSoI()` that returns the number of other vessels in the current SoI, and `fc.VesselInSoIName(index)` that will return the name of the specified vessel.  This feature needs more thought...
- Key presses will map to persistents (that is, Home, Prev, Next, Enter, Back, etc will be tracked by persistent key transitions).  Something like `fc.SetPersistent("MonitorKey%PROPID%", 1)` on key press, and `fc.SetPersistent("MonitorKey%PROPID%", 0)` on key release; different numbers can indicate different keys.  The alternative is a unique persistent per key, like `MonitorKeyHome%PROPID%` for the Home key, `MonitorKeyEnter%PROPID%` for Enter, etc.  That increases the number of persistent variables that are required, which also means more overhead for MASFlightComputer to track changes.

**Comment by MOARdV** [comment]
New menu idea ...
```
MENU
{
  name = My Awesome Menu

  position = x, y

  font = Local font
  style = Bold
  fontSize = 16, 32
  textColor = COLOR_MY_FONT_COLOR

  upSoftkey = 7
  downSoftkey = 8
  enterSoftkey = 9

 ...
}
```
* `position` is a text position, like TEXT node.
* `font`, `style`, `fontSize`, `textColor` are (optional) overrides, also like TEXT node.
* `upSoftkey`, `downSoftkey`, and `enterSoftkey` are the numbers for soft keys to show up arrow, down arrow, and enter softkey numbers.

*Will edit with rest of idea later - ran out of time*

**Comment by MOARdV** [comment]
```
ITEM
{
  name = My Menu Item
  font = Override Font
  style = Bold

  passiveText = Passive text caption
  passiveColor = COLOR_PASSIVE_COLOR

  activeText = Active text caption
  activeColor = COLOR_ACTIVE_COLOR
  activeVariable = fc.SomeVariable()

  disabledText = Disabled text caption
  disabledColor = COLOR_DISABLED_COLOR

  enabledVariable = 1

  selectEvent = MyItemAction()
}
```
* `font`, `style` override options, same as TEXT.
* `passiveText` - Required, default text.
* `passiveColor` - Optional, override default color for passive text only.
* `activeText` - Optional.  Text displayed when `activeVariable` is > 0.  Use this to show different text for active vs. passive.  If all you need is change the color of the text, use color nudges in passiveText.
* `activeColor` - Optional, override default color for active text.
* `disabledText` - Optional, Text displayed when `enabledVariable` <= 0.  `disabledColor` is default text color for disabledText.
* `enabledVariable` - Optional, default '1'.  If enabledVariable becomes false (<= 0), `selectEvent` is disabled.
* `selectEvent` - Optional, the event triggered when enterSoftkey is pressed, as long as `enabledVariable` is ready.

Simple example:
```
ITEM
{
  name = Toggle RCS menu

  passiveText = [#<=0:"00ff00";"7f7f7f"=>]Toggle RCS$&$fc.GetRCS() - 0.5
  selectEvent = fc.ToggleRCS()
}
```
"Toggle RCS" is green when RCS is on, gray when off.

**Comment by MOARdV** [comment]
```
LIST_ITEM
{
  name = Menu list

  count = fc.TargetVesselCount()

  passiveText = <=0=>$&$ fc.TargetVesselName(%LIST_INDEX%)
  selectEvent = fc.SetTargetVessel(%LIST_INDEX%)
}
```
Automatically make menu items for counts 0 to `count` - 1.  Keyword %LIST_INDEX% is converted to the number of the menu item (0 for first one, etc).

*Still designing*

**Comment by Alexustas** [comment]
> only allow the first letter? Or allow more than one letter?

as an option, you can add a character at the end of the line. 
example:

```
  menu item 1  
 ►menu item 2◄
  menu item 3
```

I myself want to make such a design of a menu

![bandicam 2017-12-19 19-48-50-915](https://user-images.githubusercontent.com/6713671/34162539-e5eb403e-e4f5-11e7-9ec6-6a03a0293f72.jpg)

**Comment by Alexustas** [comment]
by the way, in case of LIST_ITEM, it will be very useful if you add the ability to scroll the list if the list contains more items than it is allowed to show on this page. The maximum number of items must be specified in the node configuration

**Comment by Alexustas** [comment]
> upSoftkey, downSoftkey, and enterSoftkey 

I propose to add two more **optional** soft-keys: "Home" and "End". To quickly jump to the beginning and end of the menu, respectively

**Comment by Alexustas** [comment]
> selectEvent - Optional, the event triggered when enterSoftkey is pressed, as long as enabledVariable is ready.

is it possible to execute several events?

**Comment by MOARdV** [comment]
> by the way, in case of LIST_ITEM, it will be very useful if you add the ability to scroll the list if the list contains more items than it is allowed to show on this page. The maximum number of items must be specified in the node configuration

Yes, I forgot to add that to MENU (maximum items to display).  I intend for scrolling.

> I propose to add two more optional soft-keys: "Home" and "End".

Good idea - I would not think of that until I tried scrolling a large list of items.

> is it possible to execute several events?

Lua script can do that. :)

**Comment by MOARdV** [comment]
I think I may split this into MENU and MENU_LIST - LIST_ITEM can change size, and if I have to adjust the size of a list that also can have non-list ITEM in it, it becomes very messy.

`MENU` for a menu with manual `ITEM`.  `MENU_LIST` for a menu with automatic items (such as a Target Vessel menu).

*(Remind myself that MENU_LIST must have a special case for a list count of zero - maybe the config has a `noOptionsText`?)*

**Comment by MOARdV** [comment]
I think I have this working.  Documentation for [MENU](https://github.com/MOARdV/AvionicsSystems/wiki/MASMonitor#menu) is on the wiki.  Example of a "dynamic" menu in [MFD](https://github.com/MOARdV/AvionicsSystems/blob/b76b513ff5d1fae7a56f2beba2121f000b7ece94/GameData/MOARdV/MFD/kOS_Action.cfg#L171).  Beta build on [DropBox](https://www.dropbox.com/s/qo4a5yxz3qa6065/AvionicsSystems-0.21.0b1.zip?dl=0) - also note that starting with this build, MAS includes MiniAVC.dll.
