### ISSUE TITLE
Add INTERNAL_TEXT

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#301]
This is to handle a corner-case.

The stock LED Speed panels are used in vanilla RPM for a number of props.  Instead of using the RPM text renderer, they instead use the KSP InternalText object, which internally uses TextMeshPro.

For reasons I have not been able to sort out, using the normal TEXT_LABEL component does not work for this use case (I'm assuming it's because the transform is in a bad spot, and I don't know how to extract it somewhere useful).  So, if I'm going to make MAS replacements for the RPM props, I need to add a special-case text renderer, or I need to figure out how to solve the problem with attaching the default MAS text renderer.

**Comment by theonegalen** [comment]
Thanks for all of this.
