### ISSUE TITLE
Implement ASET AVAS system

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#314]
Another of the complex ASET features that needs translated into MAS.

Affected props:

**Comment by StoneBlue** [comment]
Is this still really open?
I see all the AVAS props in MAS have MASComponents, as well as there being a .lua script for the manual AVAS pushbutton..?

**Comment by MOARdV** [comment]
Yeah, you're right.  This was one of the batch of props vulkans22 did last year.
