### ISSUE TITLE
Bug when switching vessels screen goes black

### ISSUE THREAD

**Issue by GdfrGdfr** [MOARdV/AvionicsSystems#323]
Bug, when switching vessels screen goes black only fix, is to load last quicksave or restart the game. this happens multiple times between different ships and I don't know what to do says to check log but I have no idea what I'm doing, please help.
the log is too big and cant paste so I need to find a workaround.

**Comment by GdfrGdfr** [comment]
[logs.zip](https://github.com/MOARdV/AvionicsSystems/files/5226799/logs.zip)
logs in a compressed file

**Comment by MOARdV** [comment]
I see two problems - first problem, MiniAVC is installed.  MiniAVC does not work with KSP 1.9.x and newer, and it needs to be removed.  Second problem, there is an error when MAS tries to load the asset bundles included with the MAS installation.  It looks like something did not get installed correctly, or possibly the broken MiniAVC mod is interfering with MAS loading.

**Comment by GdfrGdfr** [comment]
Thank you, but how would i uninstall minavc?

**Comment by MOARdV** [comment]
Just the miniavc.dll files need to be deleted.  There is a newer version of the mod called MiniAVC-v2 that provides version checking for KSP 1.9.x and later, if you wanted the mod update notifications when you start KSP.
