### ISSUE TITLE
SetMultiModeEngineMode / ToggleMultiModeEngineMode issues

### ISSUE THREAD

**Issue by vulkans22** [MOARdV/AvionicsSystems#324]
Sorry for no pull requests, I don't have a git environment setup at the moment.

While working on converting ASET prop/avionics props over to MAS, I found that both of these functions are returning an iterator out of range exception. Looking at MASFlightComputerProxy:4820 for the problem on the toggle function, where the for loop iterator is starting on a +1 index range. Trivial fix would be to change vc.multiModeEngines.Length to vc.multiModeEngines.Length - 1 on both functions.

The second issue is that switching the multimode engines from 0 to 1 causes numerous props (Like the TWR and TWRMAX props for example) to return zero-ed data, I'm guessing the multimode engine switch is equal to a craft change and requires invalidating the saved module lists and rebuilding them?

**Comment by MOARdV** [comment]
I guess it shows how often I've used the multi-mode engine feature. :)

Thank you for diagnosing the issue.  That's a trivial fix.  I'll have to look into the TWR not updating after mode change.

If your ASET conversions are drop-in replacements for RPM, and you're willing to contribute them to the MAS distribution, I'd be quite interested.  Issue 277 is a master list of prop categoriess that have been converted, and Issue 322 tracks the MFDs.  I got a start on them, but it was such a tedious task that I stopped working on it a few weeks ago.  I've got enough props to update the entire ASET / ALCOR lander, with the exception of the MFDs.

**Comment by vulkans22** [comment]
I can surely understand your thoughts on the tedium, after spending the better part of three hours just doing the GPS/NAV display and its corresponding rotary that shows LAT/LON coordinates, where about 80% of that time was just waiting for KSP to restart.

I'm currently populating the J-HT cockpit from the OPT space place pack, with a mix of both prop and avionics props and I've been converting any that didn't get picked up by the conversion patch which wasn't a lot. mostly a few gauges from the avionics pack and some other random props like the A320 style landing gear lever. I'll have a stab at doing the NAV1/2 - DME - COMM stack next, followed by the GPWS/AVAS stuff after that and boy am I not looking forward to doing those. I've also added pages to the 40x20 MFD for the NavUtilities HLS mod and for kOSPropMonitor which is an RPM interface for kOS, happy to report both of them working fine.

I'll have a look at 277/322, and make any conversions available, along with any more that I get to as I require them. Hopefully I can get around to setting up for pull requests to simplify things.

Great work on MAS by the way, it's been nice to fly in a well populated IVA at more than 15 frames per second.

**Comment by MOARdV** [comment]
Thank you for the comment on MAS.  It's hard for me to get performance feedback, since there aren't a lot of playable IVAs out there yet.

The radio NAV instruments are some I've been meaning to do, since MAS has radio navigation support.  I've never put together an instrument or an MFD page that actually uses more than a fraction of it.  I think alexustas had some instruments working with it, since he was giving me regular feedback and pointing me at resources online as I was developing the feature.
