### ISSUE TITLE
Navball not working in IVA

### ISSUE THREAD

**Issue by tsraveling** [MOARdV/AvionicsSystems#328]
Currently navball is not updating at all while in IVA. For what it's worth, this was also true of of RPM as well. I saw that this was an issue when 1.10 came out, so I'm assuming maybe something similar happened with the 1.11 release.

**Comment by MOARdV** [comment]
Tested the FDAI in the Mk1 capsule during MAS 1.3.0 development against KSP 1.2.3, and it appears to work.
