### ISSUE TITLE
The Navball is not working

### ISSUE THREAD

**Issue by AidanPaws** [MOARdV/AvionicsSystems#334]
When I click on power on for the navball it says initialization error

Version: 1.2.2
Game Version: 1.11.2.3077

I have other mods installed using ckan.

System specs

MSI b550 -a pro
GT 730
AMD Ryzen 3600
Ripjawz ddr4 3600

**Comment by MOARdV** [comment]
I'm finally clearing out some bugs.  I can not reproduce this with the current development version of MAS, so I'm marking it 'fixed' with MAS 1.3.0 / KSP 1.2.3
