### ISSUE TITLE
MAS doesn't seem to use KSPAssembly attribute

### ISSUE THREAD

**Issue by JonnyOThan** [MOARdV/AvionicsSystems#354]
I'm working on adding MAS support to KerbalVR, and the way this works is that I have bridge dlls that can talk directly to RPM and MAS.  The RPM one uses a KSPAssemblyDependency attribute to tell KSP to not load it if RPM is not present.  I was going to do the same with MAS, but it doesn't seem to have a KSPAssembly attribute that I can use to target it.

**Comment by JonnyOThan** [comment]
I’m happy to send a pr for this, but it’s a little tricky because of the shared assembly info file.  The other project that uses it doesn’t depend on the KSP dll.  Possible solutions:
1) abandon the shared assembly info file. You’d need to manually keep the version numbers in sync (if that’s actually important)
2) put the KSPAssembly attribute into the non-shared assembly info file. You’d need to update the version numbers in two places.
3) Something more complicated using text templating to generate all the files so the version number can be set in a single place

I’d opt for 1, but I’ll leave it up to you

**Comment by MOARdV** [comment]
Yeah, separating the assembly file is the route I'd take.  I'm not really distributing the config generator tool now, and it's not getting updated regularly, so it doesn't need synchronized version numbers.
