### ISSUE TITLE
Text will not render (Linux)

### ISSUE THREAD

**Issue by TheSystemGuy1337** [MOARdV/AvionicsSystems#366]
I might be an idiot for using Linux with this mod, but I will complain anyway. If I use ASET Consolidated, **NONE** of the text renders, at all. This includes warning lights, LCDs and anything that involves text. Even without Consolidated, text rendering is screwy and inoperative at best. This issue is most apparent in the MK1 lander can.  It is behaving like the fonts are missing.  I am on Linux Mint 21.1. See screenshot below for the issue
![screenshot1](https://github.com/MOARdV/AvionicsSystems/assets/61162037/5374fa65-ec9e-4480-956e-fa19a10d6e34)
![screenshot2](https://github.com/MOARdV/AvionicsSystems/assets/61162037/076798bd-3319-46e7-a75a-8964b7b0e038)
![screenshot3](https://github.com/MOARdV/AvionicsSystems/assets/61162037/77bdb1da-0a69-4e44-bcba-66137beb2be1)
![screenshot6](https://github.com/MOARdV/AvionicsSystems/assets/61162037/dbd5d6f4-472c-47f9-ad0f-86ddf7914eb2)
![screenshot8](https://github.com/MOARdV/AvionicsSystems/assets/61162037/4801bbaa-279b-4376-b728-3cab44126ecc)

**Comment by JonnyOThan** [comment]
@TheSystemGuy1337 does it work with RasterPropMonitor instead of MAS?

**Comment by MOARdV** [comment]
This is may be the same issue as #336 - I don't think I ever updated the shader generation code to account for the Unity update.

**Comment by TheSystemGuy1337** [comment]
Looked at #336, and it is the exact same. Also, what’s MAS? And where can I get it to troubleshoot this issueOn Jun 13, 2023, at 5:35 PM, MOARdV ***@***.***> wrote:﻿
This is may be the same issue as #336 - I don't think I ever updated the shader generation code to account for the Unity update.

**Comment by TheSystemGuy1337** [comment]
Also, I have seen that someone updated PRM (I think they ment RPM) and that fixed their issue, so I'm going to try that, and remove whatever this MAS thing is

**Comment by TheSystemGuy1337** [comment]
Updated RPM, now some text is garbled. We are really ripping and tearing until it is done here. GCC save me now
![screenshot0](https://github.com/MOARdV/AvionicsSystems/assets/61162037/08279279-bde5-4ceb-a0f6-e1dab0e59360)

**Comment by JonnyOThan** [comment]
> Updated RPM, now some text is garbled. We are really ripping and tearing until it is done here. GCC save me now ![screenshot0](https://user-images.githubusercontent.com/61162037/245741195-08279279-bde5-4ceb-a0f6-e1dab0e59360.png)

That issue is https://github.com/JonnyOThan/RasterPropMonitor/issues/103

Seems like this is a dupe.
