### ISSUE TITLE
MAS Control/Autopilot

### ISSUE THREAD

**Issue by DeputyLOL** [MOARdV/AvionicsSystems#46]
I know that this isn't going to be coming anytime soon but.... 
I've been thinking back to the first time I found out about MAS. We were talking about autopilots or autolanding or pilot assistant or crashing, you said you could make a system that could autoland a plane using this "new thing" you were working on. This turned out to be MAS.

Would it be possible to have MAS control pitch, roll, yaw and throttle? It would probably be limited to IVA only.
Maybe we could have a simple autopilot that can hold a heading, speed, Altitude and vertical speed?
Maybe we could have a complex sutopilot that can follow  a flight plan or perform an autoland?
Maybe we could have a MAS flight director?
Maybe MAS limited player input to stop you stalling?
POSSIBILITIES ARE ENDLESS!!!!

**Comment by MOARdV** [comment]
I think allowing MAS to provide control inputs is feasible, but it would *have* to be IVA only - I effectively shut down MAS when you're outside of IVA so it's not chewing up resources when it's not visible.  Anything beyond that (autopilot, for instance) is way outside the scope of MAS.  That would need to be an autopilot mod, or an add-on to MAS.

**Comment by theonegalen** [comment]
It would probably be possible to have the flight plan autopilot using Pilot Assistant integration: you code your prop using Lua to give PA the proper input values at the proper times.

But I know nothing of Lua so this is just a guess.

**Comment by MOARdV** [comment]
> It would probably be possible to have the flight plan autopilot using Pilot Assistant integration: you code your prop using Lua to give PA the proper input values at the proper times.

That's exactly how it'd work.  You could punch in the destination lat/lon, for instance, and press a "go there" button that executes a script that determines the heading and feeds that into PA and switches on the appropriate hold heading mode.

**Comment by DeputyLOL** [comment]
From what i tested with RPM and rapid clicking, pilot assistant can usually handle a constantly (or rapidly) updating input. 
That means it should be capable of course corrections and maneuvering.
And that means it might be capable of performing autolandings.

**Comment by theonegalen** [comment]
Kramax Autopilot, whose code was originally based on PA, has autoland, if the flight plan config is set up correctly. I'm not sure of all the changes, but I know it was significantly changed.

**Comment by DeputyLOL** [comment]
Yeah but i dont think Kramax is being updated as much as pilot assistant. 
Also i dont think Kramax hsa its values open to RPM and it also doesn't do airspeed in knots so thats why i stuck to Pilot Assistant

**Comment by theonegalen** [comment]
Agreed.
