### ISSUE TITLE
MoonSharp Performance (and Garbage Creation) issues

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#5]
Now that I've got MAS working well enough to operate most of an IVA, I'm getting some realistic performance results showing the cost of the MoonSharp Lua interpreter,

With 129 "variables", many of them using the simple "fc.GetVariable()" form, the FixedUpdate takes 1.73ms (with a millisecond-resolution timer - need to see if there is a higher precision option).  That's about 1/10 of the FixedUpdate interval, which means it's too slow.

Strategies to consider:

1) Dynamic scaling of the update.  Right now, MAS updates every variable every FixedUpdate, which makes everything _very_ responsive (other than the yellow-timer lag occasionally).  I could put together a heuristic that 'load balances' the updates by splitting them up into groups, and updating each group in a round-robin fashion.  This will reduce the responsiveness of the variables, but that's been a 'feature' in RPM for a while.

2) Selective use of Lua.  MAS makes every variable a Lua microscript.  If I write a basic parser (yuck), I can decompose a variable and figure out which ones are simple wrappers around callbacks to the proxy classes.  Instead of round-tripping through Lua, I can split the simple cases out and use delegates.  It complicates initializing a variable, but it will cut the cost of updating it, which is the important issue.

3) Dig into the MoonSharp code.  Branch the code and see if I can find where the garbage is being generated.  Get some advice from some of the more C#-savvy modders on where the large !/$ areas are.

Ultimately, I am sure I'll try 1 and 2; there is the additional note that there is only so much I can realistically do, since Lua is an interpreted language, so it will be slower than pure C#.  I suppose there's always trying to do something like learning IL and seeing if I can write a Lua->IL transformation, but that's way down the road when I get bored...

**Comment by MOARdV** [comment]
I found a C# lexer that I can insert into the project, and it looks like it'll suit my needs.  Actually processing the output will be some effort, but the option is now available, at least.

**Comment by Alexustas** [comment]
Ok! I just tested your cockpit. 
It is very cool!
and the strange and unknown feeling when I'm in the cockpit, which was not made by me... )))

here my [ksp.log](https://www.dropbox.com/s/z7wu9fz42j7z2jv/KSP.log?dl=0)
![screenshot256](https://cloud.githubusercontent.com/assets/6713671/17833751/47d7e540-6748-11e6-9abf-96225132da28.png)

I noticed a very rapid periodical yellow flickering on the  MET timer, also periodic short frame freezes (or lags) 

as well as some bug-report
after I did "Revert the start," many caption on the toggle switch broke

![screenshot249](https://cloud.githubusercontent.com/assets/6713671/17833745/357e44c0-6748-11e6-8eb5-574f5f17a7fc.png)
![screenshot251](https://cloud.githubusercontent.com/assets/6713671/17833747/38090798-6748-11e6-86a2-64287da7da32.png)
![screenshot252](https://cloud.githubusercontent.com/assets/6713671/17833748/3afa1686-6748-11e6-9a67-5a41bc6fb84a.png)

**Comment by MOARdV** [comment]
>It is very cool!
and the strange and unknown feeling when I'm in the cockpit, which was not made by me... )))

Thank you. :)))

> I noticed a very rapid periodical yellow flickering on the MET timer, also periodic short frame freezes (or lags)

Okay, that is garbage from the Lua interpreter, I think.  I have ideas for how to make it better, but they aren't easy.

> as well as some bug-report after I did "Revert to launch," many caption on the toggle switch broke

Yes.  I saw that, too.  I have not figured out why it does that.  It does not happen in RPM, so there must be something I do differently in MAS.

**Comment by MOARdV** [comment]
I've had good progress using a 'Lexer' class to help me recognize simple variables that can be computed directly without needing to use Lua.  This improves performance.  Not enough improvement yet to be good enough, but some improvement.

**Comment by MOARdV** [comment]
I've got it implemented well enough that the Yarbrough IVA (as it is currently implemented) goes from about 250 Lua script variables to 95, with the other 155 variables being called directly (no round-trip through MoonSharp).  This change shaved about 1ms from the FixedUpdate time (from about 2.5ms to about 1.5ms) on my system.

I should look into doing the same optimization on for COLLIDER_EVENT actions - many of them could potentially be faster, too (not that it is as big of a problem right now).

**Comment by MOARdV** [comment]
More data ... using the MemGraph / Garbage Collector plugin, I see that using pure Lua calls generates 30-40MB of allocations per sample.  If I use my optimizations, that drops into the mid-20MB range, which is better, but still *bad*.

The allocation rate looks like it scales roughly proportionally with the number of calls or variables involved.  I don't know if there's a reasonable way for me to reduce the number of calls (somehow combining all of the Lua script fragments), or if I can dig through the MoonSharp code and find some low-hanging allocation changes to make, or what.

I also should see about making the Actions use the native code path where possible - less MoonSharp overhead is a good thing.

**Comment by MOARdV** [comment]
Okay, some solid performance metrics from my Yarbrough IVA as it stands currently:

* 118 constant variables (numbers or strings) - 0 overhead per FixedUpdate.
* 318 native variables (delegates / lambda expressions) - 0.23ms/FixedUpdate or 1390 variables/ms (!!).
* 124 Lua script variables (processed via MoonSharp ) - 1.47ms/FixedUpdate or 84.3 variables/ms.

Clearly, the Lua script is incredibly slow (the delegates run 16x faster, although they're also less computationally complex), and it results in a huge amount of memory allocations.  I wonder how tough it'd be to hack MoonSharp so it's not an interpreter, but it's generating IL or something like that.

**Comment by MOARdV** [comment]
Hacking in code that generates one mega-function to update all the variables has no impact on performance and garbage creation - the problem is in Lua interpretation, and not Lua "context" entry/exit

**Comment by nevercast** [comment]
Something like NLua might be a path to consider. Though it's probably not as pretty to use as MoonSharp. NLua is a wrapper around LuaInterface, thus a binding to a much faster interpreter. With that comes all the joys of Marshalling, though it's almost entirely hidden behind helper functions.

It might suit your needs as your needs are not overly complex and you just want an expression evaluator.

**Comment by nevercast** [comment]
Quick edit to my original statement about performance, MoonSharp barely suffers from cross-zone latency since it's purely C#, thus invoking a C# proxy is not nearly as expensive as it is in NLua. I think this means that there are some strong differences between MoonSharp and any LuaInterface implementation and a test case should be implemented to actually measure performance.

As you said, you're needing to evaluate entire scripts.

Caching calls would be to proxy on the Lua side also, essentially memorization on the Lua side. Though I don't know all the C# calls you are making from Lua, nor do I know how immediate their values need to be. I assumed things like Altitude could be evaluated less often, unless you needed to plan a maneuver, then it needs to be precise. 

I'll pull the repo and see if I can just do the swap to NLua, if it doesn't make it any better then it's a path you don't have to investigate yourself.

**Comment by nevercast** [comment]
Means of profiling have become somewhat vague over the years, none of the community tools to assist in profiling have survived the time. I will have to add Enter/Leave calls to all C# functions I care about to profile their execution time. Memory allocation is probably off the table for me.

**Comment by MOARdV** [comment]
Going to close this out - it's an ongoing background task, for the most part.

**Comment by nevercast** [comment]
Fair move. I never made much progress moving to an NLua implementation as the workload in doing so was greater than the time I have available.
