### ISSUE TITLE
Support Trajectories mod

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#50]
It provides a landing predictor that might be an alternative to using MechJeb.  Need a way to control which one gets priority.

**Comment by MOARdV** [comment]
Since I've added a MAS version of the landing predictor -- do I still need Trajectories support?  MAS prediction is not perfect, but is it accurate enough?

**Comment by theonegalen** [comment]
I haven't used Trajectories in a while, but I don't know how accurate the MJ prediction is for atmospheric flight.

**Comment by MOARdV** [comment]
MJ 2.6.1 is a little bit flaky with its predictions.  Sometimes they seem to stop working.  The built-in predictor I added is okay, but it's still not accurate until the lower atmosphere.  I've seen multiple reports that Trajectories causes problems, at least in FAR, because its computations are costly.  I still have not actually looked at the mod myself, since it's currently a ways down on the priority list.

**Comment by MOARdV** [comment]
I think I'm going to pass on trying to integrate this mod - it's got a lot of knobs that can be turned, which means any application of it in an IVA is going to be complex.
