### ISSUE TITLE
MASCamera / MASPageCamera still needs work

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#60]
The camera doesn't stay attached during launch, and scatterer breaks the cameras.

**Comment by MOARdV** [comment]
Scatterer does not seem to play nice with the camera implementation, either.  I need to figure out how to get MAS to cooperate when scatterer is involved.

**Comment by MOARdV** [comment]
When rendering to a MASCamera rentex, and then blitting (with no postprocessing), the resulting image is missing data (black swatches, like some layers did not show up).

**Comment by MOARdV** [comment]
The sky renders too dark from the ground when looking up.  I haven't determined if it's EVE, or reproduces in stock as well.

**Comment by MOARdV** [comment]
Need to detect a camera was separated, and switch to showing the "no camera" image afterwards.

Also need to finish implementing the missing camera effect, instead of clearing the texture to red.

**Comment by Alexustas** [comment]
I see the current values and limits for FOV, pan and tilt of cameras. but I do not understand how to manage it in flight? 

Is it possible to do the following:

We use a special (discrete) control panel for controlling cameras, where we first select the name of the camera we want to control and then change the pan , tilt and zoom settings. 

![bandicam 2017-10-29 17-35-25-175](https://user-images.githubusercontent.com/6713671/32143718-a4494066-bccf-11e7-9348-9798f929cd65.jpg)

And these changes apply to the camera itself, and not to the monitors, as it was in the RPM.

**Comment by MOARdV** [comment]
Camera control is [here](https://github.com/MOARdV/AvionicsSystems/wiki/MASFlightComputerProxy#cameras-category).

For this prop, I think it already will work.  Camera control is applied to the camera, not the monitor.

For "NextCam" COLLIDER_EVENT,
```
onClick = fc.AddPersistentWrapped("%AUTOID%-cameraId", 1, 0, fc.CameraCount())
```

For "PrevCam" COLLIDER_EVENT,
```
onClick = fc.AddPersistentWrapped("%AUTOID%-cameraId", -1, 0, fc.CameraCount())
```

For camera name display:
```
variable = fc.CameraName(fc.GetPersistentAsNumber("%AUTOID%-cameraId"))
```
or, better, if the name is too long
```
variable = fc.ScrollingMarquee(fc.CameraName(fc.GetPersistentAsNumber("%AUTOID%-cameraId")),12, 1)
```

To update camera pan (pan right; use negative number to pan left):
```
onClick = fc.AddPan(fc.GetPersistentAsNumber("%AUTOID%-cameraId"), 1) -- 1 is maybe too big
autoRepeat = 0.1
```

Zoom uses `fc.AddFov`,  tilt uses `fc.AddTilt`.  Right now, I do not have a way to ask the minimum and maximum tilt, pan, and field of view for each camera, but that is easy to add.

**Comment by Alexustas** [comment]
> Camera control is here.
> 
> For this prop, I think it already will work. Camera control is applied to the camera, not the monitor.

It's just wonderful! Thank you!
