### ISSUE TITLE
Context Menu support?

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#63]
Allow a part config to have a configurable context menu toggle button.  The button persists its values, and it can be configured to trigger an event when toggled true, and when toggled false.  The events are MAS events, including Lua scripts.

**Comment by theonegalen** [comment]
OOH. Would this be a MAS PartModule of some kind, where the scripting would go?

**Comment by MOARdV** [comment]
> OOH. Would this be a MAS PartModule of some kind, where the scripting would go?

It'd be a part module that can access scripting, so you can trigger MAS events from outside the IVA view.  I guess that's what you just said worded differently. :)
