### ISSUE TITLE
Image rotation capability

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#64]
Is it possible to add the ability to rotate the image in the IMAGE node setup? 
This will be useful for the animation of the hands of gauge-style instruments

![bandicam 2017-10-30 14-33-41-801](https://user-images.githubusercontent.com/6713671/32164213-98f68e9c-bd80-11e7-83a6-a2f22f84d7b2.jpg)

Or would you recommend using HORIZON node?

**Comment by MOARdV** [comment]
Another update on [DropBox](https://www.dropbox.com/s/vrfi9xd0bg3kuyb/AvionicsSystems-0.10.0b1.zip?dl=0) :).

`rotation` for IMAGE applies rotation in degrees, eg:
```
rotation = fc.Roll()
```
or
```
rotation = fc.GetThrottle() * 180
```

Rotation is around the center of the image.

**Comment by Alexustas** [comment]
> Rotation is around the center of the image.

Can you add a rotation center offset option?
this will help to reduce (almost twice) the size of the images in the case of instrument hands

**Comment by MOARdV** [comment]
> Can you add a rotation center offset option?

I thought maybe you would want that. :)  I will try to add it this week.

**Comment by MOARdV** [comment]
'rotationOffset' is now working.  It is the displacement from the center of the image, in pixels (+X = right, +Y = down).

Same beta on [DropBpx](https://www.dropbox.com/s/vrfi9xd0bg3kuyb/AvionicsSystems-0.10.0b1.zip?dl=0).

**Comment by Alexustas** [comment]
rotation for IMAGE - OK!
rotationOffset - OK!

https://www.youtube.com/watch?v=3GPNBHfRq1Y&feature=youtu.be

**Comment by MOARdV** [comment]
That new MFD looks interesting.  Are the labels on the buttons textures, or are they TEXT_LABEL nodes?

**Comment by Alexustas** [comment]
> Are the labels on the buttons textures, or are they TEXT_LABEL nodes?

On the left side of monitor - TEXT_LABEL
on the right side - poligons (part of monitor 3D-model)

Left side - "fixed" , each button calls the appropriate category (or group) of pages. The list of pages in the selected category is displayed in the upper text line ("Legend"). the string is formed by the script and can exceed the screen resolution, in this case it is divided into two parts and there is an automatic looped scrolling.

The page is selected by pressing the  "PREV / NEXT" rocker button

Right side buttons - "soft" and and they change their functions depending on the selected page

I chose this architecture because of the wide possibilities for scaling the system. I can easily add new pages and have no problems with lack of hot keys
