### ISSUE TITLE
MAS Component / COLLIDER_EVENT masterVariable?

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#67]
is it possible to add a function similar to what the RPM has for  "JSIActionGroupSwitch" module?

**Comment by MOARdV** [comment]
Yes -

Master Variable (master switch):
```
fc.TogglePersistent("MyMasterVariable")
```

Slave Variable (RPM uses masterVariableName, masterVariableRange):
```
fc.SetPersistent("MyPersistent", fc.TogglePersistent("%AUTOID%-switchPosition") * fc.GetPersistentAsNumber("MyMasterVariable"))
```

`MyMasterVariable` is the control variable.  `%AUTOID%-switchPosition` can be used to control the switch position animation.  `MyPersistent` is the variable controlled by the master switch.

Or, if you do not need to track a master switch animation,
```
fc.SetPersistent("MyPersistent", fc.GetPersistentAsNumber("MyMasterVariable"))
```

Or, if the master variable is not a toggle switch, but a data value:
```
fc.SetPersistent("MyPeristent", fc.Between(fc.GetAltitude(), 0, 100))
```

Something like one of those?

**Comment by Alexustas** [comment]
Sorry, I probably did not accurately express my idea. I need a way to deactivate the COLLIDER_EVENT. That is, if the variable is inside the range, then this COLLIDER_EVENT works as it should. If not, it is ignored and does nothing.

**Comment by Alexustas** [comment]
It is more like "stateVariable" in the Transfer Actions

**Comment by MOARdV** [comment]
Ah, okay.  I thought I had that already, but it looks like I forgot.  I will add it.

**Comment by Alexustas** [comment]
Excellent!
thank you!

**Comment by MOARdV** [comment]
Added to [DropBox](https://www.dropbox.com/s/vrfi9xd0bg3kuyb/AvionicsSystems-0.10.0b1.zip?dl=0) beta.
