### ISSUE TITLE
MASMonitor. Re-run startupScript

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#68]
Is it possible to add an action or command to restart all monitors in the current IVA? 

The goal - by pressing one button to force all props having the "MASMonitor" module to execute their startup scripts

**Comment by MOARdV** [comment]
I will try to find a way to do that.

**Comment by Alexustas** [comment]
I began to develop a completely new family of MFDs. The page structure is formed in the startup script and depends on the installed mods (currently only mods) and I want to make different sets of pages for different flight modes. for example, spaceplane - at the beginning and at the end of the flight - it's an airplane, in the middle - a spacescraft, or rover - first it's a spacecraft, and after landing is already wheeled vehicle. For each situation are selected the appropriate sets and design of the pages

**Comment by MOARdV** [comment]
`fc.RunMonitorStartupScript()` - runs 'startupScript' on all monitors in the same IVA.  Returns the number of monitors that had 'startupScript' defined.

On [DropBox](https://www.dropbox.com/s/vrfi9xd0bg3kuyb/AvionicsSystems-0.10.0b1.zip?dl=0) - same link as the rotationOffset and everything else.
