### ISSUE TITLE
Prograde heading

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#70]
Is it possible to obtain the value of the heading of the velocity vector, regardless of the orientation of the ship and its heading?

![progradeheading01](https://user-images.githubusercontent.com/6713671/32566985-a136ab0c-c4db-11e7-9356-bd1052b4528f.png)
![progradeheading02](https://user-images.githubusercontent.com/6713671/32566986-a15d6562-c4db-11e7-85c4-b08fe55c74ec.png)

**Comment by MOARdV** [comment]
`fc.HeadingPrograde()`, now on [DropBox](https://www.dropbox.com/s/5lrxoiyjk96su34/AvionicsSystems-0.11.0b1.zip?dl=0)

**Comment by Alexustas** [comment]
it works perfectly. Thank you!
