### ISSUE TITLE
"animateExterior" option for "ANIMATION" and "ANIMATION_PLAYER" nodes

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#72]
The same thing like in the RPM.

**Comment by MOARdV** [comment]
Now on [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0), but not tested - I do not have a MAS IVA with animations on the part.

Use `externalAnimation` instead of `animation` for exterior animation.
