### ISSUE TITLE
Terrain height and the slope angle at a point with the specified coordinates

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#73]
Is it possible to obtain data on the terrain height and the slope angle at a point with the specified coordinates?

**Comment by MOARdV** [comment]
I can provide altitude from latitude and longitude.  I am still looking for slope angle.

**Comment by MOARdV** [comment]
Available on [DropBox](https://www.dropbox.com/s/5lrxoiyjk96su34/AvionicsSystems-0.11.0b1.zip?dl=0).

`fc.BodyTerrainHeight(id, latitude, longitude)` and `fc.BodyTerrainSlope(id, latitude, longitude)`.

If `id` = -1, it is for the current body. You can also use a name, such as "Kerbin", or a planet ID (see [Body](https://github.com/MOARdV/AvionicsSystems/wiki/MASFlightComputerProxy#body-category) section of documentation).

Slope is computed by sampling elevation 5m from the location in each cardinal direction (north, south, east, west).

**Comment by Alexustas** [comment]
> fc.BodyTerrainHeight(id, latitude, longitude)

does the calculation of this function require large machine resources and can it generate lags if we calculate many such functions simultaneously?

**Comment by MOARdV** [comment]
> does the calculation of this function require large machine resources and can it generate lags if we calculate many such functions simultaneously?

It requires 4 calls to query terrain height, plus some simple vector maths (multiply / add).  I do not know how expensive the terrain height query is.  I guess we will find out. :)

**Comment by Alexustas** [comment]
I want to use this function to build a schematic section of the surface in the landing zone that is part of the landing assistance system

![bandicam 2017-11-10 23-07-36-024](https://user-images.githubusercontent.com/6713671/32672554-4b205946-c66d-11e7-8bcf-6f83cc8a228e.jpg)

so far I have stopped at 11 measurement points

**Comment by MOARdV** [comment]
> so far I have stopped at 11 measurement points

11 measurement points + slope = 15 total queries for height.  I would think that is not too bad for performance.

That is a very cool design.

**Comment by Alexustas** [comment]
https://youtu.be/p7LTYFDZ3gA

"fc.BodyTerrainHeight" works fine, but "BodyTerrainSlope" is unstable, sometimes the slope value is no longer calculated and returns zero

**Comment by MOARdV** [comment]
> but "BodyTerrainSlope" is unstable, sometimes the slope value is no longer calculated and returns zero

Very odd.  I will investigate.  Are there any unusual messages in the log?

**Comment by Alexustas** [comment]
>  Are there any unusual messages in the log?

No.

I edited my script and so far I could not reproduce this issue.

But
Look at this. I landed my ship west of the KSC. the terrain looks  acceptable flat

![screenshot29](https://user-images.githubusercontent.com/6713671/32698332-a6812cbc-c7c5-11e7-9782-162d31b7e673.png)
![screenshot30](https://user-images.githubusercontent.com/6713671/32698351-2a543c5a-c7c6-11e7-9910-150e62573433.png)


But slope value is very large

![screenshot28](https://user-images.githubusercontent.com/6713671/32698347-0cfa3d30-c7c6-11e7-8175-507c9c02dee0.png)

my script:

```
...
function ASET_LandAssistPointHeight(MonitorID)
	
		local HDG = fc.HeadingPrograde()
		local D = fc.GetPersistent(MonitorID .. "_LandAssistDistance")
		local st = fc.GetPersistent(MonitorID .. "_LandAssistDistStep")
		
			for i=1,11 do
			
				local h = fc.BodyTerrainHeight(-1, nav.DestinationLatitudeFromVessel(D-st*5+st*(i-1), HDG), nav.DestinationLongitudeFromVessel(D-st*5+st*(i-1), HDG))
			
				fc.SetPersistent(MonitorID .. "_LandAssistHight_" .. i, h)
				
				if i == 6 then 
				
					local slope = fc.BodyTerrainSlope(-1, nav.DestinationLatitudeFromVessel(D, HDG), nav.DestinationLongitudeFromVessel(D, HDG))
					
					fc.SetPersistent(MonitorID .. "_LandAssistSlope", slope)
					
				end
			end
			
		return fc.GetPersistent(MonitorID .. "_LandAssistHight_6")

```	
	end

**Comment by Alexustas** [comment]
and further. 
It looks like both functions do not "see" objects on the surface (such as structures or a runway). this is not a big problem, but it would still be just fine if we had a height and a slope with regard to artificial structures

**Comment by MOARdV** [comment]
Yes, the query only checks the surface of the planet.  Detecting structures / anomalies will be more complex, and I will need to find out how I can do that.

I will try to investigate today to understand if my math is incorrect for the slope.  The altitude samples used for the slope are +/-5m from the center, so a 16.6 degree slope is a rise of 2.8m over a distance of 10m.

**Comment by Alexustas** [comment]
"BodyTerrainSlope" shows a slope of 1.4 degrees on the launch pad

**Comment by Alexustas** [comment]
https://youtu.be/2MubsoDNkTI

this is a long 30 vin test flight. 
to save your time, take a look at:

02:20 - 04:00
05:14 - 05:24
20:34 - 23:00
25:40 - 26:57
27:00 - 27:52
30:32 - 31:20

it seems that the calculation of the slope for some reason stops or returns zero in some areas

**Comment by MOARdV** [comment]
Updated the beta on [DropBox](https://www.dropbox.com/s/5lrxoiyjk96su34/AvionicsSystems-0.11.0b1.zip?dl=0) to use PQS Controller queries instead of CelestialBody.TerrainAltitude.  It looks like it gives correct answers, and I did not see it stop working when I tested it for ten minutes.

**Comment by Alexustas** [comment]
Now the "BodyTerrainSlope" values look more correct and do not freeze

> EDIT: It is possible the query will see buildings, since it is using PQS controller.

no, looks like "fc.BodyTerrainHeight" still does not see the buildings ((((

**Comment by Alexustas** [comment]
can you add an old-fashioned fc.SlopeAngle(), **exactly the same** as "SLOPEANGLE" in RPM?

**Comment by MOARdV** [comment]
> EDIT: or are they already exactly the same?

No, they are not the same.  The old RPM "SLOPEANGLE" uses a ray-cast directly below the vessel.  I can make "fc.SlopeAngle" for directly beneath the vessel, exactly the same as "SLOPEANGLE".  That will be easy.

> "fc.BodyTerrainHeight" still does not see the buildings

I will search for a way to see buildings, if it is possible.

**Comment by Alexustas** [comment]
offtopic, but I do not want to open a separate topic for this.

functions "fc.LandingLatitude ()" and "fc.LandingLongitude ()" works only with MJ or if there is no MJ used some internal calculation engine?

**Comment by MOARdV** [comment]
>  works only with MJ

Yes, landing latitude / longitude only works with MJ, and when MJ landing predictor is switched on `mechjeb.ToggleLandingComputer()`.  I can make an internal calculation, but it will be bad when flying in atmosphere.

**Comment by Alexustas** [comment]
>  I can make "fc.SlopeAngle" for directly beneath the vessel, exactly the same as "SLOPEANGLE".

>  I can make an internal calculation, but it will be bad when flying in atmosphere.

> I will search for a way to see buildings, if it is possible.

Yes, yes and yes, please )

and "SPEEDATIMPACT" and "LATERALBRAKEDISTANCE" ))

**Comment by Alexustas** [comment]
and a little more offtopic.

"variable" in the COLLIDER_EVENT action evaluated (or computed) only when it's clicked or permanently in each update?

**Comment by MOARdV** [comment]
> "variable" in the COLLIDER_EVENT

`variable` in COLLIDER_EVENT node controls when the collider is enabled or disabled.  It is always evaluated when the variable changes.

**Comment by Alexustas** [comment]
ie, once calculated variable is not evalued until it changes?

That's the point. The easiest way to find out whether a particular page on MFD is currently selected is to compare its name and category. So, if the category and name match the specified category and the name, COLLIDER_EVENT is enabled. But we get two string comparisons and this can be expensive for performance. or not?

**Comment by MOARdV** [comment]
All variables are evaluated every FixedUpdate in Unity, unless they are a constant, such as "5".  If you search the KSP.log for "[MASFlightComputer]", you will find a text such as this:
```
[LOG 12:17:59.549] [MASFlightComputer] 1329 variables created: 209 constant variables, 1092 native variables, and 28 Lua variables
[LOG 12:17:59.550] [MASFlightComputer] FixedUpdate native average = 1.59ms/FixedUpdate or 685.1 variables/ms
[LOG 12:17:59.550] [MASFlightComputer] FixedUpdate Lua    average = 0.24ms/FixedUpdate or 116.7 variables/ms
```
which shows how many variables there are, and how much time it takes to update them.  In my IVA, there are over 1100 variables right now that are checked every FixedUpdate.

One thing I do is use two collider events.  One event sets the monitor name, the other sets a page number. 
```
	COLLIDER_EVENT
	{
		name = A button
		collider = button_A
		onClick = fc.SetPersistent("%AUTOID%", fc.GetPersistent("%AUTOID%-A"))
		sound = Squad/Sounds/sound_click_tick
		volume = 1
	}
	COLLIDER_EVENT
	{
		name = A button
		collider = button_A
		onClick = fc.SetPersistent("%AUTOID%-btn", 8)
	}
```
If I need to test if a page is visible, I can call `fc.GetPersistentAsNumber("%AUTOID%-btn")`

**Comment by Alexustas** [comment]
but in my case a set of pages is formed when the monitor starts and depends on the installed mods and the selected mode. so in one case the page can have a number, say "8", and in the other (if the mod is not installed) it will have the number "7". Because the page related to the mod and located in the middle of the list will be deleted at startup.
