### ISSUE TITLE
More dynamic compound values

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#74]
For LINE_STRING, I worked out how to generate compound values (R, G, B, A) or (x, y) using variables for each entry.  I should extend support for that to some other configuration fields in MASMonitor.

**Comment by MOARdV** [comment]
Note that `range` in almost every use should be updated - it currently uses a `string.Split(',')`, which is spoofed by multi-parameter methods.

**Comment by MOARdV** [comment]
Remaining objects that have fixed RGBA colors that could use dynamic colors:

- [ ] MASActionColorShift
- [ ] MASActionTextLabel
- [ ] MASPageLineGraph

**Comment by MOARdV** [comment]
Should I change MASPageLineGraph to allow different start and end colors for LINE_GRAPH?  If I make that change, `sourceColor` will be renamed `startColor`, similar to ELLIPSE.

**Comment by Alexustas** [comment]
> allow different start and end colors for LINE_GRAPH

I personally do not see this as a great necessity

**Comment by Alexustas** [comment]
Is it possible to make a graph whose color depends on the values of the input variable?
![bandicam 2018-04-10 00-24-18-213](https://user-images.githubusercontent.com/6713671/38518341-09cae5a6-3c56-11e8-831c-97f12e734e10.jpg)

**Comment by MOARdV** [comment]
> Is it possible to make a graph whose color depends on the values of the input variable?

It is possible, but it would be very costly to update, because each segment of the graph would have to be a separate LineRenderer (with its own gameObject). LineRenderer only allows me to set start and end color, not change colors in the middle.

**Comment by Alexustas** [comment]
OK. Thank you for the clarification

Just some thinking. 
Since I'm doing video editing and compositing, I could do this as follows:

![bandicam 2018-04-10 01-19-59-037](https://user-images.githubusercontent.com/6713671/38521094-15065d80-3c5e-11e8-821e-c25c392cd6fb.jpg)

A simple combination of color channels from two sources. But I have no idea how this can be done on the game engine

**Comment by Alexustas** [comment]
Or more easy way if you need black background

![bandicam 2018-04-10 01-36-40-545](https://user-images.githubusercontent.com/6713671/38521622-a9ca8062-3c5f-11e8-943c-c9c418c87ad5.jpg)

**Comment by MOARdV** [comment]
It is easy to composite with two textures - very simple shader for me to write.  I can think of a way to make it work by drawing the lines onto a render texture that I composite with the R, G, B color texture.  I think it would have to be a different component - not LINE_GRAPH, because it would be almost completely different.

**Comment by MOARdV** [comment]
TEXT_LABEL is done - I think that is the last of them.

This allows control panel backlights to have "night mode" and "day mode" by changing the activeColor using variables.
