### ISSUE TITLE
NAVBALL node not rendered

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#77]
page config:

```
MAS_PAGE
{
	name =  ASET_MFD2302_MFD_FONTS_TEST	

// NAVBALL (NODE) ================================================================
	NAVBALL
	{
		name = PFD navball
		model = JSI/RasterPropMonitor/Library/Components/NavBall/NavBall
		texture = JSI/RasterPropMonitor/Library/Components/NavBall/NavBall000
		position = 519, 288
		size = 320, 320
		//opacity = 0.9
		color = 255, 255, 255, 255
		//variable = fc.GetBrakes()
		//range = 0.5, 1.5
	}	
}
```
result

![bandicam 2017-11-16 05-10-40-714](https://user-images.githubusercontent.com/6713671/32867073-d3bea348-ca8c-11e7-929f-286f2613ac81.jpg)

RPM installed.
The same issue with ASET Navball model and texture

**Comment by Alexustas** [comment]
LOG

https://www.dropbox.com/s/h5nu67h7m59jqvi/KSP.log?dl=0

**Comment by MOARdV** [comment]
I spent time this morning trying to understand what is happening.  I can confirm that the camera that looks at the navball works, because I can tell it to clear everything to green and I get a green rectangle.  I also see the pre-render callback working, so I am setting up everything that needs to be drawn.  I do not know why it is not working now, although I have not tested it since last year.

**Comment by Alexustas** [comment]
can this be a shader problem?

**Comment by MOARdV** [comment]
> can this be a shader problem?

It is possible.  It used to work, but I will try a different shader.

**Comment by Alexustas** [comment]
offtop.
it looks like you mixed up the of buttons for "Radial In" and "Radial-out" in your cockpit. 
"Radial In" actually sets the "Radial Out" mode  and vice versa

**Comment by MOARdV** [comment]
NAVBALL now working on [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0).

**Comment by Alexustas** [comment]
Prograde and Retrograde markers looks yellowish-green, can you make them clear yellow 
(255, 255, 0 ,255)? or it can be changed in the config of NAVBALL node?

![bandicam 2017-11-26 02-12-02-768](https://user-images.githubusercontent.com/6713671/33234868-463be52e-d24f-11e7-85d5-77f082f1cfcf.jpg)

**Comment by MOARdV** [comment]
Yes, I will update to yellow.

**Comment by Alexustas** [comment]
MANEUVER icon is kind of "deep rose" color

![bandicam 2017-11-28 05-28-28-079](https://user-images.githubusercontent.com/6713671/33296401-4aaabf2c-d3fd-11e7-961f-3bd3d2f049c1.jpg)

can you make them clear blue, please?

**Comment by Alexustas** [comment]
I did not notice it right away, but there are other problems with icons and colors, 
watch this video

https://youtu.be/9t1V6DFZtcQ

**Comment by MOARdV** [comment]
Correct icons and colors for navball.  I will add the ability to scale the icons, but there are some other bugs with the Navball to fix, first (all nav icons are drawn on every navball!).  Also updated the MFD2 (ASET 60x30 MFD) in Yarbrough IVA on [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0) to show how to add a "back" option using softkey.
