### ISSUE TITLE
Request. Monitor Node - Ground track of vessel orbit

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#81]
just a curve and nothing else that displays the track of the ship's orbit on the flat map of the current body

![bandicam 2017-11-18 02-25-37-644](https://user-images.githubusercontent.com/6713671/32969831-58644004-cc08-11e7-9ec1-5af82d10782b.jpg)

Parameters of the node:
- position of the rectangle on the screen 
- its width in pixels, since the proportion of the rectangle is fixed and equal to 2: 1.
The left border of the rectangle is the longitude -180 degrees, the right is the latitude of 180 degrees and so on. the rectangle itself is transparent so that it is possible to place an image under it (a grid or a primitive, rough map

![bandicam 2017-11-18 02-38-04-199](https://user-images.githubusercontent.com/6713671/32970149-8fdcc7bc-cc09-11e7-8d36-5719f48edaf3.jpg)

- curve property (thickness, color, texture, number of vertex?)
- variable (turn on/off node)

the main function is to give a quick presentation to the pilot where he is and what the current orbit looks like without any third-party add-ons . no zoom, no auto-scroll, no icon (the vessel icon can be added using some text symbol and shifting it along X and Y using ship coordinates)

As an option, the possibility of displaying the orbit not of the vessel but of the target vessel

**Important**. If the orbit crosses the surface of the planet, the curve should break, just like it does in ScanSat

concomitant request

I have long wanted to be able to display the terminator line on the map

![bandicam 2017-11-18 02-51-16-652](https://user-images.githubusercontent.com/6713671/32970574-6695d8ce-cc0b-11e7-8ecf-9762a58db17e.jpg)

What a plan. 
I can use HORIZONTAL_STRIP Node, which will scroll the texture over the map image. all we need is a variable-driver . such a variable might be the longitude of the noon (subsolar point) but, unfortunately, I have no idea how to calculate it in the game

**Comment by MOARdV** [comment]
> unfortunately, I have no idea how to calculate it in the game

I should be able to compute this.  All of the information is available, all I have to do is find the correct transforms and do the math,

**Comment by MOARdV** [comment]
Additional feature 1: ground track of target vessel / moon orbit (if the target is in orbit).

**Comment by MOARdV** [comment]
`fc.BodySunLongitude(object id)` is available in the next update.

**Comment by Alexustas** [comment]
Additional feature 2 :-)

Orbit after maneuver completion

**Comment by MOARdV** [comment]
Idea 1 for node:
```
GROUND_TRACK
{
  name = My Ground Track
  position = 0, 0
  width = 1024
  lineWidth = 5
  vertexCount = 64
  vesselColor = 0, 255, 0, 255
  targetColor = 255, 0, 255, 255
  maneuverColor = 0, 255, 255, 255
  variable = ShowHideDecision()
}
```
If 'targetColor' exists, target orbit track draws if there is a target.  If no 'targetColor', also no target orbit track.

Same with 'vesselColor' and 'maneuverColor'.

Idea 2 for node:
```
GROUND_TRACK
{
  name = My Ground Track
  position = 0, 0
  width = 1024
  lineWidth = 5
  vertexCount = 64
  color = 0, 255, 0, 255
  texture = Ground/Track/Texture
  track = VESSEL // or TARGET or MANEUVER
  variable = ShowHideDecision()
}
```
I think idea 2 is more flexible, since it can have different 'variable' and different 'texture' for each track type,  It will also be easier for me to write, but also requires 3 GROUND_TRACK nodes to have vessel orbit, target orbit, and after-maneuver orbit.

**Comment by Alexustas** [comment]
I agree, idea 2 is more flexible, but on the other hand, I'm sure that I will want to display all the trajectories that are available and I will not hide them

**Comment by MOARdV** [comment]
One more change: left side longitude will be configurable.  I have been using a Kerbin map that scrolls so the vessel is always in the center.  Default will be -180, but it can be variable

**Comment by MOARdV** [comment]
[GROUND_TRACK](https://github.com/MOARdV/AvionicsSystems/wiki/MASMonitor#ground_track) preview on [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0).  It is not perfect, yet: if `size` is < screen width, you will see the ground tracks that do not fit into `size`.  Many other small changes, too (I will list all changes in Issue #95 )

**Comment by Alexustas** [comment]
I noticed an unclear behavior of the `fc.BodySunLongitude(object id`) function

please watch this video:
https://youtu.be/dTENmzv9GI8

**Comment by MOARdV** [comment]
Ah - I forgot a check to ensure the vector is pointing towards the sun, or away from the sun.

**Comment by MOARdV** [comment]
Fixed on [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0)

**Comment by Alexustas** [comment]
Now it works just fine

https://youtu.be/LOwNzUG2xVQ

**Comment by MOARdV** [comment]
Ground track lines fixed so they stay inside their bounds at [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0).  Also updated the MAS MFD2 with a resource page that has player-controlled resource gauges.
