### ISSUE TITLE
MAS MONITOR IMAGE Node improvements 

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#82]
I would very much like to have the following improvements for the "IMAGE" node:

- **_position_** should not be fixed. X and Y must be able to change depending on the specified variables, independent of each other (for example position = fc.SurfaceForwardSpeed(), fc.SurfaceLateralSpeed()

- **_Color_** The ability to change the color of the image and switch colors, depending on the variable, by analogy with "COLOR_SHIFT" action.

**example 1:**
source image (simple black rectangle)

![bandicam 2017-11-18 20-24-07-019](https://user-images.githubusercontent.com/6713671/32981982-b54b17b6-cc9e-11e7-9700-bfdff0b0850d.jpg)

```
passiveColor = 60,60,60,255
activeColor = COLOR_ASET_ORANGE
colorVariable = fc.EngineFlameout()
```
passive
![bandicam 2017-11-18 20-31-27-399](https://user-images.githubusercontent.com/6713671/32982019-89923338-cc9f-11e7-92d2-c6ba12c9aa1e.jpg)

active
![bandicam 2017-11-18 20-32-22-055](https://user-images.githubusercontent.com/6713671/32982022-9ebea76e-cc9f-11e7-962d-2b19007bc6e4.jpg)
this can be extremely convenient for creating on-screen warning lights

**example 2:**
source image
![bandicam 2017-11-18 20-38-43-719](https://user-images.githubusercontent.com/6713671/32982074-82406040-cca0-11e7-80cc-ca3d125b9ba1.jpg)

```
passiveColor = COLOR_ASET_GREEN
activeColor = COLOR_ASET_RED
colorVariable = ASET_Function()
```
passive
![bandicam 2017-11-18 20-38-16-969](https://user-images.githubusercontent.com/6713671/32982094-bb84099c-cca0-11e7-9213-aae7fe9f3d11.jpg)

active
![bandicam 2017-11-18 20-38-21-922](https://user-images.githubusercontent.com/6713671/32982095-bda9ee80-cca0-11e7-868f-d744e71ec6b7.jpg)

I know that the same thing can be done now, by creating two images and adding nodes, but this greatly increases the number of used textures and number of nodes on the page

- **_Image Tiling_** (or UV Tiling)
source image (128x128)
```
size = 128,128
tiling= 1,1
```
![bandicam 2017-11-18 20-55-44-039](https://user-images.githubusercontent.com/6713671/32982242-16ca0200-cca3-11e7-8e61-bbaf44887800.jpg)

```
size = 256,128
tiling= 1,1
```
![bandicam 2017-11-18 20-56-01-163](https://user-images.githubusercontent.com/6713671/32982257-61c5f912-cca3-11e7-9902-5d495b263ca6.jpg)

```
size = 256,128
tiling= 2,1
```
![bandicam 2017-11-18 20-56-21-830](https://user-images.githubusercontent.com/6713671/32982260-6e397494-cca3-11e7-9fbe-d3a22276fff7.jpg)

```
size = 256,128
tiling= 2,2
```
![bandicam 2017-11-18 20-56-34-373](https://user-images.githubusercontent.com/6713671/32982262-78b4ddfa-cca3-11e7-84e7-bccfaefa063d.jpg)

Both "siz"e and "tiling" must have variables as paremeters

this should be very convenient for drawing various scalable grids

Perhaps it will be more convenient if you just add a new type of Node, something like the "DYNAMIC_IMAGE", and the existing "IMAGE" Node will remain unchanged.

**Comment by Alexustas** [comment]
example of on-screen warning lights

![bandicam 2017-11-18 22-03-54-311](https://user-images.githubusercontent.com/6713671/32982822-64b441a2-ccac-11e7-97f6-da7ed5f42da4.jpg)

![screenshot36](https://user-images.githubusercontent.com/6713671/32982862-f20a8322-ccac-11e7-8997-6a2a390b9b73.png)

**Comment by MOARdV** [comment]
I think these all can be added to IMAGE.  However, the source texture will have to be white, not black.  That way, I can use the existing Unity shaders and change _MainColor instead of needing to write a custom shader that does almost the same thing.

I can make size and position use variables (this will be a little bit of work, but possible), and add a tiling value with default = (1, 1) to scale UV.

**Comment by Alexustas** [comment]
>  However, the source texture will have to be white, not black. 

ok, you better know what source color needed. the main thing is that I should be able to accurately control the final color

**Comment by MOARdV** [comment]
Use white textures for maximum options.

Color mode 1:
```
passiveColor = 255 * fc.GetThrottle(), 255, 255 * fc.GetThrottle(), 255
```
Can use variables or numbers for each of R, G, B, A, or use COLOR_ for non-changing color.

Color mode 2:
```
passiveColor = 255 * fc.GetThrottle(), 255, 255 * fc.GetThrottle(), 255
activeColor = COLOR_ASET_ACTIVE_COLOR
colorVariable = SomeVariable()
//colorRange = LowerRange(), 1.0
//colorBlend = true
```
passiveColor and activeColor can use numbers, variables, or COLOR_.  colorVariable, colorRange, and colorBlend same as variable, range, and blend for COLOR_SHIFT.

Is this enough options for color? :-)

**Comment by Alexustas** [comment]
yes, that's enough)
Thank you!

**Comment by MOARdV** [comment]
If `size` is variable, it will expand from the center of the image, or from `rotationOffset` if that value is available.  I do not think I will be able to support other ways of expanding the image, since it becomes difficult to recompute vertex position and image center.

**Comment by MOARdV** [comment]
[DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0): all requested changes, I think.

```
tiling = 1, 1
```
Plus size, position can be variables.

**Comment by MOARdV** [comment]
Should there be `startUV`, similar to the prop [TEXTURE_SHIFT](https://github.com/MOARdV/AvionicsSystems/wiki/MASComponent#texture_shift)?  With `tiling`, this would allow a texture atlas for MFD textures (such as your SAS mode display).

**Comment by Alexustas** [comment]
> Should there be startUV,

Yes, it will be useful.

and much more useful, I believe, can be ` ShiftU` and `ShiftV  `as separate parameters that can be controlled by variables, and warped = true/false. 

and then we get a real SUPER-node :-)

**Comment by MOARdV** [comment]
> warped = true/false.

What do you mean by this parameter?

> we get a real SUPER-node

No, we get a real SUPER-node when can also change textures.  But no, that will not happen - it would be too complex, or it would require special rules for how to use it,

**Comment by Alexustas** [comment]
What do you mean by this parameter?

oops, "**wrap**", not "warp". Sorry )

**Comment by Alexustas** [comment]
it's easier for me to draw than explain in words... quite like a caveman :-D

![bandicam 2017-11-29 20-27-08-713](https://user-images.githubusercontent.com/6713671/33382978-f66d3c62-d543-11e7-9ad8-efc8334f268d.jpg)

**Comment by MOARdV** [comment]
Unfortunately, texture wrap mode options are WRAP (like Wrap = true), or CLAMP, which looks like:

![uvshift](https://user-images.githubusercontent.com/6089493/33525823-8ff3f0e6-d7fc-11e7-8728-c0801c184243.jpg)

I still must verify that I can change the UV mode from WRAP to CLAMP on a single instance of the texture - it might be that if I change it for one use of the texture, it will change it for every instance of the texture, which would not be good.

**Comment by MOARdV** [comment]
I've checked, and UV wrap mode applies per-texture, so if I add a 'wrap' option, I think it will not work.

**Comment by Alexustas** [comment]
I do not think that we will often need to use the same texture with different modes

**Comment by MOARdV** [comment]
I can add the capability.  I will also add a warning about how it affects every use of that texture.

**Comment by MOARdV** [comment]
Added `wrap = false` / `wrap = true` support to next beta.
