### ISSUE TITLE
Question. Alphabetic keyboard

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#84]
I'm currently working on a prop for user input. And I need to decide whether to limit myself to a numeric pad or I need to add an alphabetic keyboard. What do you think, in the future may need the ability to enter letters in the MAS? even theoretically

**Comment by MOARdV** [comment]
Already possible: [see](https://github.com/MOARdV/AvionicsSystems/wiki/MASFlightComputerProxy2#fcappendpersistentstring-persistentname-string-addon-double-maxlength)

`fc.AppendPersistentString(persistentName, addon, maxLength)` -
* **persistentName**, same as every other persistent.
* **addon**, what to append to the persistent.
* **maxLength**, maximum length of the persistent string.  If the string is already longer than this length, new letters are ignored.

So, for letter 'A': `fc.AppendPersistentString("SomeTextBuffer", "A", 16)`

`addon` can be a single letter, like this example, or it can be words.

I have not added a "delete last character" function yet, but it is not difficult to add.

**Comment by Alexustas** [comment]
I asked not about the **possibility** of entering letters, but about the **need to have** such an opportunity for any application. you as a developer of MAS know any application now or in the future for the **alphabetic keyboard**  in MAS?

By the way, you probably have not seen my last video
https://youtu.be/ih3uP4iYhEs

**Comment by MOARdV** [comment]
Ah, I misunderstood.  Does MAS need an alphabetic keyboard, or will it need one?  No.  I can not think of a reason why it would be required for MAS.  I think the kOS mod could use a keyboard, but I have never uses that mod, so I do not plan to add support for it.

What is strange about the video is that the conversion of text to numbers is that C# converts the strings to numbers.  MAS gets the persistent variable as a string of text, and it asks C# "Convert this to a number".  And this appears to be how C# replies.  I will do some more testing, in case there is a bug in my code, but it is not complicated.

**Comment by Alexustas** [comment]
I specifically followed exactly this conversion result to exclude any possibility of a script error and the appearance of Exceptions in the game. I achieved exactly what I wanted

**Comment by Alexustas** [comment]
my script

```
function ASET_PositveNumInput(s,current,maximum)

local num=1
local input={}
local output = current

if maximum == -1 then maximum = 10000000000000 end

for w in string.gmatch(s, "[+-]?%d+") do
    input[num] = w
	num=num+1
end

	if input[1] ~= nil and math.abs(tonumber(input[1])) <= maximum then

		if input[2] == nil then 
			output = math.abs(tonumber(input[1])) 
		else
		
			if tonumber(input[2]) <= 0 then 
				input[2] = string.sub(input[2], 2, -1) 
			end
			
			temp_output = math.abs(tonumber(input[1] .. "." .. input[2]))
			
			if temp_output <= maximum then output = temp_output end			
		end	

	end		

	return output
end
```

that would not click the user, the script will return only one sequence of digits or two sequences of digits, separated by a decimal point. and at the same time compare the resulting number with the maximum allowed value

**Comment by Alexustas** [comment]
> No. I can not think of a reason why it would be required for MAS.

I just do not want the new prop repeated the fate of the old kOS terminal. I created it at Miharan's request to work with the kOS, but since kOS support was never provided, it all turned out to be a waste of space on the instrument panel and a bunch of unnecessary colliders in the IVA

**Comment by MOARdV** [comment]
Okay, I see that you wrote your own conversion from string to number.  That is why it works that way.

I wrote the persistent string code so you could call `fc.AppendPersistentString()` several times to create a string, and then call `fc.GetPersistentAsNumber()` to convert it to a number with no exceptions.  If a string is not a valid number, 0 is returned.  It is not a robust as your approach - all it does is ask C# to convert a string to a number.

**Comment by Alexustas** [comment]
since  I got the answer to my question, I close this issue. Thank you.
