### ISSUE TITLE
Redesign MASMonitor button routing

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#85]
One issue that's come up now that I have MASMonitor working, and the RPM bridge modules enabled, is routing keypresses.  I don't really have a way to say "if this page is visible, these buttons should do this".  I should add event handlers to MAS_PAGE and MASMonitor, once I figure out how that should work.

Unfortunately, that means doing a lot of rework on monitors. :(

**Comment by MOARdV** [comment]
This would be for things like up/down arrows, Enter, Esc, Next/Prev, etc.  The idea is to make them soft keys that MASMonitor could forward to the appropriate event consumer that is part of the active page.

**Comment by Alexustas** [comment]
Is it possible to do something like this?
```

COLLIDER_EVENT
{
..
onClick = rpm.DPAI_RPM.nextbutton()
..
variable = [some indication that the DPAI page is open]
}
```

**Comment by Alexustas** [comment]
or

`onClick = rpm.globalButton(5)`

**Comment by MOARdV** [comment]
> `onClick = rpm.globalButton(7)`

Something similar to this is what I have in mind.  And each page that wants to see those events will need to have a way to receive the button.  What is tricky is how to route the event.  The global button can not truly be global.  Probably have to be something like `onClick = fc.MonitorSoftKey('%AUTOID%', 7)`

I am still trying to think about how to design it.

**Comment by MOARdV** [comment]
I have an idea how this should work.

`fc.SendSoftkey(monitorName, softkeyNumber)`: Find the monitor who has `monitorID` the same as monitorName.  Send it the softkey number.

Add to MAS_PAGE: `softkey = number, action`, which can be listed more than one time.  If the softkey number is in this list, then the `action` will be called.  If the number is not on this list, the number will be forwarded to the page elements.  The first one that sees it can process it.  Right now, only RPM_MODULE cares about softkeys.  So, `buttonMapping` in RPM_MODULE will go away.

Example MASComponent for ALCORMFD40X20:
```
COLLIDER_EVENT
{
	name = NEXT button
	collider = buttonR9
	onClick = fc.SendSoftkey("%AUTOID%", 7)
	sound = Squad/Sounds/sound_click_tick
	volume = 1
}
```

Example MAS_PAGE:
```
MAS_PAGE
{
  name = MAS_ALCOR_MFD_A_Launch
  softkey = 7, fc.SetPersistent("%AUTOID%", "MAS_ALCOR_MFD_A_Land")

  ...
}
```

When the "NEXT" button is pressed, if MAS_ALCOR_MFD_A_Launch is the active page, it will change the page to the landing page.

For the SCANsat page, which does not have `softkey = `, instead the page will ask each module if it wants to use softkey 7.  The `RPM_MODULE` component will use it, and it will send it to the JSISCANsatRPM module.

I think this change allows RPM modules to use softkeys without the complex `buttonMapping` they have right now, plus it allows every page to have custom softkey behavior by added `softkey = ` to MAS_PAGE.

**Comment by Alexustas** [comment]
looks interesting. most likely I did not fully understand the description of the process, but when I see the new working configuration of your MFD, I think everything will fall into place in my head.

**Comment by MOARdV** [comment]
Beta updated on [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0).

Look at COLLIDER_EVENT for the buttons on the left and right side of the MFD in MOARdV/MAS_ASET/ALCORMFD40x20/MAS_ALCOR_MFD1.cfg for how to send the soft key events.

MOARdV/MFD/MFD1_Pages.cfg pages for MAS_ALCOR_MFD_A_Launch and MAS_ALCOR_MFD_A_Land show how to have custom softkeys for a page.  And notice that RPM_MODULE is less complex for SCANsat and DPAI in that same file.

I will update documentation, probably tomorrow.  I need to explain how it works better for the wiki.

**Comment by Alexustas** [comment]
Is it possible to add a variable for the SoftKey function? Very often I need that not only the necessary page is active, but also the additional conditions are met

**Comment by MOARdV** [comment]
It is possible to apply conditions in the script that the softkey executes on a page.  Or do you mean to add a variable to fc.SendSoftkey?

**Comment by Alexustas** [comment]
It's true. I can always call a script instead of a direct command. so never mind )
