### ISSUE TITLE
MORSE_AUDIO MASComponent

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#87]
Originally, I was going to implement the Morse code audio generator as part of the navigation module, but I think it would be better to make it a MASAction component, like a special version of the AUDIO node, but it can generate code for a string.

That is, instead of `sound` like AUDIO has, it would take a variable, such as `nav.GetNavAidIdentifier(radioId)`.  When the variable changes, it would stop the current audio, and play the new one.  This allows it to work for radio navigation, but also for any other Morse code application.

**Comment by Alexustas** [comment]
Note that the ID is broadcasted at an interval of approximately 30-40 seconds

**Comment by Alexustas** [comment]
offtop. I am also very interested in the implementation of the 
[fc.PlayAudio(string sound, double volume)](https://github.com/MOARdV/AvionicsSystems/wiki/MASFlightComputerProxy2#fcplayaudiostring-sound-double-volume) 

if I understand correctly, this makes it possible to play the sound inside the script

**Comment by MOARdV** [comment]
> Note that the ID is broadcasted at an interval of approximately 30-40 seconds

That may be more complex.  But, this is good to know, so maybe I can make it work correctly the first time. :-)

> if I understand correctly, this makes it possible to play the sound inside the script

Yes, it will allow any sound to play in a script.  Maybe it is time I make the new audio features work. :-)

**Comment by Alexustas** [comment]
So that you know.
In real life, the moment of transmitting of the identifier is determined by the station. so you can set the radio and wait 20-30 seconds until the station starts transmitting its ID again or vice versa, you will only have time to hear the very end of the broadcast. 

But decide for yourself how this will happen in the game )

**Comment by MOARdV** [comment]
Changing this implementation idea once again.  Instead of a MORSE_AUDIO component, I'll tie it in to the radio navigation code - maybe something like `nav.SetRadioAnnouncer(id, enable)`.

**Comment by MOARdV** [comment]
I have tried to come up with a way to save and restore whether the identifier is enabled, but I do not see a good way to do that.  I am going to add `fc.PlayRadioIdentifier(radioId)` to play it on demand.  It would be possible with some scripting to create an automatic player, but I think building that into MAS is a lot of complication for a small feature.  However, I think I can also add a general-purpose `fc.PlayMorseSeqeuence(string)` that can take any text string and play it as a Morse Code sequence.

**Comment by MOARdV** [comment]
`nav.PlayNavAidIdentifier(radioId, volume, stopCurrent)` and `fc.PlayMorseSequence(sequence, volume, stopCurrent)` now implemented.
