### ISSUE TITLE
Monitor TEXT node variable color

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#91]
I can make textures flash color on the monitor for warnings, but I can't change text.  Why have two texts when all I want to do is change color?

**Comment by Alexustas** [comment]
I use color tags to change the colors of the text. for more complex cases I'm using a script

```
-- MFD G READOUT COLOR ---------------------------------------------------------

	function ASET_MFD_G_Force()
	
		local g = fc.GForce()
		local color = {"[#FFFFFFFF]","[#FFFF00FF]","[#FF7700FF]","[#FF0000FF]"}
				
			if g < 3 then return color[1]			
					
			elseif g >= 3 and g < 6  then return color[2]
			
			elseif g >= 6 and g < 9  then return color[3]
			
			else 
			
				return color[4]
				
			end
		
	end
```

**Comment by MOARdV** [comment]
> I use color tags to change the colors of the text.

True, this is a good option.  And, because monitor text has extra rules because of fixed width, it is not less expensive to use simple color changes.  Maybe I will skip this extra work.
