### ISSUE TITLE
fc.ManeuverNodeDV()

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#92]
I observe a strange behavior of fc.ManeuverNodeDVNormal(), fc.ManeuverNodeDVRadial() and (some times) fc.ManeuverNodeDVPrograde() Methods 

please watch this video:
https://youtu.be/PlG9gisn9ks

**Comment by MOARdV** [comment]
Computation is not perfect.  I made a guess about how to compute those values, and it is not stable.

New features in the next beta: `fc.PeriodCount(double period, double countTo)` will count from 0 to (countTo-1) at the rate of period (if period == 1, then count increases every second, if period == 2, then count increases 2x per second).  I should rename period to frequency to be correct.

Also, [XKCD colors](https://xkcd.com/color/rgb/) using COLOR_XKCD_(name in UPPERCASE).  Some stock KSP colors are included, to.  These are generated automatically from the KSP DLL.  I will update the Named Colors page on the wiki with details of the new colors.

**Comment by Alexustas** [comment]
the `fc.AddManeuverNode(...)` method works fine, the problem is only in the incorrect display of data, because of this it is very inconvenient to adjust the maneuver. 
Once you solve this problem, all IVA-flight fans finally get the much desired Unicorn :D - IVA Maneuver Editor  

https://youtu.be/YC2ZEbdyusQ

**Comment by MOARdV** [comment]
I think I see a Unicorn on the horizon -- [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0) :)

**Comment by Alexustas** [comment]
The Normal vector sign is reversed each time the `fc.AddManeuverNode` method is called

https://youtu.be/ofRanAm6Hb8

**Comment by MOARdV** [comment]
Fixed, same link.  When I simplified the maneuver node processing, I forgot a sign reverse in the AddManeuverNode

**Comment by Alexustas** [comment]
Now it works fine. Thank you!

**Comment by Alexustas** [comment]
Can you, please, add "maneuver burn time" method? or did I just miss it?

**Comment by MOARdV** [comment]
> Can you, please, add "maneuver burn time" method? or did I just miss it?

I do not have one yet.  I can add an approximate burn time.

**Comment by Alexustas** [comment]
and  also:
 - ManeuverNodeTargetClosestApproachDistance
 - ManeuverNodeNextSoI
 - ManeuverNodeNextBody

and some method to get this info

![screenshot49](https://user-images.githubusercontent.com/6713671/33606139-3ae7ce9a-d9de-11e7-9f4c-e1ee922d8946.png)

**Comment by MOARdV** [comment]
I think, but am not certain, that mun periapsis + time will compute correctly with the maneuver node target closest approach distance / time methods (available soon).

**Comment by MOARdV** [comment]
* `fc.ManeuverNodeBurnTime()`
* `fc.ManeuverNodeNextBody()`: Returns number that can be used in fc.Body...() methods.
* `fc.ManeuverNodeNextSoI()`: Same as fc.NextSoI(), but using maneuver node.
* `fc.ManeuverNodeTargetClosestApproachDistance()`: target closest approach distance after maneuver.
* `fc.ManeuverNodeTargetClosestApproachTime()`: target closest approach time after maneuver.
* `fc.ManeuverNodeTimeToNextSoI()`: Time to SoI change after maneuver.

Not very well tested yet, on [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0).

**Comment by Alexustas** [comment]
fc.ManeuverNodeBurnTime() always  return NaN

**Comment by MOARdV** [comment]
It returns good numbers for me.  Engine is on, not off, correct?

**Comment by Alexustas** [comment]
>  Engine is on, not off, correct?

that's what my problem was. It returns the NaN if there are no active engines.

**Comment by MOARdV** [comment]
I will fix it to return 0 if there are no active engines.

**Comment by Alexustas** [comment]
Yes, it will be good. Thank you!

**Comment by Alexustas** [comment]
> I think, but am not certain, that mun periapsis + time will compute correctly with the maneuver node target closest approach distance / time methods (available soon).

When Mun is selected as the target and I do **manual** transfer burn, the value of the Closest Approach  and the new Periapsis are the same. But when I set up a **maneuver**, these values are dramatically different

**Comment by MOARdV** [comment]
> But when I set up a maneuver, these values are dramatically different

Oops - forgot to account for Celestial Body radius for maneuver.  Fixed on [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0).

**Comment by Alexustas** [comment]
I have an error tith last update

```
[ERR 23:41:21.595] [MdVTextMesh] System.OverflowException: Value is too small.
  at System.Math.Abs (Int32 value) [0x00000] in <filename unknown>:0 
  at AvionicsSystems.MASStringFormatter.FormatMET (System.String formatSpecification, Double value) [0x00000] in <filename unknown>:0 
  at AvionicsSystems.MASStringFormatter.Format (System.String formatSpecification, System.Object arg, IFormatProvider formatProvider) [0x00000] in <filename unknown>:0 
  at System.String.FormatHelper (System.Text.StringBuilder result, IFormatProvider provider, System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.String.Format (IFormatProvider provider, System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 
  at AvionicsSystems.MdVTextMesh+TextRow.EvaluateVariables () [0x00000] in <filename unknown>:0 
  at AvionicsSystems.MdVTextMesh.Update () [0x00000] in <filename unknown>:0 
```

**Comment by Alexustas** [comment]
I suspect that this error is related to the hyperbolic trajectory and the value of some of the times ( perhaps time to apoapsis or something like that)

**Comment by Alexustas** [comment]
> I suspect that this error is related to the hyperbolic trajectory ...

video:
https://youtu.be/oKkLMKfCsaQ?t=3m1s

and here very strange readings of closest approach:
https://youtu.be/oKkLMKfCsaQ?t=9s

**Comment by MOARdV** [comment]
Okay, yes, closest approach solver does not do very well with SoI changes.  I will make a new bug to fix it.

Should I make a JSIOrbitDisplay replacement for MAS?

One other question - how hard is it to make Mun and Minmus maps like the Globus prop map_Kerbin_sat texture?

**Comment by Alexustas** [comment]
> Should I make a JSIOrbitDisplay replacement for MAS?

I would like, that there was no direct dependence on the RPM. So, yes.

> One other question - how hard is it to make Mun and Minmus maps like the Globus prop map_Kerbin_sat texture?

these planetoids do not have oceans and continents, so their maps (for me) look boring and not very informative.  But it is not difficult, I can do it if necessary.

**Comment by MOARdV** [comment]
> I would like, that there was no direct dependence on the RPM. So, yes.

Okay, will make a MAS orbit display.

> these planetoids do not have oceans and continents, so their maps (for me) look boring and not very informative

If it is easy, and you can tell me how, I can make them.  I have map displays on the MFD using the Globus texture, and I would like to have the moons of Kerbin visible also.

**Comment by Alexustas** [comment]
Should I add a grid on maps just as I did on the map of Kerbin?

**Comment by Alexustas** [comment]
Mun and Minmus maps

https://www.dropbox.com/sh/km20xtk7dbzcfxv/AAC7jtN5RTxOGJkOAIaXEU16a?dl=0

**Comment by MOARdV** [comment]
These are perfect.  Thank you!
