### ISSUE TITLE
Science support

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#93]
Once I figure out just what I need to support, and how...

Should probably consider integrating support for DMagic Orbital Science.

**Comment by Alexustas** [comment]
since I have never played in a career and science mode, I do not know what is needed for this. but I understand that some kind of science support is necessary, since I have repeatedly received requests for work with science from other users.

**Comment by MOARdV** [comment]
I also never played career and science mode.  I know there are experiments, and ways to store results, and ways to transmit results, but that is about the limit of my understanding.

**Comment by theonegalen** [comment]
Being able to view what science parts are on a vessel, and select, review, or use them individually would be nice. Right now, I use Action Groups for "Run science" and "Transmit All Science" when I play, but it would be nice to leave the UI off completely.

**Comment by MOARdV** [comment]
Closing this as it is supplanted by the much better specified Issue #141
