### ISSUE TITLE
More vessel Target methods

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#94]
This will help with eventual menus, but can also be used now:

- [x] `fc.SetTargetVessel(id)`: 
- [x] `fc.TargetVesselCount()`: Already exists.
- [x] `fc.TargetVesselDistance(id)`: 
- [x] `fc.TargetVesselName(id)`: 
- [x] `fc.TargetOrbitSpeed()`
- [x] `fc.TargetRelativeSpeed()` - actually, it is `fc.TargetSpeed()`
- [x] `fc.TargetSituation()`
- [x] `fc.TargetApproachSpeed()` - actually, `fc.ApproachSpeed()`
- [x] `fc.TargetAvailableDockingPorts()`: only works on vessel target, when vessel is close enough to load, I think.
- [x] `nav.TargetBearing(relative)`
- [x] `nav.TargetGroundDistance()`

Are there other information that must be available?  I do not want to add too many, but these are enough to make a simple list like the RPM target menu allows.

**Comment by Alexustas** [comment]
- TargetVesselType (for filter )

and for already selected target:

 - orbitspeed
 - relative speed
 - situation 
 - info about available docking ports (if target is vessel)

and if this can give some performance gains, then you can add the following methods for Navigation:
- bearing form vessel to selected target (relative and absolute)
- ground distace from vessel to selected target

**Comment by Alexustas** [comment]
- target approach speed

**Comment by MOARdV** [comment]
Closing, since the target filters really should be a separate issue (#109)
