### ISSUE TITLE
Alternate shader for lines

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#96]
Currently, I use Particles/Additive, which is okay ... but it is partially transparent, so the lines I render are not opaque.  Look into a different shader, or altering Additive so it's not making partially-transparent lines.

**Comment by Alexustas** [comment]
I also noticed this. it will be cool if you can fix it

**Comment by MOARdV** [comment]
I updated the LINE_STRING and GROUND_TRACK shaders with the release last night.  The colors look correct, although I have not verified that textures still work as intended for LINE_STRING (they should).  Once I confirm that textures still work the correct way, I will replace the other places where the particle shader is being used.

**Comment by Alexustas** [comment]
Is a bug with the size of the track fixed  in this update?

**Comment by Alexustas** [comment]
> I have not verified that textures still work as intended

![bandicam 2017-12-08 20-35-54-887](https://user-images.githubusercontent.com/6713671/33772804-ab567f16-dc57-11e7-9503-e7d60a313537.jpg)

![bandicam 2017-12-08 20-37-29-997](https://user-images.githubusercontent.com/6713671/33772807-ae4a4888-dc57-11e7-8c0f-7f60caa9a536.jpg)

**Comment by MOARdV** [comment]
> Is a bug with the size of the track fixed in this update?

No.  It will be fixed this weekend.
