### ISSUE TITLE
Additional Keywords

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#97]
Can you add two additional keywords for the IMAGE node:

- %VESSEL_ICON%
- %TARGET_VESSEL_ICON%

These keywords display the **stock** icon of the ship or the target, respectively

This will be useful for designating spacecraft on maps, in the targets menu and so on

**Comment by MOARdV** [comment]
I can do slightly more than that.
* %MAP_ICON% - any stock map view icon (ship, apsis).
* fc.MapIconU(id), fc.MapIconV(id) - for `shiftUV`.  Can be a vessel type, such as fc.TargetType(), or one of some other numbers for map icons (planet, enterSOI, exitSOI, node, Ap, Pe - all of the map icons).  They are all on the same texture atlas.

**Comment by MOARdV** [comment]
Hmm.  The old map view texture atlas does not include Relay and Plane vessel types.  I can convert those types to Probe and Ship for the time being while I find the new icons.

**Comment by MOARdV** [comment]
All %MAP_ICON% is complete.  [DropBox](https://www.dropbox.com/s/3j0k2q5hesb84bq/AvionicsSystems-0.11.0b2.zip?dl=0).  Also has orbit time fixes.

Use [%MAP_ICON%](https://github.com/MOARdV/AvionicsSystems/wiki/Keyword#map_icon) for texture name, `tiling = 0.2, 0.2`.  Choose icon with `uvShift = fc.MapIconU(iconId), fc.MapIconV(iconId)` ([see](https://github.com/MOARdV/AvionicsSystems/wiki/MASFlightComputerProxy2#fcmapiconudouble-iconid)).  For targets, iconId = `fc.TargetTypeId()` ([see](https://github.com/MOARdV/AvionicsSystems/wiki/MASFlightComputerProxy3#fctargettypeid))
