### ISSUE TITLE
Incorrect calculations of fc.TimeToANEq() and fc.TimeToDNEq() on Warp

### ISSUE THREAD

**Issue by Alexustas** [MOARdV/AvionicsSystems#99]
watch this video

https://youtu.be/nFoghKI_n24

**Comment by MOARdV** [comment]
Fixed.  Will post new build later.

**Comment by Alexustas** [comment]
`fc.TimeToANTarget()`  and `fc.TimeToDNTarget()` the same thing

**Comment by MOARdV** [comment]
Yes, all orbit time computations except time to Ap, time to Pe, and orbit period are affected by the same bug, caused when the vessel goes "on rails" during time warp.  Fortunately, the fix was small, and it fixes all of the bugs,
